//------------------------------------------------------------------------------
// <auto-generated />
//
// This file was automatically generated by SWIG (https://www.swig.org).
// Version 4.4.0
//
// Do not make changes to this file unless you know what you are doing - modify
// the SWIG interface file instead.
//------------------------------------------------------------------------------

namespace csp.common {

public enum ESequenceUpdateType {
  Create = 0,
  Update = 1,
  Delete = 3,
  Invalid = 4
}

}
