//------------------------------------------------------------------------------
// <auto-generated />
//
// This file was automatically generated by SWIG (https://www.swig.org).
// Version 4.4.0
//
// Do not make changes to this file unless you know what you are doing - modify
// the SWIG interface file instead.
//------------------------------------------------------------------------------

namespace csp.common {

#nullable enable

public class SettingsCollectionList : global::System.IDisposable, global::System.Collections.IEnumerable, global::System.Collections.Generic.IList<csp.common.SettingsCollection>
 {
  private global::System.Runtime.InteropServices.HandleRef swigCPtr;
  protected bool swigCMemOwn;

  internal SettingsCollectionList(global::System.IntPtr cPtr, bool cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = new global::System.Runtime.InteropServices.HandleRef(this, cPtr);
  }

  internal static global::System.Runtime.InteropServices.HandleRef getCPtr(SettingsCollectionList obj) {
    return (obj == null) ? new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero) : obj.swigCPtr;
  }

  internal static global::System.Runtime.InteropServices.HandleRef swigRelease(SettingsCollectionList obj) {
    if (obj != null) {
      if (!obj.swigCMemOwn)
        throw new global::System.ApplicationException("Cannot release ownership as memory is not owned");
      global::System.Runtime.InteropServices.HandleRef ptr = obj.swigCPtr;
      obj.swigCMemOwn = false;
      obj.Dispose();
      return ptr;
    } else {
      return new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero);
    }
  }

  ~SettingsCollectionList() {
    Dispose(false);
  }

  public void Dispose() {
    Dispose(true);
    global::System.GC.SuppressFinalize(this);
  }

  protected virtual void Dispose(bool disposing) {
    lock(this) {
      if (swigCPtr.Handle != global::System.IntPtr.Zero) {
        if (swigCMemOwn) {
          swigCMemOwn = false;
          ConnectedSpacesPlatformDotNetPINVOKE.delete_csp_common_SettingsCollectionList(swigCPtr);
        }
        swigCPtr = new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero);
      }
    }
  }

  public SettingsCollectionList(global::System.Collections.IEnumerable c) : this() {
    if (c == null)
      throw new global::System.ArgumentNullException("c");
    foreach (csp.common.SettingsCollection element in c) {
      this.Add(element);
    }
  }

  public SettingsCollectionList(global::System.Collections.Generic.IEnumerable<csp.common.SettingsCollection> c) : this() {
    if (c == null)
      throw new global::System.ArgumentNullException("c");
    foreach (csp.common.SettingsCollection element in c) {
      this.Add(element);
    }
  }

  public bool IsFixedSize {
    get {
      return false;
    }
  }

  public bool IsReadOnly {
    get {
      return false;
    }
  }

  public csp.common.SettingsCollection this[int index]  {
    get {
      return getitem(index);
    }
    set {
      setitem(index, value);
    }
  }

  public bool IsEmpty {
    get {
      return Size() == 0;
    }
  }

  public int Count {
    get {
      return (int)Size();
    }
  }

  public bool IsSynchronized {
    get {
      return false;
    }
  }

  public void CopyTo(csp.common.SettingsCollection[] outArray)
  {
    CopyTo(0, outArray, 0, this.Count);
  }

  public void CopyTo(csp.common.SettingsCollection[] outArray, int outStartIndex)
  {
    CopyTo(0, outArray, outStartIndex, this.Count);
  }

  public void CopyTo(int srcStartIndex, csp.common.SettingsCollection[] outArray, int outStartIndex, int count)
  {
    if (outArray == null)
      throw new global::System.ArgumentNullException("outArray");
    if (srcStartIndex < 0)
      throw new global::System.ArgumentOutOfRangeException("srcStartIndex", "Value is less than zero");
    if (outStartIndex < 0)
      throw new global::System.ArgumentOutOfRangeException("outStartIndex", "Value is less than zero");
    if (count < 0)
      throw new global::System.ArgumentOutOfRangeException("count", "Value is less than zero");
    if (outArray.Rank > 1)
      throw new global::System.ArgumentException("Multi dimensional array.", "array");
    if (srcStartIndex+count > this.Count || outStartIndex+count > outArray.Length)
      throw new global::System.ArgumentException("Number of elements to copy is too large.");
    for (int i=0; i<count; i++)
      outArray.SetValue(getitemcopy(srcStartIndex+i), outStartIndex+i);
  }

  public csp.common.SettingsCollection[] DeepCopyToArray()
  {
    int count = this.Count;
    csp.common.SettingsCollection[] result = new csp.common.SettingsCollection[count];
    for (int i = 0; i < count; i++)
      result[i] = getitemcopy(i);
    return result;
  }
  
  public global::System.Collections.Generic.List<csp.common.SettingsCollection> DeepCopyToList()
  {
    int count = this.Count;
    global::System.Collections.Generic.List<csp.common.SettingsCollection> result = 
      new global::System.Collections.Generic.List<csp.common.SettingsCollection>(count);
    for (int i = 0; i < count; i++)
      result.Add(getitemcopy(i));
    return result;
  }
  
  global::System.Collections.Generic.IEnumerator<csp.common.SettingsCollection> global::System.Collections.Generic.IEnumerable<csp.common.SettingsCollection>.GetEnumerator() {
    return new SettingsCollectionListEnumerator(this);
  }

  global::System.Collections.IEnumerator global::System.Collections.IEnumerable.GetEnumerator() {
    return new SettingsCollectionListEnumerator(this);
  }

  public SettingsCollectionListEnumerator GetEnumerator() {
    return new SettingsCollectionListEnumerator(this);
  }

  // Type-safe enumerator
  /// Note that the IEnumerator documentation requires an InvalidOperationException to be thrown
  /// whenever the collection is modified. This has been done for changes in the Size of the
  /// collection but not when one of the elements of the collection is modified as it is a bit
  /// tricky to detect unmanaged code that modifies the collection under our feet.
  public sealed class SettingsCollectionListEnumerator : global::System.Collections.IEnumerator
    , global::System.Collections.Generic.IEnumerator<csp.common.SettingsCollection>
  {
    private SettingsCollectionList collectionRef;
    private int currentIndex;
    private object currentObject;
    private int currentSize;

    public SettingsCollectionListEnumerator(SettingsCollectionList collection) {
      collectionRef = collection;
      currentIndex = -1;
      currentObject = null;
      currentSize = collectionRef.Count;
    }

    // Type-safe iterator Current
    public csp.common.SettingsCollection Current {
      get {
        if (currentIndex == -1)
          throw new global::System.InvalidOperationException("Enumeration not started.");
        if (currentIndex > currentSize - 1)
          throw new global::System.InvalidOperationException("Enumeration finished.");
        if (currentObject == null)
          throw new global::System.InvalidOperationException("Collection modified.");
        return (csp.common.SettingsCollection)currentObject;
      }
    }

    // Type-unsafe IEnumerator.Current
    object global::System.Collections.IEnumerator.Current {
      get {
        return Current;
      }
    }

    public bool MoveNext() {
      int Size = collectionRef.Count;
      bool moveOkay = (currentIndex+1 < Size) && (Size == currentSize);
      if (moveOkay) {
        currentIndex++;
        currentObject = collectionRef[currentIndex];
      } else {
        currentObject = null;
      }
      return moveOkay;
    }

    public void Reset() {
      currentIndex = -1;
      currentObject = null;
      if (collectionRef.Count != currentSize) {
        throw new global::System.InvalidOperationException("Collection modified.");
      }
    }

    public void Dispose() {
        currentIndex = -1;
        currentObject = null;
    }
  }

  public SettingsCollectionList() : this(ConnectedSpacesPlatformDotNetPINVOKE.new_csp_common_SettingsCollectionList__SWIG_0(), true) {
    if (ConnectedSpacesPlatformDotNetPINVOKE.SWIGPendingException.Pending) throw ConnectedSpacesPlatformDotNetPINVOKE.SWIGPendingException.Retrieve();
  }

  public SettingsCollectionList(csp.common.SettingsCollectionList other) : this(ConnectedSpacesPlatformDotNetPINVOKE.new_csp_common_SettingsCollectionList__SWIG_1(csp.common.SettingsCollectionList.getCPtr(other)), true) {
    if (ConnectedSpacesPlatformDotNetPINVOKE.SWIGPendingException.Pending) throw ConnectedSpacesPlatformDotNetPINVOKE.SWIGPendingException.Retrieve();
  }

  private uint Size() {
    uint ret = ConnectedSpacesPlatformDotNetPINVOKE.csp_common_SettingsCollectionList_Size(swigCPtr);
    if (ConnectedSpacesPlatformDotNetPINVOKE.SWIGPendingException.Pending) throw ConnectedSpacesPlatformDotNetPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public void Insert(uint Index, csp.common.SettingsCollection item) {
    ConnectedSpacesPlatformDotNetPINVOKE.csp_common_SettingsCollectionList_Insert__SWIG_0(swigCPtr, Index, csp.common.SettingsCollection.getCPtr(item));
    if (ConnectedSpacesPlatformDotNetPINVOKE.SWIGPendingException.Pending) throw ConnectedSpacesPlatformDotNetPINVOKE.SWIGPendingException.Retrieve();
  }

  public void Clear() {
    ConnectedSpacesPlatformDotNetPINVOKE.csp_common_SettingsCollectionList_Clear(swigCPtr);
    if (ConnectedSpacesPlatformDotNetPINVOKE.SWIGPendingException.Pending) throw ConnectedSpacesPlatformDotNetPINVOKE.SWIGPendingException.Retrieve();
  }

  public void Add(csp.common.SettingsCollection x) {
    ConnectedSpacesPlatformDotNetPINVOKE.csp_common_SettingsCollectionList_Add(swigCPtr, csp.common.SettingsCollection.getCPtr(x));
    if (ConnectedSpacesPlatformDotNetPINVOKE.SWIGPendingException.Pending) throw ConnectedSpacesPlatformDotNetPINVOKE.SWIGPendingException.Retrieve();
  }

  public SettingsCollectionList(int capacity) : this(ConnectedSpacesPlatformDotNetPINVOKE.new_csp_common_SettingsCollectionList__SWIG_2(capacity), true) {
    if (ConnectedSpacesPlatformDotNetPINVOKE.SWIGPendingException.Pending) throw ConnectedSpacesPlatformDotNetPINVOKE.SWIGPendingException.Retrieve();
  }

  private csp.common.SettingsCollection getitemcopy(int index) {
    csp.common.SettingsCollection ret = new csp.common.SettingsCollection(ConnectedSpacesPlatformDotNetPINVOKE.csp_common_SettingsCollectionList_getitemcopy(swigCPtr, index), true);
    if (ConnectedSpacesPlatformDotNetPINVOKE.SWIGPendingException.Pending) throw ConnectedSpacesPlatformDotNetPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  private csp.common.SettingsCollection getitem(int index) {
  global::System.IntPtr cPtr = ConnectedSpacesPlatformDotNetPINVOKE.csp_common_SettingsCollectionList_getitem(swigCPtr, index);
    if (ConnectedSpacesPlatformDotNetPINVOKE.SWIGPendingException.Pending) throw ConnectedSpacesPlatformDotNetPINVOKE.SWIGPendingException.Retrieve();
  csp.common.SettingsCollection ret = null;
  if (cPtr != global::System.IntPtr.Zero) {
    ret = new csp.common.SettingsCollection(cPtr, false);
    ret.OuterObjectPin = this;
  }
  return ret;
}

  private void setitem(int index, csp.common.SettingsCollection val) {
    ConnectedSpacesPlatformDotNetPINVOKE.csp_common_SettingsCollectionList_setitem(swigCPtr, index, csp.common.SettingsCollection.getCPtr(val));
    if (ConnectedSpacesPlatformDotNetPINVOKE.SWIGPendingException.Pending) throw ConnectedSpacesPlatformDotNetPINVOKE.SWIGPendingException.Retrieve();
  }

  public void Insert(int index, csp.common.SettingsCollection x) {
    ConnectedSpacesPlatformDotNetPINVOKE.csp_common_SettingsCollectionList_Insert__SWIG_1(swigCPtr, index, csp.common.SettingsCollection.getCPtr(x));
    if (ConnectedSpacesPlatformDotNetPINVOKE.SWIGPendingException.Pending) throw ConnectedSpacesPlatformDotNetPINVOKE.SWIGPendingException.Retrieve();
  }

  public void RemoveAt(int index) {
    ConnectedSpacesPlatformDotNetPINVOKE.csp_common_SettingsCollectionList_RemoveAt(swigCPtr, index);
    if (ConnectedSpacesPlatformDotNetPINVOKE.SWIGPendingException.Pending) throw ConnectedSpacesPlatformDotNetPINVOKE.SWIGPendingException.Retrieve();
  }

  public void Reverse() {
    ConnectedSpacesPlatformDotNetPINVOKE.csp_common_SettingsCollectionList_Reverse__SWIG_0(swigCPtr);
    if (ConnectedSpacesPlatformDotNetPINVOKE.SWIGPendingException.Pending) throw ConnectedSpacesPlatformDotNetPINVOKE.SWIGPendingException.Retrieve();
  }

  public void Reverse(int index, int count) {
    ConnectedSpacesPlatformDotNetPINVOKE.csp_common_SettingsCollectionList_Reverse__SWIG_1(swigCPtr, index, count);
    if (ConnectedSpacesPlatformDotNetPINVOKE.SWIGPendingException.Pending) throw ConnectedSpacesPlatformDotNetPINVOKE.SWIGPendingException.Retrieve();
  }

  public void SetRange(int index, csp.common.SettingsCollectionList values) {
    ConnectedSpacesPlatformDotNetPINVOKE.csp_common_SettingsCollectionList_SetRange(swigCPtr, index, csp.common.SettingsCollectionList.getCPtr(values));
    if (ConnectedSpacesPlatformDotNetPINVOKE.SWIGPendingException.Pending) throw ConnectedSpacesPlatformDotNetPINVOKE.SWIGPendingException.Retrieve();
  }

  public bool Contains(csp.common.SettingsCollection value) {
    bool ret = ConnectedSpacesPlatformDotNetPINVOKE.csp_common_SettingsCollectionList_Contains(swigCPtr, csp.common.SettingsCollection.getCPtr(value));
    if (ConnectedSpacesPlatformDotNetPINVOKE.SWIGPendingException.Pending) throw ConnectedSpacesPlatformDotNetPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public int IndexOf(csp.common.SettingsCollection value) {
    int ret = ConnectedSpacesPlatformDotNetPINVOKE.csp_common_SettingsCollectionList_IndexOf(swigCPtr, csp.common.SettingsCollection.getCPtr(value));
    if (ConnectedSpacesPlatformDotNetPINVOKE.SWIGPendingException.Pending) throw ConnectedSpacesPlatformDotNetPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public int LastIndexOf(csp.common.SettingsCollection value) {
    int ret = ConnectedSpacesPlatformDotNetPINVOKE.csp_common_SettingsCollectionList_LastIndexOf(swigCPtr, csp.common.SettingsCollection.getCPtr(value));
    if (ConnectedSpacesPlatformDotNetPINVOKE.SWIGPendingException.Pending) throw ConnectedSpacesPlatformDotNetPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public bool Remove(csp.common.SettingsCollection value) {
    bool ret = ConnectedSpacesPlatformDotNetPINVOKE.csp_common_SettingsCollectionList_Remove(swigCPtr, csp.common.SettingsCollection.getCPtr(value));
    if (ConnectedSpacesPlatformDotNetPINVOKE.SWIGPendingException.Pending) throw ConnectedSpacesPlatformDotNetPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  // Any time this object is returned from an outer C++ object via reference, this is set
  // to prevent premature garbage collection causing premature C++ memory deallocation.
  public object OuterObjectPin { private get; set; }

}

}
