//------------------------------------------------------------------------------
// <auto-generated />
//
// This file was automatically generated by SWIG (https://www.swig.org).
// Version 4.4.0
//
// Do not make changes to this file unless you know what you are doing - modify
// the SWIG interface file instead.
//------------------------------------------------------------------------------

namespace csp.multiplayer {

#nullable enable

public class CustomSpaceComponent : csp.multiplayer.ComponentBase {
  private global::System.Runtime.InteropServices.HandleRef swigCPtr;

  internal CustomSpaceComponent(global::System.IntPtr cPtr, bool cMemoryOwn) : base(ConnectedSpacesPlatformDotNetPINVOKE.csp_multiplayer_CustomSpaceComponent_SWIGUpcast(cPtr), cMemoryOwn) {
    swigCPtr = new global::System.Runtime.InteropServices.HandleRef(this, cPtr);
  }

  internal static global::System.Runtime.InteropServices.HandleRef getCPtr(CustomSpaceComponent obj) {
    return (obj == null) ? new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero) : obj.swigCPtr;
  }

  internal static global::System.Runtime.InteropServices.HandleRef swigRelease(CustomSpaceComponent obj) {
    if (obj != null) {
      if (!obj.swigCMemOwn)
        throw new global::System.ApplicationException("Cannot release ownership as memory is not owned");
      global::System.Runtime.InteropServices.HandleRef ptr = obj.swigCPtr;
      obj.swigCMemOwn = false;
      obj.Dispose();
      return ptr;
    } else {
      return new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero);
    }
  }

  protected override void Dispose(bool disposing) {
    lock(this) {
      if (swigCPtr.Handle != global::System.IntPtr.Zero) {
        if (swigCMemOwn) {
          swigCMemOwn = false;
          ConnectedSpacesPlatformDotNetPINVOKE.delete_csp_multiplayer_CustomSpaceComponent(swigCPtr);
        }
        swigCPtr = new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero);
      }
      base.Dispose(disposing);
    }
  }


  // Returns null on failure.
  public static csp.multiplayer.CustomSpaceComponent? TryFromBaseCast(csp.multiplayer.ComponentBase baseObj)
  {
    return NativeFromBaseCast(baseObj);
  }

  // Throws ArgumentException on failure.
  public static csp.multiplayer.CustomSpaceComponent FromBaseCast(csp.multiplayer.ComponentBase baseObj)
  {
    csp.multiplayer.CustomSpaceComponent? derived = TryFromBaseCast(baseObj);
    if (derived == null){
      throw new System.ArgumentException("Failed to cast " + nameof(csp.multiplayer.ComponentBase) + " to " + nameof(csp.multiplayer.CustomSpaceComponent), "baseObj");
    }
    return derived;
  }


  public CustomSpaceComponent(csp.common.LogSystem LogSystem, csp.multiplayer.SpaceEntity Parent) : this(ConnectedSpacesPlatformDotNetPINVOKE.new_csp_multiplayer_CustomSpaceComponent((LogSystem != null && csp.common.LogSystem.getCPtr(LogSystem).Handle == global::System.IntPtr.Zero) ? throw new global::System.ObjectDisposedException("LogSystem", "Passed a disposed C# SWIG wrapper (null native handle) to C++. This indicates an object lifecycle bug needing investigation. Note: This does not detect C++-side deletions.") : csp.common.LogSystem.getCPtr(LogSystem), (Parent != null && csp.multiplayer.SpaceEntity.getCPtr(Parent).Handle == global::System.IntPtr.Zero) ? throw new global::System.ObjectDisposedException("Parent", "Passed a disposed C# SWIG wrapper (null native handle) to C++. This indicates an object lifecycle bug needing investigation. Note: This does not detect C++-side deletions.") : csp.multiplayer.SpaceEntity.getCPtr(Parent)), true) {
    if (ConnectedSpacesPlatformDotNetPINVOKE.SWIGPendingException.Pending) throw ConnectedSpacesPlatformDotNetPINVOKE.SWIGPendingException.Retrieve();
  }

  public string GetApplicationOrigin() {
    string ret = ConnectedSpacesPlatformDotNetPINVOKE.csp_multiplayer_CustomSpaceComponent_GetApplicationOrigin(swigCPtr);
    if (ConnectedSpacesPlatformDotNetPINVOKE.SWIGPendingException.Pending) throw ConnectedSpacesPlatformDotNetPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public void SetApplicationOrigin(string Value) {
    ConnectedSpacesPlatformDotNetPINVOKE.csp_multiplayer_CustomSpaceComponent_SetApplicationOrigin(swigCPtr, Value);
    if (ConnectedSpacesPlatformDotNetPINVOKE.SWIGPendingException.Pending) throw ConnectedSpacesPlatformDotNetPINVOKE.SWIGPendingException.Retrieve();
  }

  public bool HasCustomProperty(string Key) {
    bool ret = ConnectedSpacesPlatformDotNetPINVOKE.csp_multiplayer_CustomSpaceComponent_HasCustomProperty(swigCPtr, Key);
    if (ConnectedSpacesPlatformDotNetPINVOKE.SWIGPendingException.Pending) throw ConnectedSpacesPlatformDotNetPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public csp.common.ReplicatedValue GetCustomProperty(string Key) {
  global::System.IntPtr cPtr = ConnectedSpacesPlatformDotNetPINVOKE.csp_multiplayer_CustomSpaceComponent_GetCustomProperty(swigCPtr, Key);
    if (ConnectedSpacesPlatformDotNetPINVOKE.SWIGPendingException.Pending) throw ConnectedSpacesPlatformDotNetPINVOKE.SWIGPendingException.Retrieve();
  csp.common.ReplicatedValue ret = null;
  if (cPtr != global::System.IntPtr.Zero) {
    ret = new csp.common.ReplicatedValue(cPtr, false);
    ret.OuterObjectPin = this;
  }
  return ret;
}

  public void SetCustomProperty(string Key, csp.common.ReplicatedValue Value) {
    ConnectedSpacesPlatformDotNetPINVOKE.csp_multiplayer_CustomSpaceComponent_SetCustomProperty(swigCPtr, Key, csp.common.ReplicatedValue.getCPtr(Value));
    if (ConnectedSpacesPlatformDotNetPINVOKE.SWIGPendingException.Pending) throw ConnectedSpacesPlatformDotNetPINVOKE.SWIGPendingException.Retrieve();
  }

  public void RemoveCustomProperty(string Key) {
    ConnectedSpacesPlatformDotNetPINVOKE.csp_multiplayer_CustomSpaceComponent_RemoveCustomProperty(swigCPtr, Key);
    if (ConnectedSpacesPlatformDotNetPINVOKE.SWIGPendingException.Pending) throw ConnectedSpacesPlatformDotNetPINVOKE.SWIGPendingException.Retrieve();
  }

  public csp.common.StringList GetCustomPropertyKeys() {
    csp.common.StringList ret = new csp.common.StringList(ConnectedSpacesPlatformDotNetPINVOKE.csp_multiplayer_CustomSpaceComponent_GetCustomPropertyKeys(swigCPtr), true);
    if (ConnectedSpacesPlatformDotNetPINVOKE.SWIGPendingException.Pending) throw ConnectedSpacesPlatformDotNetPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public int GetNumProperties() {
    int ret = ConnectedSpacesPlatformDotNetPINVOKE.csp_multiplayer_CustomSpaceComponent_GetNumProperties(swigCPtr);
    if (ConnectedSpacesPlatformDotNetPINVOKE.SWIGPendingException.Pending) throw ConnectedSpacesPlatformDotNetPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public uint GetCustomPropertySubscriptionKey(string Key) {
    uint ret = ConnectedSpacesPlatformDotNetPINVOKE.csp_multiplayer_CustomSpaceComponent_GetCustomPropertySubscriptionKey(swigCPtr, Key);
    if (ConnectedSpacesPlatformDotNetPINVOKE.SWIGPendingException.Pending) throw ConnectedSpacesPlatformDotNetPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  // Any time this object is returned from an outer C++ object via reference, this is set
  // to prevent premature garbage collection causing premature C++ memory deallocation.
  public object OuterObjectPin { private get; set; }

  internal static csp.multiplayer.CustomSpaceComponent NativeFromBaseCast(csp.multiplayer.ComponentBase baseObj) {
    global::System.IntPtr cPtr = ConnectedSpacesPlatformDotNetPINVOKE.csp_multiplayer_CustomSpaceComponent_NativeFromBaseCast((baseObj != null && csp.multiplayer.ComponentBase.getCPtr(baseObj).Handle == global::System.IntPtr.Zero) ? throw new global::System.ObjectDisposedException("baseObj", "Passed a disposed C# SWIG wrapper (null native handle) to C++. This indicates an object lifecycle bug needing investigation. Note: This does not detect C++-side deletions.") : csp.multiplayer.ComponentBase.getCPtr(baseObj));
    csp.multiplayer.CustomSpaceComponent ret = (cPtr == global::System.IntPtr.Zero) ? null : new csp.multiplayer.CustomSpaceComponent(cPtr, false);
    if (ConnectedSpacesPlatformDotNetPINVOKE.SWIGPendingException.Pending) throw ConnectedSpacesPlatformDotNetPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

}

}
