//------------------------------------------------------------------------------
// <auto-generated />
//
// This file was automatically generated by SWIG (https://www.swig.org).
// Version 4.4.0
//
// Do not make changes to this file unless you know what you are doing - modify
// the SWIG interface file instead.
//------------------------------------------------------------------------------

namespace csp.multiplayer {

#nullable enable

public interface IExternalResourceComponent {
  [System.ComponentModel.EditorBrowsable(System.ComponentModel.EditorBrowsableState.Never)]
  global::System.Runtime.InteropServices.HandleRef GetInterfaceCPtr();
  string GetExternalResourceAssetId();
  void SetExternalResourceAssetId(string InValue);
  string GetExternalResourceAssetCollectionId();
  void SetExternalResourceAssetCollectionId(string InValue);
}

}
