//------------------------------------------------------------------------------
// <auto-generated />
//
// This file was automatically generated by SWIG (https://www.swig.org).
// Version 4.4.0
//
// Do not make changes to this file unless you know what you are doing - modify
// the SWIG interface file instead.
//------------------------------------------------------------------------------

namespace csp.multiplayer {

#nullable enable

public class ITransformComponentSwigImpl : ITransformComponent, IPositionComponent, IRotationComponent, IScaleComponent, global::System.IDisposable {
  private global::System.Runtime.InteropServices.HandleRef swigCPtr;
  protected bool swigCMemOwn;

  internal ITransformComponentSwigImpl(global::System.IntPtr cPtr, bool cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = new global::System.Runtime.InteropServices.HandleRef(this, cPtr);
  }

  internal static global::System.Runtime.InteropServices.HandleRef getCPtr(ITransformComponentSwigImpl obj) {
    return (obj == null) ? new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero) : obj.swigCPtr;
  }

  internal static global::System.Runtime.InteropServices.HandleRef swigRelease(ITransformComponentSwigImpl obj) {
    if (obj != null) {
      if (!obj.swigCMemOwn)
        throw new global::System.ApplicationException("Cannot release ownership as memory is not owned");
      global::System.Runtime.InteropServices.HandleRef ptr = obj.swigCPtr;
      obj.swigCMemOwn = false;
      obj.Dispose();
      return ptr;
    } else {
      return new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero);
    }
  }

  ~ITransformComponentSwigImpl() {
    Dispose(false);
  }

  public void Dispose() {
    Dispose(true);
    global::System.GC.SuppressFinalize(this);
  }

  protected virtual void Dispose(bool disposing) {
    lock(this) {
      if (swigCPtr.Handle != global::System.IntPtr.Zero) {
        if (swigCMemOwn) {
          swigCMemOwn = false;
          throw new global::System.MethodAccessException("C++ destructor does not have public access");
        }
        swigCPtr = new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero);
      }
    }
  }

  [System.ComponentModel.EditorBrowsable(System.ComponentModel.EditorBrowsableState.Never)]
  global::System.Runtime.InteropServices.HandleRef ITransformComponent.GetInterfaceCPtr() {
    return new global::System.Runtime.InteropServices.HandleRef(this, ConnectedSpacesPlatformDotNetPINVOKE.csp_multiplayer_ITransformComponentSwigImpl_ITransformComponent_GetInterfaceCPtr(swigCPtr.Handle));
  }

  [System.ComponentModel.EditorBrowsable(System.ComponentModel.EditorBrowsableState.Never)]
  global::System.Runtime.InteropServices.HandleRef IPositionComponent.GetInterfaceCPtr() {
    return new global::System.Runtime.InteropServices.HandleRef(this, ConnectedSpacesPlatformDotNetPINVOKE.csp_multiplayer_ITransformComponentSwigImpl_IPositionComponent_GetInterfaceCPtr(swigCPtr.Handle));
  }

  [System.ComponentModel.EditorBrowsable(System.ComponentModel.EditorBrowsableState.Never)]
  global::System.Runtime.InteropServices.HandleRef IRotationComponent.GetInterfaceCPtr() {
    return new global::System.Runtime.InteropServices.HandleRef(this, ConnectedSpacesPlatformDotNetPINVOKE.csp_multiplayer_ITransformComponentSwigImpl_IRotationComponent_GetInterfaceCPtr(swigCPtr.Handle));
  }

  [System.ComponentModel.EditorBrowsable(System.ComponentModel.EditorBrowsableState.Never)]
  global::System.Runtime.InteropServices.HandleRef IScaleComponent.GetInterfaceCPtr() {
    return new global::System.Runtime.InteropServices.HandleRef(this, ConnectedSpacesPlatformDotNetPINVOKE.csp_multiplayer_ITransformComponentSwigImpl_IScaleComponent_GetInterfaceCPtr(swigCPtr.Handle));
  }

  public virtual csp.multiplayer.SpaceTransform GetTransform() {
    csp.multiplayer.SpaceTransform ret = new csp.multiplayer.SpaceTransform(ConnectedSpacesPlatformDotNetPINVOKE.csp_multiplayer_ITransformComponentSwigImpl_GetTransform(swigCPtr), true);
    if (ConnectedSpacesPlatformDotNetPINVOKE.SWIGPendingException.Pending) throw ConnectedSpacesPlatformDotNetPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public virtual void SetTransform(csp.multiplayer.SpaceTransform InValue) {
    ConnectedSpacesPlatformDotNetPINVOKE.csp_multiplayer_ITransformComponentSwigImpl_SetTransform(swigCPtr, csp.multiplayer.SpaceTransform.getCPtr(InValue));
    if (ConnectedSpacesPlatformDotNetPINVOKE.SWIGPendingException.Pending) throw ConnectedSpacesPlatformDotNetPINVOKE.SWIGPendingException.Retrieve();
  }

  public virtual csp.common.Vector3 GetPosition() {
  global::System.IntPtr cPtr = ConnectedSpacesPlatformDotNetPINVOKE.csp_multiplayer_ITransformComponentSwigImpl_GetPosition(swigCPtr);
    if (ConnectedSpacesPlatformDotNetPINVOKE.SWIGPendingException.Pending) throw ConnectedSpacesPlatformDotNetPINVOKE.SWIGPendingException.Retrieve();
  csp.common.Vector3 ret = null;
  if (cPtr != global::System.IntPtr.Zero) {
    ret = new csp.common.Vector3(cPtr, false);
    ret.OuterObjectPin = this;
  }
  return ret;
}

  public virtual void SetPosition(csp.common.Vector3 InValue) {
    ConnectedSpacesPlatformDotNetPINVOKE.csp_multiplayer_ITransformComponentSwigImpl_SetPosition(swigCPtr, csp.common.Vector3.getCPtr(InValue));
    if (ConnectedSpacesPlatformDotNetPINVOKE.SWIGPendingException.Pending) throw ConnectedSpacesPlatformDotNetPINVOKE.SWIGPendingException.Retrieve();
  }

  public virtual csp.common.Vector4 GetRotation() {
  global::System.IntPtr cPtr = ConnectedSpacesPlatformDotNetPINVOKE.csp_multiplayer_ITransformComponentSwigImpl_GetRotation(swigCPtr);
    if (ConnectedSpacesPlatformDotNetPINVOKE.SWIGPendingException.Pending) throw ConnectedSpacesPlatformDotNetPINVOKE.SWIGPendingException.Retrieve();
  csp.common.Vector4 ret = null;
  if (cPtr != global::System.IntPtr.Zero) {
    ret = new csp.common.Vector4(cPtr, false);
    ret.OuterObjectPin = this;
  }
  return ret;
}

  public virtual void SetRotation(csp.common.Vector4 InValue) {
    ConnectedSpacesPlatformDotNetPINVOKE.csp_multiplayer_ITransformComponentSwigImpl_SetRotation(swigCPtr, csp.common.Vector4.getCPtr(InValue));
    if (ConnectedSpacesPlatformDotNetPINVOKE.SWIGPendingException.Pending) throw ConnectedSpacesPlatformDotNetPINVOKE.SWIGPendingException.Retrieve();
  }

  public virtual csp.common.Vector3 GetScale() {
  global::System.IntPtr cPtr = ConnectedSpacesPlatformDotNetPINVOKE.csp_multiplayer_ITransformComponentSwigImpl_GetScale(swigCPtr);
    if (ConnectedSpacesPlatformDotNetPINVOKE.SWIGPendingException.Pending) throw ConnectedSpacesPlatformDotNetPINVOKE.SWIGPendingException.Retrieve();
  csp.common.Vector3 ret = null;
  if (cPtr != global::System.IntPtr.Zero) {
    ret = new csp.common.Vector3(cPtr, false);
    ret.OuterObjectPin = this;
  }
  return ret;
}

  public virtual void SetScale(csp.common.Vector3 InValue) {
    ConnectedSpacesPlatformDotNetPINVOKE.csp_multiplayer_ITransformComponentSwigImpl_SetScale(swigCPtr, csp.common.Vector3.getCPtr(InValue));
    if (ConnectedSpacesPlatformDotNetPINVOKE.SWIGPendingException.Pending) throw ConnectedSpacesPlatformDotNetPINVOKE.SWIGPendingException.Retrieve();
  }

}

}
