//------------------------------------------------------------------------------
// <auto-generated />
//
// This file was automatically generated by SWIG (https://www.swig.org).
// Version 4.4.0
//
// Do not make changes to this file unless you know what you are doing - modify
// the SWIG interface file instead.
//------------------------------------------------------------------------------

namespace csp.multiplayer {

public enum VideoPlayerPropertyKeys : ushort {
  Name_DEPRECATED = 0,
  VideoAssetId,
  VideoAssetURL,
  AssetCollectionId,
  Position,
  Rotation,
  Scale,
  IsStateShared,
  IsAutoPlay,
  IsLoopPlayback,
  IsAutoResize,
  AttenuationRadius,
  PlaybackState,
  CurrentPlayheadPosition,
  TimeSincePlay,
  VideoPlayerSourceType,
  IsVisible,
  IsARVisible,
  MeshComponentId,
  IsEnabled,
  IsVirtualVisible,
  StereoVideoType,
  IsStereoFlipped,
  Volume,
  AudioType,
  Num
}

}
