//------------------------------------------------------------------------------
// <auto-generated />
//
// This file was automatically generated by SWIG (https://www.swig.org).
// Version 4.4.0
//
// Do not make changes to this file unless you know what you are doing - modify
// the SWIG interface file instead.
//------------------------------------------------------------------------------


#nullable enable

public class SequenceChangedEventCallbackAdapter : global::System.IDisposable {
  private global::System.Runtime.InteropServices.HandleRef swigCPtr;
  protected bool swigCMemOwn;

  internal SequenceChangedEventCallbackAdapter(global::System.IntPtr cPtr, bool cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = new global::System.Runtime.InteropServices.HandleRef(this, cPtr);
  }

  internal static global::System.Runtime.InteropServices.HandleRef getCPtr(SequenceChangedEventCallbackAdapter obj) {
    return (obj == null) ? new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero) : obj.swigCPtr;
  }

  internal static global::System.Runtime.InteropServices.HandleRef swigRelease(SequenceChangedEventCallbackAdapter obj) {
    if (obj != null) {
      if (!obj.swigCMemOwn)
        throw new global::System.ApplicationException("Cannot release ownership as memory is not owned");
      global::System.Runtime.InteropServices.HandleRef ptr = obj.swigCPtr;
      obj.swigCMemOwn = false;
      obj.Dispose();
      return ptr;
    } else {
      return new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero);
    }
  }
  private static System.Collections.Concurrent.ConcurrentDictionary<global::System.IntPtr, global::System.WeakReference<SequenceChangedEventCallbackAdapter>> IL2CPPInstances = new();

  ~SequenceChangedEventCallbackAdapter() {
    Dispose(false);
  }

  public void Dispose() {
    Dispose(true);
    global::System.GC.SuppressFinalize(this);
  }

  protected virtual void Dispose(bool disposing) {
    lock(this) {
      if (swigCPtr.Handle != global::System.IntPtr.Zero) {
        if (swigCMemOwn) {
          swigCMemOwn = false;
          ConnectedSpacesPlatformDotNetPINVOKE.delete_SequenceChangedEventCallbackAdapter(swigCPtr);
        }
        var key = swigCPtr.Handle;
        swigCPtr = new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero);
        IL2CPPInstances.TryRemove(key, out _);
      }
    }
  }

  public virtual void Call(csp.common.SequenceChangedNetworkEventData eventData) {
    ConnectedSpacesPlatformDotNetPINVOKE.SequenceChangedEventCallbackAdapter_Call(swigCPtr, csp.common.SequenceChangedNetworkEventData.getCPtr(eventData));
    if (ConnectedSpacesPlatformDotNetPINVOKE.SWIGPendingException.Pending) throw ConnectedSpacesPlatformDotNetPINVOKE.SWIGPendingException.Retrieve();
  }

  public SequenceChangedEventCallbackAdapter() : this(ConnectedSpacesPlatformDotNetPINVOKE.new_SequenceChangedEventCallbackAdapter(), true) {
    if (ConnectedSpacesPlatformDotNetPINVOKE.SWIGPendingException.Pending) throw ConnectedSpacesPlatformDotNetPINVOKE.SWIGPendingException.Retrieve();
    SwigDirectorConnect();
  }

  private void SwigDirectorConnect() {
    if (SwigDerivedClassHasMethod("Call", swigMethodTypes0))
      swigDelegate0 = new SwigDelegateSequenceChangedEventCallbackAdapter_0(SwigDirectorMethodCall);
    IL2CPPInstances[swigCPtr.Handle] = new global::System.WeakReference<SequenceChangedEventCallbackAdapter>(this);
    ConnectedSpacesPlatformDotNetPINVOKE.SequenceChangedEventCallbackAdapter_director_connect(swigCPtr, swigDelegate0);
  }

  private bool SwigDerivedClassHasMethod(string methodName, global::System.Type[] methodTypes) {
    global::System.Reflection.MethodInfo[] methodInfos = this.GetType().GetMethods(
        global::System.Reflection.BindingFlags.Public | global::System.Reflection.BindingFlags.NonPublic | global::System.Reflection.BindingFlags.Instance);
    foreach (global::System.Reflection.MethodInfo methodInfo in methodInfos) {
      if (methodInfo.DeclaringType == null)
        continue;

      if (methodInfo.Name != methodName)
        continue;

      var parameters = methodInfo.GetParameters();
      if (parameters.Length != methodTypes.Length)
        continue;

      bool parametersMatch = true;
      for (var i = 0; i < parameters.Length; i++) {
        if (parameters[i].ParameterType != methodTypes[i]) {
          parametersMatch = false;
          break;
        }
      }

      if (!parametersMatch)
        continue;

      if (methodInfo.IsVirtual && (methodInfo.DeclaringType.IsSubclassOf(typeof(SequenceChangedEventCallbackAdapter))) &&
        methodInfo.DeclaringType != methodInfo.GetBaseDefinition().DeclaringType) {
        return true;
      }
    }

    return false;
  }

#if !UNITY_EDITOR && ENABLE_IL2CPP
  [AOT.MonoPInvokeCallback (typeof (SwigDelegateSequenceChangedEventCallbackAdapter_0))]
#endif
  private static void SwigDirectorMethodCall(global::System.IntPtr eventData, global::System.IntPtr ObjectData) {
    if (IL2CPPInstances.TryGetValue(ObjectData, out var wr) && wr.TryGetTarget(out var self))
    {
      self.Call(new csp.common.SequenceChangedNetworkEventData(eventData, true)) ;
    }
  }

  public delegate void SwigDelegateSequenceChangedEventCallbackAdapter_0(global::System.IntPtr eventData, global::System.IntPtr ObjectData);

  private SwigDelegateSequenceChangedEventCallbackAdapter_0 swigDelegate0;

  private static global::System.Type[] swigMethodTypes0 = new global::System.Type[] { typeof(csp.common.SequenceChangedNetworkEventData) };
}
