//------------------------------------------------------------------------------
// <auto-generated />
//
// This file was automatically generated by SWIG (https://www.swig.org).
// Version 4.4.0
//
// Do not make changes to this file unless you know what you are doing - modify
// the SWIG interface file instead.
//------------------------------------------------------------------------------


#nullable enable

public class TestBooleanResultCallbackAdapter : global::System.IDisposable {
  private global::System.Runtime.InteropServices.HandleRef swigCPtr;
  protected bool swigCMemOwn;

  internal TestBooleanResultCallbackAdapter(global::System.IntPtr cPtr, bool cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = new global::System.Runtime.InteropServices.HandleRef(this, cPtr);
  }

  internal static global::System.Runtime.InteropServices.HandleRef getCPtr(TestBooleanResultCallbackAdapter obj) {
    return (obj == null) ? new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero) : obj.swigCPtr;
  }

  internal static global::System.Runtime.InteropServices.HandleRef swigRelease(TestBooleanResultCallbackAdapter obj) {
    if (obj != null) {
      if (!obj.swigCMemOwn)
        throw new global::System.ApplicationException("Cannot release ownership as memory is not owned");
      global::System.Runtime.InteropServices.HandleRef ptr = obj.swigCPtr;
      obj.swigCMemOwn = false;
      obj.Dispose();
      return ptr;
    } else {
      return new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero);
    }
  }
  private static System.Collections.Concurrent.ConcurrentDictionary<global::System.IntPtr, global::System.WeakReference<TestBooleanResultCallbackAdapter>> IL2CPPInstances = new();

  ~TestBooleanResultCallbackAdapter() {
    Dispose(false);
  }

  public void Dispose() {
    Dispose(true);
    global::System.GC.SuppressFinalize(this);
  }

  protected virtual void Dispose(bool disposing) {
    lock(this) {
      if (swigCPtr.Handle != global::System.IntPtr.Zero) {
        if (swigCMemOwn) {
          swigCMemOwn = false;
          ConnectedSpacesPlatformDotNetPINVOKE.delete_TestBooleanResultCallbackAdapter(swigCPtr);
        }
        var key = swigCPtr.Handle;
        swigCPtr = new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero);
        IL2CPPInstances.TryRemove(key, out _);
      }
    }
  }

  public virtual void Call(extra.test.TestBooleanResult result) {
    ConnectedSpacesPlatformDotNetPINVOKE.TestBooleanResultCallbackAdapter_Call(swigCPtr, extra.test.TestBooleanResult.getCPtr(result));
    if (ConnectedSpacesPlatformDotNetPINVOKE.SWIGPendingException.Pending) throw ConnectedSpacesPlatformDotNetPINVOKE.SWIGPendingException.Retrieve();
  }

  public TestBooleanResultCallbackAdapter() : this(ConnectedSpacesPlatformDotNetPINVOKE.new_TestBooleanResultCallbackAdapter(), true) {
    if (ConnectedSpacesPlatformDotNetPINVOKE.SWIGPendingException.Pending) throw ConnectedSpacesPlatformDotNetPINVOKE.SWIGPendingException.Retrieve();
    SwigDirectorConnect();
  }

  private void SwigDirectorConnect() {
    if (SwigDerivedClassHasMethod("Call", swigMethodTypes0))
      swigDelegate0 = new SwigDelegateTestBooleanResultCallbackAdapter_0(SwigDirectorMethodCall);
    IL2CPPInstances[swigCPtr.Handle] = new global::System.WeakReference<TestBooleanResultCallbackAdapter>(this);
    ConnectedSpacesPlatformDotNetPINVOKE.TestBooleanResultCallbackAdapter_director_connect(swigCPtr, swigDelegate0);
  }

  private bool SwigDerivedClassHasMethod(string methodName, global::System.Type[] methodTypes) {
    global::System.Reflection.MethodInfo[] methodInfos = this.GetType().GetMethods(
        global::System.Reflection.BindingFlags.Public | global::System.Reflection.BindingFlags.NonPublic | global::System.Reflection.BindingFlags.Instance);
    foreach (global::System.Reflection.MethodInfo methodInfo in methodInfos) {
      if (methodInfo.DeclaringType == null)
        continue;

      if (methodInfo.Name != methodName)
        continue;

      var parameters = methodInfo.GetParameters();
      if (parameters.Length != methodTypes.Length)
        continue;

      bool parametersMatch = true;
      for (var i = 0; i < parameters.Length; i++) {
        if (parameters[i].ParameterType != methodTypes[i]) {
          parametersMatch = false;
          break;
        }
      }

      if (!parametersMatch)
        continue;

      if (methodInfo.IsVirtual && (methodInfo.DeclaringType.IsSubclassOf(typeof(TestBooleanResultCallbackAdapter))) &&
        methodInfo.DeclaringType != methodInfo.GetBaseDefinition().DeclaringType) {
        return true;
      }
    }

    return false;
  }

#if !UNITY_EDITOR && ENABLE_IL2CPP
  [AOT.MonoPInvokeCallback (typeof (SwigDelegateTestBooleanResultCallbackAdapter_0))]
#endif
  private static void SwigDirectorMethodCall(global::System.IntPtr result, global::System.IntPtr ObjectData) {
    if (IL2CPPInstances.TryGetValue(ObjectData, out var wr) && wr.TryGetTarget(out var self))
    {
      self.Call(new extra.test.TestBooleanResult(result, true)) ;
    }
  }

  public delegate void SwigDelegateTestBooleanResultCallbackAdapter_0(global::System.IntPtr result, global::System.IntPtr ObjectData);

  private SwigDelegateTestBooleanResultCallbackAdapter_0 swigDelegate0;

  private static global::System.Type[] swigMethodTypes0 = new global::System.Type[] { typeof(extra.test.TestBooleanResult) };
}
