//------------------------------------------------------------------------------
// <auto-generated />
//
// This file was automatically generated by SWIG (https://www.swig.org).
// Version 4.4.0
//
// Do not make changes to this file unless you know what you are doing - modify
// the SWIG interface file instead.
//------------------------------------------------------------------------------

namespace extra.test {

#nullable enable

public class TestBooleanResult : csp.systems.ResultBase {
  private global::System.Runtime.InteropServices.HandleRef swigCPtr;

  internal TestBooleanResult(global::System.IntPtr cPtr, bool cMemoryOwn) : base(ConnectedSpacesPlatformDotNetPINVOKE.extra_test_TestBooleanResult_SWIGUpcast(cPtr), cMemoryOwn) {
    swigCPtr = new global::System.Runtime.InteropServices.HandleRef(this, cPtr);
  }

  internal static global::System.Runtime.InteropServices.HandleRef getCPtr(TestBooleanResult obj) {
    return (obj == null) ? new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero) : obj.swigCPtr;
  }

  internal static global::System.Runtime.InteropServices.HandleRef swigRelease(TestBooleanResult obj) {
    if (obj != null) {
      if (!obj.swigCMemOwn)
        throw new global::System.ApplicationException("Cannot release ownership as memory is not owned");
      global::System.Runtime.InteropServices.HandleRef ptr = obj.swigCPtr;
      obj.swigCMemOwn = false;
      obj.Dispose();
      return ptr;
    } else {
      return new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero);
    }
  }

  protected override void Dispose(bool disposing) {
    lock(this) {
      if (swigCPtr.Handle != global::System.IntPtr.Zero) {
        if (swigCMemOwn) {
          swigCMemOwn = false;
          ConnectedSpacesPlatformDotNetPINVOKE.delete_extra_test_TestBooleanResult(swigCPtr);
        }
        swigCPtr = new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero);
      }
      base.Dispose(disposing);
    }
  }

  public TestBooleanResult(csp.systems.EResultCode ResCode, ushort HttpResCode) : this(ConnectedSpacesPlatformDotNetPINVOKE.new_extra_test_TestBooleanResult__SWIG_0((int)ResCode, HttpResCode), true) {
    if (ConnectedSpacesPlatformDotNetPINVOKE.SWIGPendingException.Pending) throw ConnectedSpacesPlatformDotNetPINVOKE.SWIGPendingException.Retrieve();
  }

  public TestBooleanResult(csp.systems.EResultCode ResCode, ushort HttpResCode, csp.systems.ERequestFailureReason Reason) : this(ConnectedSpacesPlatformDotNetPINVOKE.new_extra_test_TestBooleanResult__SWIG_1((int)ResCode, HttpResCode, (int)Reason), true) {
    if (ConnectedSpacesPlatformDotNetPINVOKE.SWIGPendingException.Pending) throw ConnectedSpacesPlatformDotNetPINVOKE.SWIGPendingException.Retrieve();
  }

  public void SetRequestProgress(float ProgressPercentage) {
    ConnectedSpacesPlatformDotNetPINVOKE.extra_test_TestBooleanResult_SetRequestProgress(swigCPtr, ProgressPercentage);
    if (ConnectedSpacesPlatformDotNetPINVOKE.SWIGPendingException.Pending) throw ConnectedSpacesPlatformDotNetPINVOKE.SWIGPendingException.Retrieve();
  }

  public void SetResult(csp.systems.EResultCode ResCode, ushort HttpResCode) {
    ConnectedSpacesPlatformDotNetPINVOKE.extra_test_TestBooleanResult_SetResult(swigCPtr, (int)ResCode, HttpResCode);
    if (ConnectedSpacesPlatformDotNetPINVOKE.SWIGPendingException.Pending) throw ConnectedSpacesPlatformDotNetPINVOKE.SWIGPendingException.Retrieve();
  }

  public void SetValue(bool InValue) {
    ConnectedSpacesPlatformDotNetPINVOKE.extra_test_TestBooleanResult_SetValue(swigCPtr, InValue);
    if (ConnectedSpacesPlatformDotNetPINVOKE.SWIGPendingException.Pending) throw ConnectedSpacesPlatformDotNetPINVOKE.SWIGPendingException.Retrieve();
  }

  public bool GetValue() {
    bool ret = ConnectedSpacesPlatformDotNetPINVOKE.extra_test_TestBooleanResult_GetValue(swigCPtr);
    if (ConnectedSpacesPlatformDotNetPINVOKE.SWIGPendingException.Pending) throw ConnectedSpacesPlatformDotNetPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

}

}
