//------------------------------------------------------------------------------
// <auto-generated />
//
// This file was automatically generated by SWIG (https://www.swig.org).
// Version 4.4.0
//
// Do not make changes to this file unless you know what you are doing - modify
// the SWIG interface file instead.
//------------------------------------------------------------------------------

namespace csp.systems {

#nullable enable

public class AlphaVideoMaterial : csp.systems.Material {
  private global::System.Runtime.InteropServices.HandleRef swigCPtr;

  internal AlphaVideoMaterial(global::System.IntPtr cPtr, bool cMemoryOwn) : base(ConnectedSpacesPlatformDotNetPINVOKE.csp_systems_AlphaVideoMaterial_SWIGUpcast(cPtr), cMemoryOwn) {
    swigCPtr = new global::System.Runtime.InteropServices.HandleRef(this, cPtr);
  }

  internal static global::System.Runtime.InteropServices.HandleRef getCPtr(AlphaVideoMaterial obj) {
    return (obj == null) ? new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero) : obj.swigCPtr;
  }

  internal static global::System.Runtime.InteropServices.HandleRef swigRelease(AlphaVideoMaterial obj) {
    if (obj != null) {
      if (!obj.swigCMemOwn)
        throw new global::System.ApplicationException("Cannot release ownership as memory is not owned");
      global::System.Runtime.InteropServices.HandleRef ptr = obj.swigCPtr;
      obj.swigCMemOwn = false;
      obj.Dispose();
      return ptr;
    } else {
      return new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero);
    }
  }

  protected override void Dispose(bool disposing) {
    lock(this) {
      if (swigCPtr.Handle != global::System.IntPtr.Zero) {
        if (swigCMemOwn) {
          swigCMemOwn = false;
          ConnectedSpacesPlatformDotNetPINVOKE.delete_csp_systems_AlphaVideoMaterial(swigCPtr);
        }
        swigCPtr = new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero);
      }
      base.Dispose(disposing);
    }
  }


  // Returns null on failure.
  public static csp.systems.AlphaVideoMaterial? TryFromBaseCast(csp.systems.Material baseObj)
  {
    return NativeFromBaseCast(baseObj);
  }

  // Throws ArgumentException on failure.
  public static csp.systems.AlphaVideoMaterial FromBaseCast(csp.systems.Material baseObj)
  {
    csp.systems.AlphaVideoMaterial? derived = TryFromBaseCast(baseObj);
    if (derived == null){
      throw new System.ArgumentException("Failed to cast " + nameof(csp.systems.Material) + " to " + nameof(csp.systems.AlphaVideoMaterial), "baseObj");
    }
    return derived;
  }


  public void SetColorTexture(csp.systems.TextureInfo Texture) {
    ConnectedSpacesPlatformDotNetPINVOKE.csp_systems_AlphaVideoMaterial_SetColorTexture(swigCPtr, csp.systems.TextureInfo.getCPtr(Texture));
    if (ConnectedSpacesPlatformDotNetPINVOKE.SWIGPendingException.Pending) throw ConnectedSpacesPlatformDotNetPINVOKE.SWIGPendingException.Retrieve();
  }

  public csp.systems.TextureInfo GetColorTexture() {
  global::System.IntPtr cPtr = ConnectedSpacesPlatformDotNetPINVOKE.csp_systems_AlphaVideoMaterial_GetColorTexture(swigCPtr);
    if (ConnectedSpacesPlatformDotNetPINVOKE.SWIGPendingException.Pending) throw ConnectedSpacesPlatformDotNetPINVOKE.SWIGPendingException.Retrieve();
  csp.systems.TextureInfo ret = null;
  if (cPtr != global::System.IntPtr.Zero) {
    ret = new csp.systems.TextureInfo(cPtr, false);
    ret.OuterObjectPin = this;
  }
  return ret;
}

  public void SetDoubleSided(bool DoubleSided) {
    ConnectedSpacesPlatformDotNetPINVOKE.csp_systems_AlphaVideoMaterial_SetDoubleSided(swigCPtr, DoubleSided);
    if (ConnectedSpacesPlatformDotNetPINVOKE.SWIGPendingException.Pending) throw ConnectedSpacesPlatformDotNetPINVOKE.SWIGPendingException.Retrieve();
  }

  public bool GetDoubleSided() {
    bool ret = ConnectedSpacesPlatformDotNetPINVOKE.csp_systems_AlphaVideoMaterial_GetDoubleSided(swigCPtr);
    if (ConnectedSpacesPlatformDotNetPINVOKE.SWIGPendingException.Pending) throw ConnectedSpacesPlatformDotNetPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public void SetIsEmissive(bool IsEmissive) {
    ConnectedSpacesPlatformDotNetPINVOKE.csp_systems_AlphaVideoMaterial_SetIsEmissive(swigCPtr, IsEmissive);
    if (ConnectedSpacesPlatformDotNetPINVOKE.SWIGPendingException.Pending) throw ConnectedSpacesPlatformDotNetPINVOKE.SWIGPendingException.Retrieve();
  }

  public bool GetIsEmissive() {
    bool ret = ConnectedSpacesPlatformDotNetPINVOKE.csp_systems_AlphaVideoMaterial_GetIsEmissive(swigCPtr);
    if (ConnectedSpacesPlatformDotNetPINVOKE.SWIGPendingException.Pending) throw ConnectedSpacesPlatformDotNetPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public void SetReadAlphaFromChannel(csp.systems.EColorChannel ColorChannel) {
    ConnectedSpacesPlatformDotNetPINVOKE.csp_systems_AlphaVideoMaterial_SetReadAlphaFromChannel(swigCPtr, (int)ColorChannel);
    if (ConnectedSpacesPlatformDotNetPINVOKE.SWIGPendingException.Pending) throw ConnectedSpacesPlatformDotNetPINVOKE.SWIGPendingException.Retrieve();
  }

  public csp.systems.EColorChannel GetReadAlphaFromChannel() {
    csp.systems.EColorChannel ret = (csp.systems.EColorChannel)ConnectedSpacesPlatformDotNetPINVOKE.csp_systems_AlphaVideoMaterial_GetReadAlphaFromChannel(swigCPtr);
    if (ConnectedSpacesPlatformDotNetPINVOKE.SWIGPendingException.Pending) throw ConnectedSpacesPlatformDotNetPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public void SetBlendMode(csp.systems.EBlendMode Mode) {
    ConnectedSpacesPlatformDotNetPINVOKE.csp_systems_AlphaVideoMaterial_SetBlendMode(swigCPtr, (int)Mode);
    if (ConnectedSpacesPlatformDotNetPINVOKE.SWIGPendingException.Pending) throw ConnectedSpacesPlatformDotNetPINVOKE.SWIGPendingException.Retrieve();
  }

  public csp.systems.EBlendMode GetBlendMode() {
    csp.systems.EBlendMode ret = (csp.systems.EBlendMode)ConnectedSpacesPlatformDotNetPINVOKE.csp_systems_AlphaVideoMaterial_GetBlendMode(swigCPtr);
    if (ConnectedSpacesPlatformDotNetPINVOKE.SWIGPendingException.Pending) throw ConnectedSpacesPlatformDotNetPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public void SetFresnelFactor(float Factor) {
    ConnectedSpacesPlatformDotNetPINVOKE.csp_systems_AlphaVideoMaterial_SetFresnelFactor(swigCPtr, Factor);
    if (ConnectedSpacesPlatformDotNetPINVOKE.SWIGPendingException.Pending) throw ConnectedSpacesPlatformDotNetPINVOKE.SWIGPendingException.Retrieve();
  }

  public float GetFresnelFactor() {
    float ret = ConnectedSpacesPlatformDotNetPINVOKE.csp_systems_AlphaVideoMaterial_GetFresnelFactor(swigCPtr);
    if (ConnectedSpacesPlatformDotNetPINVOKE.SWIGPendingException.Pending) throw ConnectedSpacesPlatformDotNetPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public void SetTint(csp.common.Vector3 Tint) {
    ConnectedSpacesPlatformDotNetPINVOKE.csp_systems_AlphaVideoMaterial_SetTint(swigCPtr, csp.common.Vector3.getCPtr(Tint));
    if (ConnectedSpacesPlatformDotNetPINVOKE.SWIGPendingException.Pending) throw ConnectedSpacesPlatformDotNetPINVOKE.SWIGPendingException.Retrieve();
  }

  public csp.common.Vector3 GetTint() {
  global::System.IntPtr cPtr = ConnectedSpacesPlatformDotNetPINVOKE.csp_systems_AlphaVideoMaterial_GetTint(swigCPtr);
    if (ConnectedSpacesPlatformDotNetPINVOKE.SWIGPendingException.Pending) throw ConnectedSpacesPlatformDotNetPINVOKE.SWIGPendingException.Retrieve();
  csp.common.Vector3 ret = null;
  if (cPtr != global::System.IntPtr.Zero) {
    ret = new csp.common.Vector3(cPtr, false);
    ret.OuterObjectPin = this;
  }
  return ret;
}

  public void SetAlphaFactor(float Factor) {
    ConnectedSpacesPlatformDotNetPINVOKE.csp_systems_AlphaVideoMaterial_SetAlphaFactor(swigCPtr, Factor);
    if (ConnectedSpacesPlatformDotNetPINVOKE.SWIGPendingException.Pending) throw ConnectedSpacesPlatformDotNetPINVOKE.SWIGPendingException.Retrieve();
  }

  public float GetAlphaFactor() {
    float ret = ConnectedSpacesPlatformDotNetPINVOKE.csp_systems_AlphaVideoMaterial_GetAlphaFactor(swigCPtr);
    if (ConnectedSpacesPlatformDotNetPINVOKE.SWIGPendingException.Pending) throw ConnectedSpacesPlatformDotNetPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public void SetEmissiveIntensity(float Intensity) {
    ConnectedSpacesPlatformDotNetPINVOKE.csp_systems_AlphaVideoMaterial_SetEmissiveIntensity(swigCPtr, Intensity);
    if (ConnectedSpacesPlatformDotNetPINVOKE.SWIGPendingException.Pending) throw ConnectedSpacesPlatformDotNetPINVOKE.SWIGPendingException.Retrieve();
  }

  public float GetEmissiveIntensity() {
    float ret = ConnectedSpacesPlatformDotNetPINVOKE.csp_systems_AlphaVideoMaterial_GetEmissiveIntensity(swigCPtr);
    if (ConnectedSpacesPlatformDotNetPINVOKE.SWIGPendingException.Pending) throw ConnectedSpacesPlatformDotNetPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public void SetAlphaMask(float Mask) {
    ConnectedSpacesPlatformDotNetPINVOKE.csp_systems_AlphaVideoMaterial_SetAlphaMask(swigCPtr, Mask);
    if (ConnectedSpacesPlatformDotNetPINVOKE.SWIGPendingException.Pending) throw ConnectedSpacesPlatformDotNetPINVOKE.SWIGPendingException.Retrieve();
  }

  public float GetAlphaMask() {
    float ret = ConnectedSpacesPlatformDotNetPINVOKE.csp_systems_AlphaVideoMaterial_GetAlphaMask(swigCPtr);
    if (ConnectedSpacesPlatformDotNetPINVOKE.SWIGPendingException.Pending) throw ConnectedSpacesPlatformDotNetPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public AlphaVideoMaterial(string Name, string MaterialCollectionId, string MaterialId) : this(ConnectedSpacesPlatformDotNetPINVOKE.new_csp_systems_AlphaVideoMaterial__SWIG_0(Name, MaterialCollectionId, MaterialId), true) {
    if (ConnectedSpacesPlatformDotNetPINVOKE.SWIGPendingException.Pending) throw ConnectedSpacesPlatformDotNetPINVOKE.SWIGPendingException.Retrieve();
  }

  public AlphaVideoMaterial() : this(ConnectedSpacesPlatformDotNetPINVOKE.new_csp_systems_AlphaVideoMaterial__SWIG_1(), true) {
    if (ConnectedSpacesPlatformDotNetPINVOKE.SWIGPendingException.Pending) throw ConnectedSpacesPlatformDotNetPINVOKE.SWIGPendingException.Retrieve();
  }

  // Any time this object is returned from an outer C++ object via reference, this is set
  // to prevent premature garbage collection causing premature C++ memory deallocation.
  public object OuterObjectPin { private get; set; }

  internal static csp.systems.AlphaVideoMaterial NativeFromBaseCast(csp.systems.Material baseObj) {
    global::System.IntPtr cPtr = ConnectedSpacesPlatformDotNetPINVOKE.csp_systems_AlphaVideoMaterial_NativeFromBaseCast((baseObj != null && csp.systems.Material.getCPtr(baseObj).Handle == global::System.IntPtr.Zero) ? throw new global::System.ObjectDisposedException("baseObj", "Passed a disposed C# SWIG wrapper (null native handle) to C++. This indicates an object lifecycle bug needing investigation. Note: This does not detect C++-side deletions.") : csp.systems.Material.getCPtr(baseObj));
    csp.systems.AlphaVideoMaterial ret = (cPtr == global::System.IntPtr.Zero) ? null : new csp.systems.AlphaVideoMaterial(cPtr, false);
    if (ConnectedSpacesPlatformDotNetPINVOKE.SWIGPendingException.Pending) throw ConnectedSpacesPlatformDotNetPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

}

}
