//------------------------------------------------------------------------------
// <auto-generated />
//
// This file was automatically generated by SWIG (https://www.swig.org).
// Version 4.4.0
//
// Do not make changes to this file unless you know what you are doing - modify
// the SWIG interface file instead.
//------------------------------------------------------------------------------

namespace csp.systems {

#nullable enable

public class AnalyticsSystem : csp.systems.SystemBase {
  private global::System.Runtime.InteropServices.HandleRef swigCPtr;

  internal AnalyticsSystem(global::System.IntPtr cPtr, bool cMemoryOwn) : base(ConnectedSpacesPlatformDotNetPINVOKE.csp_systems_AnalyticsSystem_SWIGUpcast(cPtr), cMemoryOwn) {
    swigCPtr = new global::System.Runtime.InteropServices.HandleRef(this, cPtr);
  }

  internal static global::System.Runtime.InteropServices.HandleRef getCPtr(AnalyticsSystem obj) {
    return (obj == null) ? new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero) : obj.swigCPtr;
  }

  internal static global::System.Runtime.InteropServices.HandleRef swigRelease(AnalyticsSystem obj) {
    if (obj != null) {
      if (!obj.swigCMemOwn)
        throw new global::System.ApplicationException("Cannot release ownership as memory is not owned");
      global::System.Runtime.InteropServices.HandleRef ptr = obj.swigCPtr;
      obj.swigCMemOwn = false;
      obj.Dispose();
      return ptr;
    } else {
      return new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero);
    }
  }

  protected override void Dispose(bool disposing) {
    lock(this) {
      if (swigCPtr.Handle != global::System.IntPtr.Zero) {
        if (swigCMemOwn) {
          swigCMemOwn = false;
          throw new global::System.MethodAccessException("C++ destructor does not have public access");
        }
        swigCPtr = new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero);
      }
      base.Dispose(disposing);
    }
  }

  public void QueueAnalyticsEvent(string ProductContextSection, string Category, string InteractionType, string SubCategory, csp.common.StringDict Metadata) {
    ConnectedSpacesPlatformDotNetPINVOKE.csp_systems_AnalyticsSystem_QueueAnalyticsEvent(swigCPtr, ProductContextSection, Category, InteractionType, SubCategory, csp.common.StringDict.getCPtr(Metadata));
    if (ConnectedSpacesPlatformDotNetPINVOKE.SWIGPendingException.Pending) throw ConnectedSpacesPlatformDotNetPINVOKE.SWIGPendingException.Retrieve();
  }

  public void SendAnalyticsEvent(string ProductContextSection, string Category, string InteractionType, string SubCategory, csp.common.StringDict Metadata, NullResultCallbackAdapter Callback) {
    ConnectedSpacesPlatformDotNetPINVOKE.csp_systems_AnalyticsSystem_SendAnalyticsEvent(swigCPtr, ProductContextSection, Category, InteractionType, SubCategory, csp.common.StringDict.getCPtr(Metadata), NullResultCallbackAdapter.getCPtr(Callback));
    if (ConnectedSpacesPlatformDotNetPINVOKE.SWIGPendingException.Pending) throw ConnectedSpacesPlatformDotNetPINVOKE.SWIGPendingException.Retrieve();
  }

  public void FlushAnalyticsEventsQueue(NullResultCallbackAdapter Callback) {
    ConnectedSpacesPlatformDotNetPINVOKE.csp_systems_AnalyticsSystem_FlushAnalyticsEventsQueue(swigCPtr, NullResultCallbackAdapter.getCPtr(Callback));
    if (ConnectedSpacesPlatformDotNetPINVOKE.SWIGPendingException.Pending) throw ConnectedSpacesPlatformDotNetPINVOKE.SWIGPendingException.Retrieve();
  }


  public System.Threading.Tasks.Task<csp.systems.NullResult> SendAnalyticsEventAsync(string productContextSection,string category,string interactionType,string? subCategory,csp.common.StringDict? metadata, System.Action<float>? progressCallback = null)
  {
    // Create a TaskCompletionSource to represent the async operation.
    System.Threading.Tasks.TaskCompletionSource<csp.systems.NullResult> tcs = 
        new System.Threading.Tasks.TaskCompletionSource<csp.systems.NullResult>(System.Threading.Tasks.TaskCreationOptions.RunContinuationsAsynchronously);

    /*@SWIG:/Users/runner/work/connected-spaces-platform-unity/connected-spaces-platform-unity/interface/swigutils/AsyncAdapters.i,129,MAKE_ROOTED_ASYNC_CALLBACK_BODY@*/
    ConnectedSpacesPlatformDotNet.NullResultCallback callback =
        new ConnectedSpacesPlatformDotNet.NullResultCallback();

    // Define the callback that will be called by the C++ code
    System.Action<csp.systems.NullResult>? handler = null;
    handler = new ((csp.systems.NullResult result) =>
    {
        try
        {
           /* This is a bit jank. Due to the desire to use passthrough macros between async
            * and actions, we have this result param which yes, can be
            * a comma separated list for action style callbacks, but in async (awaitable) functions,
            * it's only ever a single name.
            * It ISNT always a ResultBase type (although that would simplify things if CSP would do that...)
            * Sometime's it's just a space entity, or a bool, or something else. */

            if((object)result is csp.systems.ResultBase _result)
            {
                // It's a result base

                // Convert the failing result to a throw if we have that option enabled
                _result.ThrowOnFailure(nameof(SendAnalyticsEventAsync));


                // Use _result here because we need to call ResultBase api, but we still pass the fully specified type in the TrySetResult
                // Remember that callbacks also have `init` and `inProgress` status's. We will often receive this callback more than once,
                // only finish when we get a final status.  
                if (_result.GetResultCode() == csp.systems.EResultCode.Success ||
                    _result.GetResultCode() == csp.systems.EResultCode.Failed)
                {
                    tcs.TrySetResult(result);
                    // Now that the callback has been invoked and returned success or failure, we no longer need to
                    // await, so we unsubscribe, which should empty the invocation list and unroot the reference for GC. 
                    // Instead, if the result was still pending we would have still needed to await and keep this alive.
                    callback.Invoked -= handler;
                }
                else if (_result.GetResultCode() == csp.systems.EResultCode.InProgress)
                {
                    // Trigger the injected progress callback.
                    progressCallback?.Invoke(_result.GetRequestProgress());
                }
            }
            else
            {
                // It's something else
                tcs.TrySetResult(result);
                // Now that the callback has been invoked, we unsubscribe, so that if there is no other subscriber
                // the callback gets automatically unrooted. We do this because we do not expect
                // any more callbacks to come since this is not a ResultBase with pending status. This will
                // trigger the GC of the callback safely, since we no longer await for it.
                callback.Invoked -= handler;
            }
        }
        catch (System.Exception ex)
        {
            // If any other exception occurs, we set it on the task completion source. Failsafe.
            tcs.TrySetException(ex);

            // Ensure the callback is safely unregistered and unpinned from the global 
            // GCHandle registry if a validation exception interrupts the execution flow
            callback.Invoked -= handler;
        }
    });

    // Subscribe to the callback. 
    // Note that this will automatically root the callback since it has at least one subscriber.
    callback.Invoked += handler;

/*@SWIG@*/;

    // Run the method with the provided arguments and the callback
    // callback is defined in MAKE_AWAITABLE_CALLBACK_BODY
    SendAnalyticsEvent(productContextSection,category,interactionType,subCategory,metadata, callback);

    return tcs.Task;
  }

  public System.Threading.Tasks.Task<csp.systems.NullResult> FlushAnalyticsEventsQueueAsync(System.Action<float>? progressCallback = null)
  {  
    // Create a TaskCompletionSource to represent the async operation.
    System.Threading.Tasks.TaskCompletionSource<csp.systems.NullResult> tcs = 
        new System.Threading.Tasks.TaskCompletionSource<csp.systems.NullResult>(System.Threading.Tasks.TaskCreationOptions.RunContinuationsAsynchronously);

    /*@SWIG:/Users/runner/work/connected-spaces-platform-unity/connected-spaces-platform-unity/interface/swigutils/AsyncAdapters.i,129,MAKE_ROOTED_ASYNC_CALLBACK_BODY@*/
    ConnectedSpacesPlatformDotNet.NullResultCallback callback =
        new ConnectedSpacesPlatformDotNet.NullResultCallback();

    // Define the callback that will be called by the C++ code
    System.Action<csp.systems.NullResult>? handler = null;
    handler = new ((csp.systems.NullResult result) =>
    {
        try
        {
           /* This is a bit jank. Due to the desire to use passthrough macros between async
            * and actions, we have this result param which yes, can be
            * a comma separated list for action style callbacks, but in async (awaitable) functions,
            * it's only ever a single name.
            * It ISNT always a ResultBase type (although that would simplify things if CSP would do that...)
            * Sometime's it's just a space entity, or a bool, or something else. */

            if((object)result is csp.systems.ResultBase _result)
            {
                // It's a result base

                // Convert the failing result to a throw if we have that option enabled
                _result.ThrowOnFailure(nameof(FlushAnalyticsEventsQueueAsync));


                // Use _result here because we need to call ResultBase api, but we still pass the fully specified type in the TrySetResult
                // Remember that callbacks also have `init` and `inProgress` status's. We will often receive this callback more than once,
                // only finish when we get a final status.  
                if (_result.GetResultCode() == csp.systems.EResultCode.Success ||
                    _result.GetResultCode() == csp.systems.EResultCode.Failed)
                {
                    tcs.TrySetResult(result);
                    // Now that the callback has been invoked and returned success or failure, we no longer need to
                    // await, so we unsubscribe, which should empty the invocation list and unroot the reference for GC. 
                    // Instead, if the result was still pending we would have still needed to await and keep this alive.
                    callback.Invoked -= handler;
                }
                else if (_result.GetResultCode() == csp.systems.EResultCode.InProgress)
                {
                    // Trigger the injected progress callback.
                    progressCallback?.Invoke(_result.GetRequestProgress());
                }
            }
            else
            {
                // It's something else
                tcs.TrySetResult(result);
                // Now that the callback has been invoked, we unsubscribe, so that if there is no other subscriber
                // the callback gets automatically unrooted. We do this because we do not expect
                // any more callbacks to come since this is not a ResultBase with pending status. This will
                // trigger the GC of the callback safely, since we no longer await for it.
                callback.Invoked -= handler;
            }
        }
        catch (System.Exception ex)
        {
            // If any other exception occurs, we set it on the task completion source. Failsafe.
            tcs.TrySetException(ex);

            // Ensure the callback is safely unregistered and unpinned from the global 
            // GCHandle registry if a validation exception interrupts the execution flow
            callback.Invoked -= handler;
        }
    });

    // Subscribe to the callback. 
    // Note that this will automatically root the callback since it has at least one subscriber.
    callback.Invoked += handler;

/*@SWIG@*/;

    // Run the method with the provided arguments and the callback
    FlushAnalyticsEventsQueue(callback);

    return tcs.Task;

  }

  // Any time this object is returned from an outer C++ object via reference, this is set
  // to prevent premature garbage collection causing premature C++ memory deallocation.
  public object OuterObjectPin { private get; set; }

}

}
