//------------------------------------------------------------------------------
// <auto-generated />
//
// This file was automatically generated by SWIG (https://www.swig.org).
// Version 4.4.0
//
// Do not make changes to this file unless you know what you are doing - modify
// the SWIG interface file instead.
//------------------------------------------------------------------------------

namespace csp.systems {

#nullable enable

public class AnchorSystem : csp.systems.SystemBase {
  private global::System.Runtime.InteropServices.HandleRef swigCPtr;

  internal AnchorSystem(global::System.IntPtr cPtr, bool cMemoryOwn) : base(ConnectedSpacesPlatformDotNetPINVOKE.csp_systems_AnchorSystem_SWIGUpcast(cPtr), cMemoryOwn) {
    swigCPtr = new global::System.Runtime.InteropServices.HandleRef(this, cPtr);
  }

  internal static global::System.Runtime.InteropServices.HandleRef getCPtr(AnchorSystem obj) {
    return (obj == null) ? new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero) : obj.swigCPtr;
  }

  internal static global::System.Runtime.InteropServices.HandleRef swigRelease(AnchorSystem obj) {
    if (obj != null) {
      if (!obj.swigCMemOwn)
        throw new global::System.ApplicationException("Cannot release ownership as memory is not owned");
      global::System.Runtime.InteropServices.HandleRef ptr = obj.swigCPtr;
      obj.swigCMemOwn = false;
      obj.Dispose();
      return ptr;
    } else {
      return new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero);
    }
  }

  protected override void Dispose(bool disposing) {
    lock(this) {
      if (swigCPtr.Handle != global::System.IntPtr.Zero) {
        if (swigCMemOwn) {
          swigCMemOwn = false;
          throw new global::System.MethodAccessException("C++ destructor does not have public access");
        }
        swigCPtr = new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero);
      }
      base.Dispose(disposing);
    }
  }

  public void CreateAnchor(csp.systems.AnchorProvider ThirdPartyAnchorProvider, string ThirdPartyAnchorId, string AssetCollectionId, csp.systems.GeoLocation Location, csp.systems.OlyAnchorPosition Position, csp.systems.OlyRotation Rotation, csp.common.StringDict SpatialKeyValue, csp.common.StringArray Tags, AnchorResultCallbackAdapter Callback) {
    ConnectedSpacesPlatformDotNetPINVOKE.csp_systems_AnchorSystem_CreateAnchor(swigCPtr, (int)ThirdPartyAnchorProvider, ThirdPartyAnchorId, AssetCollectionId, csp.systems.GeoLocation.getCPtr(Location), csp.systems.OlyAnchorPosition.getCPtr(Position), csp.systems.OlyRotation.getCPtr(Rotation), csp.common.StringDict.getCPtr(SpatialKeyValue), csp.common.StringArray.getCPtr(Tags), AnchorResultCallbackAdapter.getCPtr(Callback));
    if (ConnectedSpacesPlatformDotNetPINVOKE.SWIGPendingException.Pending) throw ConnectedSpacesPlatformDotNetPINVOKE.SWIGPendingException.Retrieve();
  }

  public void CreateAnchorInSpace(csp.systems.AnchorProvider ThirdPartyAnchorProvider, string ThirdPartyAnchorId, string SpaceId, ulong SpaceEntityId, string AssetCollectionId, csp.systems.GeoLocation Location, csp.systems.OlyAnchorPosition Position, csp.systems.OlyRotation Rotation, csp.common.StringDict SpatialKeyValue, csp.common.StringArray Tags, AnchorResultCallbackAdapter Callback) {
    ConnectedSpacesPlatformDotNetPINVOKE.csp_systems_AnchorSystem_CreateAnchorInSpace(swigCPtr, (int)ThirdPartyAnchorProvider, ThirdPartyAnchorId, SpaceId, SpaceEntityId, AssetCollectionId, csp.systems.GeoLocation.getCPtr(Location), csp.systems.OlyAnchorPosition.getCPtr(Position), csp.systems.OlyRotation.getCPtr(Rotation), csp.common.StringDict.getCPtr(SpatialKeyValue), csp.common.StringArray.getCPtr(Tags), AnchorResultCallbackAdapter.getCPtr(Callback));
    if (ConnectedSpacesPlatformDotNetPINVOKE.SWIGPendingException.Pending) throw ConnectedSpacesPlatformDotNetPINVOKE.SWIGPendingException.Retrieve();
  }

  public void DeleteAnchors(csp.common.StringArray AnchorIds, NullResultCallbackAdapter Callback) {
    ConnectedSpacesPlatformDotNetPINVOKE.csp_systems_AnchorSystem_DeleteAnchors(swigCPtr, csp.common.StringArray.getCPtr(AnchorIds), NullResultCallbackAdapter.getCPtr(Callback));
    if (ConnectedSpacesPlatformDotNetPINVOKE.SWIGPendingException.Pending) throw ConnectedSpacesPlatformDotNetPINVOKE.SWIGPendingException.Retrieve();
  }

  public void GetAnchorsInArea(csp.systems.GeoLocation OriginLocation, double AreaRadius, csp.common.StringArray SpatialKeys, csp.common.StringArray SpatialValues, csp.common.StringArray Tags, bool? AllTags, csp.common.StringArray SpaceIds, int? Skip, int? Limit, AnchorCollectionResultCallbackAdapter Callback) {
    csp.common.OptBool opt_AllTags = AllTags.HasValue ? new csp.common.OptBool(AllTags.Value) : new csp.common.OptBool();
    csp.common.OptSignedInt32 opt_Skip = Skip.HasValue ? new csp.common.OptSignedInt32(Skip.Value) : new csp.common.OptSignedInt32();
    csp.common.OptSignedInt32 opt_Limit = Limit.HasValue ? new csp.common.OptSignedInt32(Limit.Value) : new csp.common.OptSignedInt32();
    {
      ConnectedSpacesPlatformDotNetPINVOKE.csp_systems_AnchorSystem_GetAnchorsInArea(swigCPtr, csp.systems.GeoLocation.getCPtr(OriginLocation), AreaRadius, csp.common.StringArray.getCPtr(SpatialKeys), csp.common.StringArray.getCPtr(SpatialValues), csp.common.StringArray.getCPtr(Tags), csp.common.OptBool.getCPtr(opt_AllTags), csp.common.StringArray.getCPtr(SpaceIds), csp.common.OptSignedInt32.getCPtr(opt_Skip), csp.common.OptSignedInt32.getCPtr(opt_Limit), AnchorCollectionResultCallbackAdapter.getCPtr(Callback));
      if (ConnectedSpacesPlatformDotNetPINVOKE.SWIGPendingException.Pending) throw ConnectedSpacesPlatformDotNetPINVOKE.SWIGPendingException.Retrieve();
    }
  }

  public void GetAnchorsInSpace(string SpaceId, int? Skip, int? Limit, AnchorCollectionResultCallbackAdapter Callback) {
    csp.common.OptSignedInt32 opt_Skip = Skip.HasValue ? new csp.common.OptSignedInt32(Skip.Value) : new csp.common.OptSignedInt32();
    csp.common.OptSignedInt32 opt_Limit = Limit.HasValue ? new csp.common.OptSignedInt32(Limit.Value) : new csp.common.OptSignedInt32();
    {
      ConnectedSpacesPlatformDotNetPINVOKE.csp_systems_AnchorSystem_GetAnchorsInSpace(swigCPtr, SpaceId, csp.common.OptSignedInt32.getCPtr(opt_Skip), csp.common.OptSignedInt32.getCPtr(opt_Limit), AnchorCollectionResultCallbackAdapter.getCPtr(Callback));
      if (ConnectedSpacesPlatformDotNetPINVOKE.SWIGPendingException.Pending) throw ConnectedSpacesPlatformDotNetPINVOKE.SWIGPendingException.Retrieve();
    }
  }

  public void GetAnchorsByAssetCollectionId(string AssetCollectionId, int? Skip, int? Limit, AnchorCollectionResultCallbackAdapter Callback) {
    csp.common.OptSignedInt32 opt_Skip = Skip.HasValue ? new csp.common.OptSignedInt32(Skip.Value) : new csp.common.OptSignedInt32();
    csp.common.OptSignedInt32 opt_Limit = Limit.HasValue ? new csp.common.OptSignedInt32(Limit.Value) : new csp.common.OptSignedInt32();
    {
      ConnectedSpacesPlatformDotNetPINVOKE.csp_systems_AnchorSystem_GetAnchorsByAssetCollectionId(swigCPtr, AssetCollectionId, csp.common.OptSignedInt32.getCPtr(opt_Skip), csp.common.OptSignedInt32.getCPtr(opt_Limit), AnchorCollectionResultCallbackAdapter.getCPtr(Callback));
      if (ConnectedSpacesPlatformDotNetPINVOKE.SWIGPendingException.Pending) throw ConnectedSpacesPlatformDotNetPINVOKE.SWIGPendingException.Retrieve();
    }
  }

  public void CreateAnchorResolution(string AnchorId, bool SuccessfullyResolved, int ResolveAttempted, double ResolveTime, csp.common.StringArray Tags, AnchorResolutionResultCallbackAdapter Callback) {
    ConnectedSpacesPlatformDotNetPINVOKE.csp_systems_AnchorSystem_CreateAnchorResolution(swigCPtr, AnchorId, SuccessfullyResolved, ResolveAttempted, ResolveTime, csp.common.StringArray.getCPtr(Tags), AnchorResolutionResultCallbackAdapter.getCPtr(Callback));
    if (ConnectedSpacesPlatformDotNetPINVOKE.SWIGPendingException.Pending) throw ConnectedSpacesPlatformDotNetPINVOKE.SWIGPendingException.Retrieve();
  }


  public System.Threading.Tasks.Task<csp.systems.AnchorResult> CreateAnchorAsync(csp.systems.AnchorProvider thirdPartyAnchorProvider,string thirdPartyAnchorId,string assetCollectionId,csp.systems.GeoLocation location,csp.systems.OlyAnchorPosition position,csp.systems.OlyRotation rotation,csp.common.StringDict? spatialKeyValue,csp.common.StringArray? tags)
  {
    // Create a TaskCompletionSource to represent the async operation.
    System.Threading.Tasks.TaskCompletionSource<csp.systems.AnchorResult> tcs = 
        new System.Threading.Tasks.TaskCompletionSource<csp.systems.AnchorResult>(System.Threading.Tasks.TaskCreationOptions.RunContinuationsAsynchronously);

    /*@SWIG:D:\a\connected-spaces-platform-unity\connected-spaces-platform-unity\interface\swigutils\AsyncAdapters.i,129,MAKE_ROOTED_ASYNC_CALLBACK_BODY@*/
    ConnectedSpacesPlatformDotNet.AnchorResultCallback callback =
        new ConnectedSpacesPlatformDotNet.AnchorResultCallback();

    // Define the callback that will be called by the C++ code
    System.Action<csp.systems.AnchorResult>? handler = null;
    handler = new ((csp.systems.AnchorResult result) =>
    {
        try
        {
           /* This is a bit jank. Due to the desire to use passthrough macros between async
            * and actions, we have this result param which yes, can be
            * a comma separated list for action style callbacks, but in async (awaitable) functions,
            * it's only ever a single name.
            * It ISNT always a ResultBase type (although that would simplify things if CSP would do that...)
            * Sometime's it's just a space entity, or a bool, or something else. */

            if((object)result is csp.systems.ResultBase _result)
            {
                // It's a result base

                // Convert the failing result to a throw if we have that option enabled
                _result.ThrowOnFailure(nameof(CreateAnchorAsync));


                // Use _result here because we need to call ResultBase api, but we still pass the fully specified type in the TrySetResult
                // Remember that callbacks also have `init` and `inProgress` status's. We will often receive this callback more than once,
                // only finish when we get a final status.  
                if (_result.GetResultCode() == csp.systems.EResultCode.Success ||
                    _result.GetResultCode() == csp.systems.EResultCode.Failed)
                {
                    tcs.TrySetResult(result);
                    // Now that the callback has been invoked and returned success or failure, we no longer need to
                    // await, so we unsubscribe, which should empty the invocation list and unroot the reference for GC. 
                    // Instead, if the result was still pending we would have still needed to await and keep this alive.
                    callback.Invoked -= handler;
                }
            }
            else
            {
                // It's something else
                tcs.TrySetResult(result);
                // Now that the callback has been invoked, we unsubscribe, so that if there is no other subscriber
                // the callback gets automatically unrooted. We do this because we do not expect
                // any more callbacks to come since this is not a ResultBase with pending status. This will
                // trigger the GC of the callback safely, since we no longer await for it.
                callback.Invoked -= handler;
            }
        }
        catch (System.Exception ex)
        {
            // If any other exception occurs, we set it on the task completion source. Failsafe.
            tcs.TrySetException(ex);
        }
    });

    // Subscribe to the callback. 
    // Note that this will automatically root the callback since it has at least one subscriber.
    callback.Invoked += handler;

/*@SWIG@*/;

    // Run the method with the provided arguments and the callback
    // callback is defined in MAKE_AWAITABLE_CALLBACK_BODY
    CreateAnchor(thirdPartyAnchorProvider,thirdPartyAnchorId,assetCollectionId,location,position,rotation,spatialKeyValue,tags, callback);

    return tcs.Task;
  }


  public System.Threading.Tasks.Task<csp.systems.AnchorResult> CreateAnchorInSpaceAsync(csp.systems.AnchorProvider thirdPartyAnchorProvider,string thirdPartyAnchorId,string spaceId,ulong spaceEntityId,string assetCollectionId,csp.systems.GeoLocation location,csp.systems.OlyAnchorPosition position,csp.systems.OlyRotation rotation,csp.common.StringDict? spatialKeyValue,csp.common.StringArray? tags)
  {
    // Create a TaskCompletionSource to represent the async operation.
    System.Threading.Tasks.TaskCompletionSource<csp.systems.AnchorResult> tcs = 
        new System.Threading.Tasks.TaskCompletionSource<csp.systems.AnchorResult>(System.Threading.Tasks.TaskCreationOptions.RunContinuationsAsynchronously);

    /*@SWIG:D:\a\connected-spaces-platform-unity\connected-spaces-platform-unity\interface\swigutils\AsyncAdapters.i,129,MAKE_ROOTED_ASYNC_CALLBACK_BODY@*/
    ConnectedSpacesPlatformDotNet.AnchorResultCallback callback =
        new ConnectedSpacesPlatformDotNet.AnchorResultCallback();

    // Define the callback that will be called by the C++ code
    System.Action<csp.systems.AnchorResult>? handler = null;
    handler = new ((csp.systems.AnchorResult result) =>
    {
        try
        {
           /* This is a bit jank. Due to the desire to use passthrough macros between async
            * and actions, we have this result param which yes, can be
            * a comma separated list for action style callbacks, but in async (awaitable) functions,
            * it's only ever a single name.
            * It ISNT always a ResultBase type (although that would simplify things if CSP would do that...)
            * Sometime's it's just a space entity, or a bool, or something else. */

            if((object)result is csp.systems.ResultBase _result)
            {
                // It's a result base

                // Convert the failing result to a throw if we have that option enabled
                _result.ThrowOnFailure(nameof(CreateAnchorInSpaceAsync));


                // Use _result here because we need to call ResultBase api, but we still pass the fully specified type in the TrySetResult
                // Remember that callbacks also have `init` and `inProgress` status's. We will often receive this callback more than once,
                // only finish when we get a final status.  
                if (_result.GetResultCode() == csp.systems.EResultCode.Success ||
                    _result.GetResultCode() == csp.systems.EResultCode.Failed)
                {
                    tcs.TrySetResult(result);
                    // Now that the callback has been invoked and returned success or failure, we no longer need to
                    // await, so we unsubscribe, which should empty the invocation list and unroot the reference for GC. 
                    // Instead, if the result was still pending we would have still needed to await and keep this alive.
                    callback.Invoked -= handler;
                }
            }
            else
            {
                // It's something else
                tcs.TrySetResult(result);
                // Now that the callback has been invoked, we unsubscribe, so that if there is no other subscriber
                // the callback gets automatically unrooted. We do this because we do not expect
                // any more callbacks to come since this is not a ResultBase with pending status. This will
                // trigger the GC of the callback safely, since we no longer await for it.
                callback.Invoked -= handler;
            }
        }
        catch (System.Exception ex)
        {
            // If any other exception occurs, we set it on the task completion source. Failsafe.
            tcs.TrySetException(ex);
        }
    });

    // Subscribe to the callback. 
    // Note that this will automatically root the callback since it has at least one subscriber.
    callback.Invoked += handler;

/*@SWIG@*/;

    // Run the method with the provided arguments and the callback
    // callback is defined in MAKE_AWAITABLE_CALLBACK_BODY
    CreateAnchorInSpace(thirdPartyAnchorProvider,thirdPartyAnchorId,spaceId,spaceEntityId,assetCollectionId,location,position,rotation,spatialKeyValue,tags, callback);

    return tcs.Task;
  }


  public System.Threading.Tasks.Task<csp.systems.NullResult> DeleteAnchorsAsync(csp.common.StringArray anchorIds)
  {
    // Create a TaskCompletionSource to represent the async operation.
    System.Threading.Tasks.TaskCompletionSource<csp.systems.NullResult> tcs = 
        new System.Threading.Tasks.TaskCompletionSource<csp.systems.NullResult>(System.Threading.Tasks.TaskCreationOptions.RunContinuationsAsynchronously);

    /*@SWIG:D:\a\connected-spaces-platform-unity\connected-spaces-platform-unity\interface\swigutils\AsyncAdapters.i,129,MAKE_ROOTED_ASYNC_CALLBACK_BODY@*/
    ConnectedSpacesPlatformDotNet.NullResultCallback callback =
        new ConnectedSpacesPlatformDotNet.NullResultCallback();

    // Define the callback that will be called by the C++ code
    System.Action<csp.systems.NullResult>? handler = null;
    handler = new ((csp.systems.NullResult result) =>
    {
        try
        {
           /* This is a bit jank. Due to the desire to use passthrough macros between async
            * and actions, we have this result param which yes, can be
            * a comma separated list for action style callbacks, but in async (awaitable) functions,
            * it's only ever a single name.
            * It ISNT always a ResultBase type (although that would simplify things if CSP would do that...)
            * Sometime's it's just a space entity, or a bool, or something else. */

            if((object)result is csp.systems.ResultBase _result)
            {
                // It's a result base

                // Convert the failing result to a throw if we have that option enabled
                _result.ThrowOnFailure(nameof(DeleteAnchorsAsync));


                // Use _result here because we need to call ResultBase api, but we still pass the fully specified type in the TrySetResult
                // Remember that callbacks also have `init` and `inProgress` status's. We will often receive this callback more than once,
                // only finish when we get a final status.  
                if (_result.GetResultCode() == csp.systems.EResultCode.Success ||
                    _result.GetResultCode() == csp.systems.EResultCode.Failed)
                {
                    tcs.TrySetResult(result);
                    // Now that the callback has been invoked and returned success or failure, we no longer need to
                    // await, so we unsubscribe, which should empty the invocation list and unroot the reference for GC. 
                    // Instead, if the result was still pending we would have still needed to await and keep this alive.
                    callback.Invoked -= handler;
                }
            }
            else
            {
                // It's something else
                tcs.TrySetResult(result);
                // Now that the callback has been invoked, we unsubscribe, so that if there is no other subscriber
                // the callback gets automatically unrooted. We do this because we do not expect
                // any more callbacks to come since this is not a ResultBase with pending status. This will
                // trigger the GC of the callback safely, since we no longer await for it.
                callback.Invoked -= handler;
            }
        }
        catch (System.Exception ex)
        {
            // If any other exception occurs, we set it on the task completion source. Failsafe.
            tcs.TrySetException(ex);
        }
    });

    // Subscribe to the callback. 
    // Note that this will automatically root the callback since it has at least one subscriber.
    callback.Invoked += handler;

/*@SWIG@*/;

    // Run the method with the provided arguments and the callback
    // callback is defined in MAKE_AWAITABLE_CALLBACK_BODY
    DeleteAnchors(anchorIds, callback);

    return tcs.Task;
  }


  public System.Threading.Tasks.Task<csp.systems.AnchorCollectionResult> GetAnchorsInAreaAsync(csp.systems.GeoLocation originLocation,double areaRadius,csp.common.StringArray? spatialKeys,csp.common.StringArray? spatialValues,csp.common.StringArray? tags,bool? allTags,csp.common.StringArray? spaceIds,int? skip,int? limit)
  {
    // Create a TaskCompletionSource to represent the async operation.
    System.Threading.Tasks.TaskCompletionSource<csp.systems.AnchorCollectionResult> tcs = 
        new System.Threading.Tasks.TaskCompletionSource<csp.systems.AnchorCollectionResult>(System.Threading.Tasks.TaskCreationOptions.RunContinuationsAsynchronously);

    /*@SWIG:D:\a\connected-spaces-platform-unity\connected-spaces-platform-unity\interface\swigutils\AsyncAdapters.i,129,MAKE_ROOTED_ASYNC_CALLBACK_BODY@*/
    ConnectedSpacesPlatformDotNet.AnchorCollectionResultCallback callback =
        new ConnectedSpacesPlatformDotNet.AnchorCollectionResultCallback();

    // Define the callback that will be called by the C++ code
    System.Action<csp.systems.AnchorCollectionResult>? handler = null;
    handler = new ((csp.systems.AnchorCollectionResult result) =>
    {
        try
        {
           /* This is a bit jank. Due to the desire to use passthrough macros between async
            * and actions, we have this result param which yes, can be
            * a comma separated list for action style callbacks, but in async (awaitable) functions,
            * it's only ever a single name.
            * It ISNT always a ResultBase type (although that would simplify things if CSP would do that...)
            * Sometime's it's just a space entity, or a bool, or something else. */

            if((object)result is csp.systems.ResultBase _result)
            {
                // It's a result base

                // Convert the failing result to a throw if we have that option enabled
                _result.ThrowOnFailure(nameof(GetAnchorsInAreaAsync));


                // Use _result here because we need to call ResultBase api, but we still pass the fully specified type in the TrySetResult
                // Remember that callbacks also have `init` and `inProgress` status's. We will often receive this callback more than once,
                // only finish when we get a final status.  
                if (_result.GetResultCode() == csp.systems.EResultCode.Success ||
                    _result.GetResultCode() == csp.systems.EResultCode.Failed)
                {
                    tcs.TrySetResult(result);
                    // Now that the callback has been invoked and returned success or failure, we no longer need to
                    // await, so we unsubscribe, which should empty the invocation list and unroot the reference for GC. 
                    // Instead, if the result was still pending we would have still needed to await and keep this alive.
                    callback.Invoked -= handler;
                }
            }
            else
            {
                // It's something else
                tcs.TrySetResult(result);
                // Now that the callback has been invoked, we unsubscribe, so that if there is no other subscriber
                // the callback gets automatically unrooted. We do this because we do not expect
                // any more callbacks to come since this is not a ResultBase with pending status. This will
                // trigger the GC of the callback safely, since we no longer await for it.
                callback.Invoked -= handler;
            }
        }
        catch (System.Exception ex)
        {
            // If any other exception occurs, we set it on the task completion source. Failsafe.
            tcs.TrySetException(ex);
        }
    });

    // Subscribe to the callback. 
    // Note that this will automatically root the callback since it has at least one subscriber.
    callback.Invoked += handler;

/*@SWIG@*/;

    // Run the method with the provided arguments and the callback
    // callback is defined in MAKE_AWAITABLE_CALLBACK_BODY
    GetAnchorsInArea(originLocation,areaRadius,spatialKeys,spatialValues,tags,allTags,spaceIds,skip,limit, callback);

    return tcs.Task;
  }


  public System.Threading.Tasks.Task<csp.systems.AnchorCollectionResult> GetAnchorsInSpaceAsync(string spaceId,int? skip,int? limit)
  {
    // Create a TaskCompletionSource to represent the async operation.
    System.Threading.Tasks.TaskCompletionSource<csp.systems.AnchorCollectionResult> tcs = 
        new System.Threading.Tasks.TaskCompletionSource<csp.systems.AnchorCollectionResult>(System.Threading.Tasks.TaskCreationOptions.RunContinuationsAsynchronously);

    /*@SWIG:D:\a\connected-spaces-platform-unity\connected-spaces-platform-unity\interface\swigutils\AsyncAdapters.i,129,MAKE_ROOTED_ASYNC_CALLBACK_BODY@*/
    ConnectedSpacesPlatformDotNet.AnchorCollectionResultCallback callback =
        new ConnectedSpacesPlatformDotNet.AnchorCollectionResultCallback();

    // Define the callback that will be called by the C++ code
    System.Action<csp.systems.AnchorCollectionResult>? handler = null;
    handler = new ((csp.systems.AnchorCollectionResult result) =>
    {
        try
        {
           /* This is a bit jank. Due to the desire to use passthrough macros between async
            * and actions, we have this result param which yes, can be
            * a comma separated list for action style callbacks, but in async (awaitable) functions,
            * it's only ever a single name.
            * It ISNT always a ResultBase type (although that would simplify things if CSP would do that...)
            * Sometime's it's just a space entity, or a bool, or something else. */

            if((object)result is csp.systems.ResultBase _result)
            {
                // It's a result base

                // Convert the failing result to a throw if we have that option enabled
                _result.ThrowOnFailure(nameof(GetAnchorsInSpaceAsync));


                // Use _result here because we need to call ResultBase api, but we still pass the fully specified type in the TrySetResult
                // Remember that callbacks also have `init` and `inProgress` status's. We will often receive this callback more than once,
                // only finish when we get a final status.  
                if (_result.GetResultCode() == csp.systems.EResultCode.Success ||
                    _result.GetResultCode() == csp.systems.EResultCode.Failed)
                {
                    tcs.TrySetResult(result);
                    // Now that the callback has been invoked and returned success or failure, we no longer need to
                    // await, so we unsubscribe, which should empty the invocation list and unroot the reference for GC. 
                    // Instead, if the result was still pending we would have still needed to await and keep this alive.
                    callback.Invoked -= handler;
                }
            }
            else
            {
                // It's something else
                tcs.TrySetResult(result);
                // Now that the callback has been invoked, we unsubscribe, so that if there is no other subscriber
                // the callback gets automatically unrooted. We do this because we do not expect
                // any more callbacks to come since this is not a ResultBase with pending status. This will
                // trigger the GC of the callback safely, since we no longer await for it.
                callback.Invoked -= handler;
            }
        }
        catch (System.Exception ex)
        {
            // If any other exception occurs, we set it on the task completion source. Failsafe.
            tcs.TrySetException(ex);
        }
    });

    // Subscribe to the callback. 
    // Note that this will automatically root the callback since it has at least one subscriber.
    callback.Invoked += handler;

/*@SWIG@*/;

    // Run the method with the provided arguments and the callback
    // callback is defined in MAKE_AWAITABLE_CALLBACK_BODY
    GetAnchorsInSpace(spaceId,skip,limit, callback);

    return tcs.Task;
  }


  public System.Threading.Tasks.Task<csp.systems.AnchorCollectionResult> GetAnchorsByAssetCollectionIdAsync(string assetCollectionId,int? skip,int? limit)
  {
    // Create a TaskCompletionSource to represent the async operation.
    System.Threading.Tasks.TaskCompletionSource<csp.systems.AnchorCollectionResult> tcs = 
        new System.Threading.Tasks.TaskCompletionSource<csp.systems.AnchorCollectionResult>(System.Threading.Tasks.TaskCreationOptions.RunContinuationsAsynchronously);

    /*@SWIG:D:\a\connected-spaces-platform-unity\connected-spaces-platform-unity\interface\swigutils\AsyncAdapters.i,129,MAKE_ROOTED_ASYNC_CALLBACK_BODY@*/
    ConnectedSpacesPlatformDotNet.AnchorCollectionResultCallback callback =
        new ConnectedSpacesPlatformDotNet.AnchorCollectionResultCallback();

    // Define the callback that will be called by the C++ code
    System.Action<csp.systems.AnchorCollectionResult>? handler = null;
    handler = new ((csp.systems.AnchorCollectionResult result) =>
    {
        try
        {
           /* This is a bit jank. Due to the desire to use passthrough macros between async
            * and actions, we have this result param which yes, can be
            * a comma separated list for action style callbacks, but in async (awaitable) functions,
            * it's only ever a single name.
            * It ISNT always a ResultBase type (although that would simplify things if CSP would do that...)
            * Sometime's it's just a space entity, or a bool, or something else. */

            if((object)result is csp.systems.ResultBase _result)
            {
                // It's a result base

                // Convert the failing result to a throw if we have that option enabled
                _result.ThrowOnFailure(nameof(GetAnchorsByAssetCollectionIdAsync));


                // Use _result here because we need to call ResultBase api, but we still pass the fully specified type in the TrySetResult
                // Remember that callbacks also have `init` and `inProgress` status's. We will often receive this callback more than once,
                // only finish when we get a final status.  
                if (_result.GetResultCode() == csp.systems.EResultCode.Success ||
                    _result.GetResultCode() == csp.systems.EResultCode.Failed)
                {
                    tcs.TrySetResult(result);
                    // Now that the callback has been invoked and returned success or failure, we no longer need to
                    // await, so we unsubscribe, which should empty the invocation list and unroot the reference for GC. 
                    // Instead, if the result was still pending we would have still needed to await and keep this alive.
                    callback.Invoked -= handler;
                }
            }
            else
            {
                // It's something else
                tcs.TrySetResult(result);
                // Now that the callback has been invoked, we unsubscribe, so that if there is no other subscriber
                // the callback gets automatically unrooted. We do this because we do not expect
                // any more callbacks to come since this is not a ResultBase with pending status. This will
                // trigger the GC of the callback safely, since we no longer await for it.
                callback.Invoked -= handler;
            }
        }
        catch (System.Exception ex)
        {
            // If any other exception occurs, we set it on the task completion source. Failsafe.
            tcs.TrySetException(ex);
        }
    });

    // Subscribe to the callback. 
    // Note that this will automatically root the callback since it has at least one subscriber.
    callback.Invoked += handler;

/*@SWIG@*/;

    // Run the method with the provided arguments and the callback
    // callback is defined in MAKE_AWAITABLE_CALLBACK_BODY
    GetAnchorsByAssetCollectionId(assetCollectionId,skip,limit, callback);

    return tcs.Task;
  }


  public System.Threading.Tasks.Task<csp.systems.AnchorResolutionResult> CreateAnchorResolutionAsync(string anchorId,bool successfullyResolved,int resolveAttempted,double resolveTime,csp.common.StringArray tags)
  {
    // Create a TaskCompletionSource to represent the async operation.
    System.Threading.Tasks.TaskCompletionSource<csp.systems.AnchorResolutionResult> tcs = 
        new System.Threading.Tasks.TaskCompletionSource<csp.systems.AnchorResolutionResult>(System.Threading.Tasks.TaskCreationOptions.RunContinuationsAsynchronously);

    /*@SWIG:D:\a\connected-spaces-platform-unity\connected-spaces-platform-unity\interface\swigutils\AsyncAdapters.i,129,MAKE_ROOTED_ASYNC_CALLBACK_BODY@*/
    ConnectedSpacesPlatformDotNet.AnchorResolutionResultCallback callback =
        new ConnectedSpacesPlatformDotNet.AnchorResolutionResultCallback();

    // Define the callback that will be called by the C++ code
    System.Action<csp.systems.AnchorResolutionResult>? handler = null;
    handler = new ((csp.systems.AnchorResolutionResult result) =>
    {
        try
        {
           /* This is a bit jank. Due to the desire to use passthrough macros between async
            * and actions, we have this result param which yes, can be
            * a comma separated list for action style callbacks, but in async (awaitable) functions,
            * it's only ever a single name.
            * It ISNT always a ResultBase type (although that would simplify things if CSP would do that...)
            * Sometime's it's just a space entity, or a bool, or something else. */

            if((object)result is csp.systems.ResultBase _result)
            {
                // It's a result base

                // Convert the failing result to a throw if we have that option enabled
                _result.ThrowOnFailure(nameof(CreateAnchorResolutionAsync));


                // Use _result here because we need to call ResultBase api, but we still pass the fully specified type in the TrySetResult
                // Remember that callbacks also have `init` and `inProgress` status's. We will often receive this callback more than once,
                // only finish when we get a final status.  
                if (_result.GetResultCode() == csp.systems.EResultCode.Success ||
                    _result.GetResultCode() == csp.systems.EResultCode.Failed)
                {
                    tcs.TrySetResult(result);
                    // Now that the callback has been invoked and returned success or failure, we no longer need to
                    // await, so we unsubscribe, which should empty the invocation list and unroot the reference for GC. 
                    // Instead, if the result was still pending we would have still needed to await and keep this alive.
                    callback.Invoked -= handler;
                }
            }
            else
            {
                // It's something else
                tcs.TrySetResult(result);
                // Now that the callback has been invoked, we unsubscribe, so that if there is no other subscriber
                // the callback gets automatically unrooted. We do this because we do not expect
                // any more callbacks to come since this is not a ResultBase with pending status. This will
                // trigger the GC of the callback safely, since we no longer await for it.
                callback.Invoked -= handler;
            }
        }
        catch (System.Exception ex)
        {
            // If any other exception occurs, we set it on the task completion source. Failsafe.
            tcs.TrySetException(ex);
        }
    });

    // Subscribe to the callback. 
    // Note that this will automatically root the callback since it has at least one subscriber.
    callback.Invoked += handler;

/*@SWIG@*/;

    // Run the method with the provided arguments and the callback
    // callback is defined in MAKE_AWAITABLE_CALLBACK_BODY
    CreateAnchorResolution(anchorId,successfullyResolved,resolveAttempted,resolveTime,tags, callback);

    return tcs.Task;
  }

  // Any time this object is returned from an outer C++ object via reference, this is set
  // to prevent premature garbage collection causing premature C++ memory deallocation.
  public object OuterObjectPin { private get; set; }

}

}
