//------------------------------------------------------------------------------
// <auto-generated />
//
// This file was automatically generated by SWIG (https://www.swig.org).
// Version 4.4.0
//
// Do not make changes to this file unless you know what you are doing - modify
// the SWIG interface file instead.
//------------------------------------------------------------------------------

namespace csp.systems {

#nullable enable

public class QuotaSystem : csp.systems.SystemBase {
  private global::System.Runtime.InteropServices.HandleRef swigCPtr;

  internal QuotaSystem(global::System.IntPtr cPtr, bool cMemoryOwn) : base(ConnectedSpacesPlatformDotNetPINVOKE.csp_systems_QuotaSystem_SWIGUpcast(cPtr), cMemoryOwn) {
    swigCPtr = new global::System.Runtime.InteropServices.HandleRef(this, cPtr);
  }

  internal static global::System.Runtime.InteropServices.HandleRef getCPtr(QuotaSystem obj) {
    return (obj == null) ? new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero) : obj.swigCPtr;
  }

  internal static global::System.Runtime.InteropServices.HandleRef swigRelease(QuotaSystem obj) {
    if (obj != null) {
      if (!obj.swigCMemOwn)
        throw new global::System.ApplicationException("Cannot release ownership as memory is not owned");
      global::System.Runtime.InteropServices.HandleRef ptr = obj.swigCPtr;
      obj.swigCMemOwn = false;
      obj.Dispose();
      return ptr;
    } else {
      return new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero);
    }
  }

  protected override void Dispose(bool disposing) {
    lock(this) {
      if (swigCPtr.Handle != global::System.IntPtr.Zero) {
        if (swigCMemOwn) {
          swigCMemOwn = false;
          throw new global::System.MethodAccessException("C++ destructor does not have public access");
        }
        swigCPtr = new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero);
      }
      base.Dispose(disposing);
    }
  }

  public void GetTotalSpacesOwnedByUser(FeatureLimitCallbackAdapter Callback) {
    ConnectedSpacesPlatformDotNetPINVOKE.csp_systems_QuotaSystem_GetTotalSpacesOwnedByUser(swigCPtr, FeatureLimitCallbackAdapter.getCPtr(Callback));
    if (ConnectedSpacesPlatformDotNetPINVOKE.SWIGPendingException.Pending) throw ConnectedSpacesPlatformDotNetPINVOKE.SWIGPendingException.Retrieve();
  }

  public void GetConcurrentUsersInSpace(string SpaceId, FeatureLimitCallbackAdapter Callback) {
    ConnectedSpacesPlatformDotNetPINVOKE.csp_systems_QuotaSystem_GetConcurrentUsersInSpace(swigCPtr, SpaceId, FeatureLimitCallbackAdapter.getCPtr(Callback));
    if (ConnectedSpacesPlatformDotNetPINVOKE.SWIGPendingException.Pending) throw ConnectedSpacesPlatformDotNetPINVOKE.SWIGPendingException.Retrieve();
  }

  public void GetTotalSpaceSizeInKilobytes(string SpaceId, FeatureLimitCallbackAdapter Callback) {
    ConnectedSpacesPlatformDotNetPINVOKE.csp_systems_QuotaSystem_GetTotalSpaceSizeInKilobytes(swigCPtr, SpaceId, FeatureLimitCallbackAdapter.getCPtr(Callback));
    if (ConnectedSpacesPlatformDotNetPINVOKE.SWIGPendingException.Pending) throw ConnectedSpacesPlatformDotNetPINVOKE.SWIGPendingException.Retrieve();
  }

  public void GetTierFeatureProgressForUser(csp.common.TierFeaturesArray FeatureNames, FeaturesLimitCallbackAdapter Callback) {
    ConnectedSpacesPlatformDotNetPINVOKE.csp_systems_QuotaSystem_GetTierFeatureProgressForUser(swigCPtr, csp.common.TierFeaturesArray.getCPtr(FeatureNames), FeaturesLimitCallbackAdapter.getCPtr(Callback));
    if (ConnectedSpacesPlatformDotNetPINVOKE.SWIGPendingException.Pending) throw ConnectedSpacesPlatformDotNetPINVOKE.SWIGPendingException.Retrieve();
  }

  public void GetTierFeatureProgressForSpace(string SpaceId, csp.common.TierFeaturesArray FeatureNames, FeaturesLimitCallbackAdapter Callback) {
    ConnectedSpacesPlatformDotNetPINVOKE.csp_systems_QuotaSystem_GetTierFeatureProgressForSpace(swigCPtr, SpaceId, csp.common.TierFeaturesArray.getCPtr(FeatureNames), FeaturesLimitCallbackAdapter.getCPtr(Callback));
    if (ConnectedSpacesPlatformDotNetPINVOKE.SWIGPendingException.Pending) throw ConnectedSpacesPlatformDotNetPINVOKE.SWIGPendingException.Retrieve();
  }

  public void SetUserTier(csp.systems.TierNames Tier, string UserId, UserTierCallbackAdapter Callback) {
    ConnectedSpacesPlatformDotNetPINVOKE.csp_systems_QuotaSystem_SetUserTier(swigCPtr, (int)Tier, UserId, UserTierCallbackAdapter.getCPtr(Callback));
    if (ConnectedSpacesPlatformDotNetPINVOKE.SWIGPendingException.Pending) throw ConnectedSpacesPlatformDotNetPINVOKE.SWIGPendingException.Retrieve();
  }

  public void GetCurrentUserTier(UserTierCallbackAdapter Callback) {
    ConnectedSpacesPlatformDotNetPINVOKE.csp_systems_QuotaSystem_GetCurrentUserTier(swigCPtr, UserTierCallbackAdapter.getCPtr(Callback));
    if (ConnectedSpacesPlatformDotNetPINVOKE.SWIGPendingException.Pending) throw ConnectedSpacesPlatformDotNetPINVOKE.SWIGPendingException.Retrieve();
  }

  public void GetTierFeatureQuota(csp.systems.TierNames TierName, csp.systems.TierFeatures FeatureName, FeatureQuotaCallbackAdapter Callback) {
    ConnectedSpacesPlatformDotNetPINVOKE.csp_systems_QuotaSystem_GetTierFeatureQuota(swigCPtr, (int)TierName, (int)FeatureName, FeatureQuotaCallbackAdapter.getCPtr(Callback));
    if (ConnectedSpacesPlatformDotNetPINVOKE.SWIGPendingException.Pending) throw ConnectedSpacesPlatformDotNetPINVOKE.SWIGPendingException.Retrieve();
  }

  public void GetTierFeaturesQuota(csp.systems.TierNames TierName, FeaturesQuotaCallbackAdapter Callback) {
    ConnectedSpacesPlatformDotNetPINVOKE.csp_systems_QuotaSystem_GetTierFeaturesQuota(swigCPtr, (int)TierName, FeaturesQuotaCallbackAdapter.getCPtr(Callback));
    if (ConnectedSpacesPlatformDotNetPINVOKE.SWIGPendingException.Pending) throw ConnectedSpacesPlatformDotNetPINVOKE.SWIGPendingException.Retrieve();
  }


  public System.Threading.Tasks.Task<csp.systems.FeatureLimitResult> GetTotalSpaceSizeInKilobytesAsync(string spaceId)
  {
    // Create a TaskCompletionSource to represent the async operation.
    System.Threading.Tasks.TaskCompletionSource<csp.systems.FeatureLimitResult> tcs = 
        new System.Threading.Tasks.TaskCompletionSource<csp.systems.FeatureLimitResult>(System.Threading.Tasks.TaskCreationOptions.RunContinuationsAsynchronously);

    /*@SWIG:D:\a\connected-spaces-platform-unity\connected-spaces-platform-unity\interface\swigutils\AsyncAdapters.i,129,MAKE_ROOTED_ASYNC_CALLBACK_BODY@*/
    ConnectedSpacesPlatformDotNet.FeatureLimitCallback callback =
        new ConnectedSpacesPlatformDotNet.FeatureLimitCallback();

    // Define the callback that will be called by the C++ code
    System.Action<csp.systems.FeatureLimitResult>? handler = null;
    handler = new ((csp.systems.FeatureLimitResult featureLimitResult) =>
    {
        try
        {
           /* This is a bit jank. Due to the desire to use passthrough macros between async
            * and actions, we have this featureLimitResult param which yes, can be
            * a comma separated list for action style callbacks, but in async (awaitable) functions,
            * it's only ever a single name.
            * It ISNT always a ResultBase type (although that would simplify things if CSP would do that...)
            * Sometime's it's just a space entity, or a bool, or something else. */

            if((object)featureLimitResult is csp.systems.ResultBase _result)
            {
                // It's a result base

                // Convert the failing result to a throw if we have that option enabled
                _result.ThrowOnFailure(nameof(GetTotalSpaceSizeInKilobytesAsync));


                // Use _result here because we need to call ResultBase api, but we still pass the fully specified type in the TrySetResult
                // Remember that callbacks also have `init` and `inProgress` status's. We will often receive this callback more than once,
                // only finish when we get a final status.  
                if (_result.GetResultCode() == csp.systems.EResultCode.Success ||
                    _result.GetResultCode() == csp.systems.EResultCode.Failed)
                {
                    tcs.TrySetResult(featureLimitResult);
                    // Now that the callback has been invoked and returned success or failure, we no longer need to
                    // await, so we unsubscribe, which should empty the invocation list and unroot the reference for GC. 
                    // Instead, if the result was still pending we would have still needed to await and keep this alive.
                    callback.Invoked -= handler;
                }
            }
            else
            {
                // It's something else
                tcs.TrySetResult(featureLimitResult);
                // Now that the callback has been invoked, we unsubscribe, so that if there is no other subscriber
                // the callback gets automatically unrooted. We do this because we do not expect
                // any more callbacks to come since this is not a ResultBase with pending status. This will
                // trigger the GC of the callback safely, since we no longer await for it.
                callback.Invoked -= handler;
            }
        }
        catch (System.Exception ex)
        {
            // If any other exception occurs, we set it on the task completion source. Failsafe.
            tcs.TrySetException(ex);
        }
    });

    // Subscribe to the callback. 
    // Note that this will automatically root the callback since it has at least one subscriber.
    callback.Invoked += handler;

/*@SWIG@*/;

    // Run the method with the provided arguments and the callback
    // callback is defined in MAKE_AWAITABLE_CALLBACK_BODY
    GetTotalSpaceSizeInKilobytes(spaceId, callback);

    return tcs.Task;
  }


  public System.Threading.Tasks.Task<csp.systems.FeaturesLimitResult> GetTierFeatureProgressForUserAsync(csp.common.TierFeaturesArray featureNames)
  {
    // Create a TaskCompletionSource to represent the async operation.
    System.Threading.Tasks.TaskCompletionSource<csp.systems.FeaturesLimitResult> tcs = 
        new System.Threading.Tasks.TaskCompletionSource<csp.systems.FeaturesLimitResult>(System.Threading.Tasks.TaskCreationOptions.RunContinuationsAsynchronously);

    /*@SWIG:D:\a\connected-spaces-platform-unity\connected-spaces-platform-unity\interface\swigutils\AsyncAdapters.i,129,MAKE_ROOTED_ASYNC_CALLBACK_BODY@*/
    ConnectedSpacesPlatformDotNet.FeaturesLimitCallback callback =
        new ConnectedSpacesPlatformDotNet.FeaturesLimitCallback();

    // Define the callback that will be called by the C++ code
    System.Action<csp.systems.FeaturesLimitResult>? handler = null;
    handler = new ((csp.systems.FeaturesLimitResult result) =>
    {
        try
        {
           /* This is a bit jank. Due to the desire to use passthrough macros between async
            * and actions, we have this result param which yes, can be
            * a comma separated list for action style callbacks, but in async (awaitable) functions,
            * it's only ever a single name.
            * It ISNT always a ResultBase type (although that would simplify things if CSP would do that...)
            * Sometime's it's just a space entity, or a bool, or something else. */

            if((object)result is csp.systems.ResultBase _result)
            {
                // It's a result base

                // Convert the failing result to a throw if we have that option enabled
                _result.ThrowOnFailure(nameof(GetTierFeatureProgressForUserAsync));


                // Use _result here because we need to call ResultBase api, but we still pass the fully specified type in the TrySetResult
                // Remember that callbacks also have `init` and `inProgress` status's. We will often receive this callback more than once,
                // only finish when we get a final status.  
                if (_result.GetResultCode() == csp.systems.EResultCode.Success ||
                    _result.GetResultCode() == csp.systems.EResultCode.Failed)
                {
                    tcs.TrySetResult(result);
                    // Now that the callback has been invoked and returned success or failure, we no longer need to
                    // await, so we unsubscribe, which should empty the invocation list and unroot the reference for GC. 
                    // Instead, if the result was still pending we would have still needed to await and keep this alive.
                    callback.Invoked -= handler;
                }
            }
            else
            {
                // It's something else
                tcs.TrySetResult(result);
                // Now that the callback has been invoked, we unsubscribe, so that if there is no other subscriber
                // the callback gets automatically unrooted. We do this because we do not expect
                // any more callbacks to come since this is not a ResultBase with pending status. This will
                // trigger the GC of the callback safely, since we no longer await for it.
                callback.Invoked -= handler;
            }
        }
        catch (System.Exception ex)
        {
            // If any other exception occurs, we set it on the task completion source. Failsafe.
            tcs.TrySetException(ex);
        }
    });

    // Subscribe to the callback. 
    // Note that this will automatically root the callback since it has at least one subscriber.
    callback.Invoked += handler;

/*@SWIG@*/;

    // Run the method with the provided arguments and the callback
    // callback is defined in MAKE_AWAITABLE_CALLBACK_BODY
    GetTierFeatureProgressForUser(featureNames, callback);

    return tcs.Task;
  }


  public System.Threading.Tasks.Task<csp.systems.FeaturesLimitResult> GetTierFeatureProgressForSpaceAsync(string spaceId,csp.common.TierFeaturesArray featureNames)
  {
    // Create a TaskCompletionSource to represent the async operation.
    System.Threading.Tasks.TaskCompletionSource<csp.systems.FeaturesLimitResult> tcs = 
        new System.Threading.Tasks.TaskCompletionSource<csp.systems.FeaturesLimitResult>(System.Threading.Tasks.TaskCreationOptions.RunContinuationsAsynchronously);

    /*@SWIG:D:\a\connected-spaces-platform-unity\connected-spaces-platform-unity\interface\swigutils\AsyncAdapters.i,129,MAKE_ROOTED_ASYNC_CALLBACK_BODY@*/
    ConnectedSpacesPlatformDotNet.FeaturesLimitCallback callback =
        new ConnectedSpacesPlatformDotNet.FeaturesLimitCallback();

    // Define the callback that will be called by the C++ code
    System.Action<csp.systems.FeaturesLimitResult>? handler = null;
    handler = new ((csp.systems.FeaturesLimitResult result) =>
    {
        try
        {
           /* This is a bit jank. Due to the desire to use passthrough macros between async
            * and actions, we have this result param which yes, can be
            * a comma separated list for action style callbacks, but in async (awaitable) functions,
            * it's only ever a single name.
            * It ISNT always a ResultBase type (although that would simplify things if CSP would do that...)
            * Sometime's it's just a space entity, or a bool, or something else. */

            if((object)result is csp.systems.ResultBase _result)
            {
                // It's a result base

                // Convert the failing result to a throw if we have that option enabled
                _result.ThrowOnFailure(nameof(GetTierFeatureProgressForSpaceAsync));


                // Use _result here because we need to call ResultBase api, but we still pass the fully specified type in the TrySetResult
                // Remember that callbacks also have `init` and `inProgress` status's. We will often receive this callback more than once,
                // only finish when we get a final status.  
                if (_result.GetResultCode() == csp.systems.EResultCode.Success ||
                    _result.GetResultCode() == csp.systems.EResultCode.Failed)
                {
                    tcs.TrySetResult(result);
                    // Now that the callback has been invoked and returned success or failure, we no longer need to
                    // await, so we unsubscribe, which should empty the invocation list and unroot the reference for GC. 
                    // Instead, if the result was still pending we would have still needed to await and keep this alive.
                    callback.Invoked -= handler;
                }
            }
            else
            {
                // It's something else
                tcs.TrySetResult(result);
                // Now that the callback has been invoked, we unsubscribe, so that if there is no other subscriber
                // the callback gets automatically unrooted. We do this because we do not expect
                // any more callbacks to come since this is not a ResultBase with pending status. This will
                // trigger the GC of the callback safely, since we no longer await for it.
                callback.Invoked -= handler;
            }
        }
        catch (System.Exception ex)
        {
            // If any other exception occurs, we set it on the task completion source. Failsafe.
            tcs.TrySetException(ex);
        }
    });

    // Subscribe to the callback. 
    // Note that this will automatically root the callback since it has at least one subscriber.
    callback.Invoked += handler;

/*@SWIG@*/;

    // Run the method with the provided arguments and the callback
    // callback is defined in MAKE_AWAITABLE_CALLBACK_BODY
    GetTierFeatureProgressForSpace(spaceId,featureNames, callback);

    return tcs.Task;
  }


  public System.Threading.Tasks.Task<csp.systems.UserTierResult> SetUserTierAsync(csp.systems.TierNames tier,string userId)
  {
    // Create a TaskCompletionSource to represent the async operation.
    System.Threading.Tasks.TaskCompletionSource<csp.systems.UserTierResult> tcs = 
        new System.Threading.Tasks.TaskCompletionSource<csp.systems.UserTierResult>(System.Threading.Tasks.TaskCreationOptions.RunContinuationsAsynchronously);

    /*@SWIG:D:\a\connected-spaces-platform-unity\connected-spaces-platform-unity\interface\swigutils\AsyncAdapters.i,129,MAKE_ROOTED_ASYNC_CALLBACK_BODY@*/
    ConnectedSpacesPlatformDotNet.UserTierCallback callback =
        new ConnectedSpacesPlatformDotNet.UserTierCallback();

    // Define the callback that will be called by the C++ code
    System.Action<csp.systems.UserTierResult>? handler = null;
    handler = new ((csp.systems.UserTierResult result) =>
    {
        try
        {
           /* This is a bit jank. Due to the desire to use passthrough macros between async
            * and actions, we have this result param which yes, can be
            * a comma separated list for action style callbacks, but in async (awaitable) functions,
            * it's only ever a single name.
            * It ISNT always a ResultBase type (although that would simplify things if CSP would do that...)
            * Sometime's it's just a space entity, or a bool, or something else. */

            if((object)result is csp.systems.ResultBase _result)
            {
                // It's a result base

                // Convert the failing result to a throw if we have that option enabled
                _result.ThrowOnFailure(nameof(SetUserTierAsync));


                // Use _result here because we need to call ResultBase api, but we still pass the fully specified type in the TrySetResult
                // Remember that callbacks also have `init` and `inProgress` status's. We will often receive this callback more than once,
                // only finish when we get a final status.  
                if (_result.GetResultCode() == csp.systems.EResultCode.Success ||
                    _result.GetResultCode() == csp.systems.EResultCode.Failed)
                {
                    tcs.TrySetResult(result);
                    // Now that the callback has been invoked and returned success or failure, we no longer need to
                    // await, so we unsubscribe, which should empty the invocation list and unroot the reference for GC. 
                    // Instead, if the result was still pending we would have still needed to await and keep this alive.
                    callback.Invoked -= handler;
                }
            }
            else
            {
                // It's something else
                tcs.TrySetResult(result);
                // Now that the callback has been invoked, we unsubscribe, so that if there is no other subscriber
                // the callback gets automatically unrooted. We do this because we do not expect
                // any more callbacks to come since this is not a ResultBase with pending status. This will
                // trigger the GC of the callback safely, since we no longer await for it.
                callback.Invoked -= handler;
            }
        }
        catch (System.Exception ex)
        {
            // If any other exception occurs, we set it on the task completion source. Failsafe.
            tcs.TrySetException(ex);
        }
    });

    // Subscribe to the callback. 
    // Note that this will automatically root the callback since it has at least one subscriber.
    callback.Invoked += handler;

/*@SWIG@*/;

    // Run the method with the provided arguments and the callback
    // callback is defined in MAKE_AWAITABLE_CALLBACK_BODY
    SetUserTier(tier,userId, callback);

    return tcs.Task;
  }

  public System.Threading.Tasks.Task<csp.systems.UserTierResult> GetCurrentUserTierAsync()
  {  
    // Create a TaskCompletionSource to represent the async operation.
    System.Threading.Tasks.TaskCompletionSource<csp.systems.UserTierResult> tcs = 
        new System.Threading.Tasks.TaskCompletionSource<csp.systems.UserTierResult>(System.Threading.Tasks.TaskCreationOptions.RunContinuationsAsynchronously);

    /*@SWIG:D:\a\connected-spaces-platform-unity\connected-spaces-platform-unity\interface\swigutils\AsyncAdapters.i,129,MAKE_ROOTED_ASYNC_CALLBACK_BODY@*/
    ConnectedSpacesPlatformDotNet.UserTierCallback callback =
        new ConnectedSpacesPlatformDotNet.UserTierCallback();

    // Define the callback that will be called by the C++ code
    System.Action<csp.systems.UserTierResult>? handler = null;
    handler = new ((csp.systems.UserTierResult result) =>
    {
        try
        {
           /* This is a bit jank. Due to the desire to use passthrough macros between async
            * and actions, we have this result param which yes, can be
            * a comma separated list for action style callbacks, but in async (awaitable) functions,
            * it's only ever a single name.
            * It ISNT always a ResultBase type (although that would simplify things if CSP would do that...)
            * Sometime's it's just a space entity, or a bool, or something else. */

            if((object)result is csp.systems.ResultBase _result)
            {
                // It's a result base

                // Convert the failing result to a throw if we have that option enabled
                _result.ThrowOnFailure(nameof(GetCurrentUserTierAsync));


                // Use _result here because we need to call ResultBase api, but we still pass the fully specified type in the TrySetResult
                // Remember that callbacks also have `init` and `inProgress` status's. We will often receive this callback more than once,
                // only finish when we get a final status.  
                if (_result.GetResultCode() == csp.systems.EResultCode.Success ||
                    _result.GetResultCode() == csp.systems.EResultCode.Failed)
                {
                    tcs.TrySetResult(result);
                    // Now that the callback has been invoked and returned success or failure, we no longer need to
                    // await, so we unsubscribe, which should empty the invocation list and unroot the reference for GC. 
                    // Instead, if the result was still pending we would have still needed to await and keep this alive.
                    callback.Invoked -= handler;
                }
            }
            else
            {
                // It's something else
                tcs.TrySetResult(result);
                // Now that the callback has been invoked, we unsubscribe, so that if there is no other subscriber
                // the callback gets automatically unrooted. We do this because we do not expect
                // any more callbacks to come since this is not a ResultBase with pending status. This will
                // trigger the GC of the callback safely, since we no longer await for it.
                callback.Invoked -= handler;
            }
        }
        catch (System.Exception ex)
        {
            // If any other exception occurs, we set it on the task completion source. Failsafe.
            tcs.TrySetException(ex);
        }
    });

    // Subscribe to the callback. 
    // Note that this will automatically root the callback since it has at least one subscriber.
    callback.Invoked += handler;

/*@SWIG@*/;

    // Run the method with the provided arguments and the callback
    GetCurrentUserTier(callback);

    return tcs.Task;

  }


  public System.Threading.Tasks.Task<csp.systems.FeatureQuotaResult> GetTierFeatureQuotaAsync(csp.systems.TierNames tierName,csp.systems.TierFeatures featureName)
  {
    // Create a TaskCompletionSource to represent the async operation.
    System.Threading.Tasks.TaskCompletionSource<csp.systems.FeatureQuotaResult> tcs = 
        new System.Threading.Tasks.TaskCompletionSource<csp.systems.FeatureQuotaResult>(System.Threading.Tasks.TaskCreationOptions.RunContinuationsAsynchronously);

    /*@SWIG:D:\a\connected-spaces-platform-unity\connected-spaces-platform-unity\interface\swigutils\AsyncAdapters.i,129,MAKE_ROOTED_ASYNC_CALLBACK_BODY@*/
    ConnectedSpacesPlatformDotNet.FeatureQuotaCallback callback =
        new ConnectedSpacesPlatformDotNet.FeatureQuotaCallback();

    // Define the callback that will be called by the C++ code
    System.Action<csp.systems.FeatureQuotaResult>? handler = null;
    handler = new ((csp.systems.FeatureQuotaResult result) =>
    {
        try
        {
           /* This is a bit jank. Due to the desire to use passthrough macros between async
            * and actions, we have this result param which yes, can be
            * a comma separated list for action style callbacks, but in async (awaitable) functions,
            * it's only ever a single name.
            * It ISNT always a ResultBase type (although that would simplify things if CSP would do that...)
            * Sometime's it's just a space entity, or a bool, or something else. */

            if((object)result is csp.systems.ResultBase _result)
            {
                // It's a result base

                // Convert the failing result to a throw if we have that option enabled
                _result.ThrowOnFailure(nameof(GetTierFeatureQuotaAsync));


                // Use _result here because we need to call ResultBase api, but we still pass the fully specified type in the TrySetResult
                // Remember that callbacks also have `init` and `inProgress` status's. We will often receive this callback more than once,
                // only finish when we get a final status.  
                if (_result.GetResultCode() == csp.systems.EResultCode.Success ||
                    _result.GetResultCode() == csp.systems.EResultCode.Failed)
                {
                    tcs.TrySetResult(result);
                    // Now that the callback has been invoked and returned success or failure, we no longer need to
                    // await, so we unsubscribe, which should empty the invocation list and unroot the reference for GC. 
                    // Instead, if the result was still pending we would have still needed to await and keep this alive.
                    callback.Invoked -= handler;
                }
            }
            else
            {
                // It's something else
                tcs.TrySetResult(result);
                // Now that the callback has been invoked, we unsubscribe, so that if there is no other subscriber
                // the callback gets automatically unrooted. We do this because we do not expect
                // any more callbacks to come since this is not a ResultBase with pending status. This will
                // trigger the GC of the callback safely, since we no longer await for it.
                callback.Invoked -= handler;
            }
        }
        catch (System.Exception ex)
        {
            // If any other exception occurs, we set it on the task completion source. Failsafe.
            tcs.TrySetException(ex);
        }
    });

    // Subscribe to the callback. 
    // Note that this will automatically root the callback since it has at least one subscriber.
    callback.Invoked += handler;

/*@SWIG@*/;

    // Run the method with the provided arguments and the callback
    // callback is defined in MAKE_AWAITABLE_CALLBACK_BODY
    GetTierFeatureQuota(tierName,featureName, callback);

    return tcs.Task;
  }


  public System.Threading.Tasks.Task<csp.systems.FeaturesQuotaResult> GetTierFeaturesQuotaAsync(csp.systems.TierNames tierName)
  {
    // Create a TaskCompletionSource to represent the async operation.
    System.Threading.Tasks.TaskCompletionSource<csp.systems.FeaturesQuotaResult> tcs = 
        new System.Threading.Tasks.TaskCompletionSource<csp.systems.FeaturesQuotaResult>(System.Threading.Tasks.TaskCreationOptions.RunContinuationsAsynchronously);

    /*@SWIG:D:\a\connected-spaces-platform-unity\connected-spaces-platform-unity\interface\swigutils\AsyncAdapters.i,129,MAKE_ROOTED_ASYNC_CALLBACK_BODY@*/
    ConnectedSpacesPlatformDotNet.FeaturesQuotaCallback callback =
        new ConnectedSpacesPlatformDotNet.FeaturesQuotaCallback();

    // Define the callback that will be called by the C++ code
    System.Action<csp.systems.FeaturesQuotaResult>? handler = null;
    handler = new ((csp.systems.FeaturesQuotaResult result) =>
    {
        try
        {
           /* This is a bit jank. Due to the desire to use passthrough macros between async
            * and actions, we have this result param which yes, can be
            * a comma separated list for action style callbacks, but in async (awaitable) functions,
            * it's only ever a single name.
            * It ISNT always a ResultBase type (although that would simplify things if CSP would do that...)
            * Sometime's it's just a space entity, or a bool, or something else. */

            if((object)result is csp.systems.ResultBase _result)
            {
                // It's a result base

                // Convert the failing result to a throw if we have that option enabled
                _result.ThrowOnFailure(nameof(GetTierFeaturesQuotaAsync));


                // Use _result here because we need to call ResultBase api, but we still pass the fully specified type in the TrySetResult
                // Remember that callbacks also have `init` and `inProgress` status's. We will often receive this callback more than once,
                // only finish when we get a final status.  
                if (_result.GetResultCode() == csp.systems.EResultCode.Success ||
                    _result.GetResultCode() == csp.systems.EResultCode.Failed)
                {
                    tcs.TrySetResult(result);
                    // Now that the callback has been invoked and returned success or failure, we no longer need to
                    // await, so we unsubscribe, which should empty the invocation list and unroot the reference for GC. 
                    // Instead, if the result was still pending we would have still needed to await and keep this alive.
                    callback.Invoked -= handler;
                }
            }
            else
            {
                // It's something else
                tcs.TrySetResult(result);
                // Now that the callback has been invoked, we unsubscribe, so that if there is no other subscriber
                // the callback gets automatically unrooted. We do this because we do not expect
                // any more callbacks to come since this is not a ResultBase with pending status. This will
                // trigger the GC of the callback safely, since we no longer await for it.
                callback.Invoked -= handler;
            }
        }
        catch (System.Exception ex)
        {
            // If any other exception occurs, we set it on the task completion source. Failsafe.
            tcs.TrySetException(ex);
        }
    });

    // Subscribe to the callback. 
    // Note that this will automatically root the callback since it has at least one subscriber.
    callback.Invoked += handler;

/*@SWIG@*/;

    // Run the method with the provided arguments and the callback
    // callback is defined in MAKE_AWAITABLE_CALLBACK_BODY
    GetTierFeaturesQuota(tierName, callback);

    return tcs.Task;
  }

  public System.Threading.Tasks.Task<csp.systems.FeatureLimitResult> GetTotalSpacesOwnedByUserAsync()
  {  
    // Create a TaskCompletionSource to represent the async operation.
    System.Threading.Tasks.TaskCompletionSource<csp.systems.FeatureLimitResult> tcs = 
        new System.Threading.Tasks.TaskCompletionSource<csp.systems.FeatureLimitResult>(System.Threading.Tasks.TaskCreationOptions.RunContinuationsAsynchronously);

    /*@SWIG:D:\a\connected-spaces-platform-unity\connected-spaces-platform-unity\interface\swigutils\AsyncAdapters.i,129,MAKE_ROOTED_ASYNC_CALLBACK_BODY@*/
    ConnectedSpacesPlatformDotNet.FeatureLimitCallback callback =
        new ConnectedSpacesPlatformDotNet.FeatureLimitCallback();

    // Define the callback that will be called by the C++ code
    System.Action<csp.systems.FeatureLimitResult>? handler = null;
    handler = new ((csp.systems.FeatureLimitResult featureLimitResult) =>
    {
        try
        {
           /* This is a bit jank. Due to the desire to use passthrough macros between async
            * and actions, we have this featureLimitResult param which yes, can be
            * a comma separated list for action style callbacks, but in async (awaitable) functions,
            * it's only ever a single name.
            * It ISNT always a ResultBase type (although that would simplify things if CSP would do that...)
            * Sometime's it's just a space entity, or a bool, or something else. */

            if((object)featureLimitResult is csp.systems.ResultBase _result)
            {
                // It's a result base

                // Convert the failing result to a throw if we have that option enabled
                _result.ThrowOnFailure(nameof(GetTotalSpacesOwnedByUserAsync));


                // Use _result here because we need to call ResultBase api, but we still pass the fully specified type in the TrySetResult
                // Remember that callbacks also have `init` and `inProgress` status's. We will often receive this callback more than once,
                // only finish when we get a final status.  
                if (_result.GetResultCode() == csp.systems.EResultCode.Success ||
                    _result.GetResultCode() == csp.systems.EResultCode.Failed)
                {
                    tcs.TrySetResult(featureLimitResult);
                    // Now that the callback has been invoked and returned success or failure, we no longer need to
                    // await, so we unsubscribe, which should empty the invocation list and unroot the reference for GC. 
                    // Instead, if the result was still pending we would have still needed to await and keep this alive.
                    callback.Invoked -= handler;
                }
            }
            else
            {
                // It's something else
                tcs.TrySetResult(featureLimitResult);
                // Now that the callback has been invoked, we unsubscribe, so that if there is no other subscriber
                // the callback gets automatically unrooted. We do this because we do not expect
                // any more callbacks to come since this is not a ResultBase with pending status. This will
                // trigger the GC of the callback safely, since we no longer await for it.
                callback.Invoked -= handler;
            }
        }
        catch (System.Exception ex)
        {
            // If any other exception occurs, we set it on the task completion source. Failsafe.
            tcs.TrySetException(ex);
        }
    });

    // Subscribe to the callback. 
    // Note that this will automatically root the callback since it has at least one subscriber.
    callback.Invoked += handler;

/*@SWIG@*/;

    // Run the method with the provided arguments and the callback
    GetTotalSpacesOwnedByUser(callback);

    return tcs.Task;

  }


  public System.Threading.Tasks.Task<csp.systems.FeatureLimitResult> GetConcurrentUsersInSpaceAsync(string spaceID)
  {
    // Create a TaskCompletionSource to represent the async operation.
    System.Threading.Tasks.TaskCompletionSource<csp.systems.FeatureLimitResult> tcs = 
        new System.Threading.Tasks.TaskCompletionSource<csp.systems.FeatureLimitResult>(System.Threading.Tasks.TaskCreationOptions.RunContinuationsAsynchronously);

    /*@SWIG:D:\a\connected-spaces-platform-unity\connected-spaces-platform-unity\interface\swigutils\AsyncAdapters.i,129,MAKE_ROOTED_ASYNC_CALLBACK_BODY@*/
    ConnectedSpacesPlatformDotNet.FeatureLimitCallback callback =
        new ConnectedSpacesPlatformDotNet.FeatureLimitCallback();

    // Define the callback that will be called by the C++ code
    System.Action<csp.systems.FeatureLimitResult>? handler = null;
    handler = new ((csp.systems.FeatureLimitResult featureLimitResult) =>
    {
        try
        {
           /* This is a bit jank. Due to the desire to use passthrough macros between async
            * and actions, we have this featureLimitResult param which yes, can be
            * a comma separated list for action style callbacks, but in async (awaitable) functions,
            * it's only ever a single name.
            * It ISNT always a ResultBase type (although that would simplify things if CSP would do that...)
            * Sometime's it's just a space entity, or a bool, or something else. */

            if((object)featureLimitResult is csp.systems.ResultBase _result)
            {
                // It's a result base

                // Convert the failing result to a throw if we have that option enabled
                _result.ThrowOnFailure(nameof(GetConcurrentUsersInSpaceAsync));


                // Use _result here because we need to call ResultBase api, but we still pass the fully specified type in the TrySetResult
                // Remember that callbacks also have `init` and `inProgress` status's. We will often receive this callback more than once,
                // only finish when we get a final status.  
                if (_result.GetResultCode() == csp.systems.EResultCode.Success ||
                    _result.GetResultCode() == csp.systems.EResultCode.Failed)
                {
                    tcs.TrySetResult(featureLimitResult);
                    // Now that the callback has been invoked and returned success or failure, we no longer need to
                    // await, so we unsubscribe, which should empty the invocation list and unroot the reference for GC. 
                    // Instead, if the result was still pending we would have still needed to await and keep this alive.
                    callback.Invoked -= handler;
                }
            }
            else
            {
                // It's something else
                tcs.TrySetResult(featureLimitResult);
                // Now that the callback has been invoked, we unsubscribe, so that if there is no other subscriber
                // the callback gets automatically unrooted. We do this because we do not expect
                // any more callbacks to come since this is not a ResultBase with pending status. This will
                // trigger the GC of the callback safely, since we no longer await for it.
                callback.Invoked -= handler;
            }
        }
        catch (System.Exception ex)
        {
            // If any other exception occurs, we set it on the task completion source. Failsafe.
            tcs.TrySetException(ex);
        }
    });

    // Subscribe to the callback. 
    // Note that this will automatically root the callback since it has at least one subscriber.
    callback.Invoked += handler;

/*@SWIG@*/;

    // Run the method with the provided arguments and the callback
    // callback is defined in MAKE_AWAITABLE_CALLBACK_BODY
    GetConcurrentUsersInSpace(spaceID, callback);

    return tcs.Task;
  }

  // Any time this object is returned from an outer C++ object via reference, this is set
  // to prevent premature garbage collection causing premature C++ memory deallocation.
  public object OuterObjectPin { private get; set; }

}

}
