//------------------------------------------------------------------------------
// <auto-generated />
//
// This file was automatically generated by SWIG (https://www.swig.org).
// Version 4.4.0
//
// Do not make changes to this file unless you know what you are doing - modify
// the SWIG interface file instead.
//------------------------------------------------------------------------------

namespace csp.multiplayer {

#nullable enable

public class CinematicCameraSpaceComponent : csp.multiplayer.ComponentBase, IThirdPartyComponentRef, IPositionComponent, IRotationComponent, IEnableableComponent {
  private global::System.Runtime.InteropServices.HandleRef swigCPtr;

  internal CinematicCameraSpaceComponent(global::System.IntPtr cPtr, bool cMemoryOwn) : base(ConnectedSpacesPlatformDotNetPINVOKE.csp_multiplayer_CinematicCameraSpaceComponent_SWIGUpcast(cPtr), cMemoryOwn) {
    swigCPtr = new global::System.Runtime.InteropServices.HandleRef(this, cPtr);
  }

  internal static global::System.Runtime.InteropServices.HandleRef getCPtr(CinematicCameraSpaceComponent obj) {
    return (obj == null) ? new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero) : obj.swigCPtr;
  }

  internal static global::System.Runtime.InteropServices.HandleRef swigRelease(CinematicCameraSpaceComponent obj) {
    if (obj != null) {
      if (!obj.swigCMemOwn)
        throw new global::System.ApplicationException("Cannot release ownership as memory is not owned");
      global::System.Runtime.InteropServices.HandleRef ptr = obj.swigCPtr;
      obj.swigCMemOwn = false;
      obj.Dispose();
      return ptr;
    } else {
      return new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero);
    }
  }

  protected override void Dispose(bool disposing) {
    lock(this) {
      if (swigCPtr.Handle != global::System.IntPtr.Zero) {
        if (swigCMemOwn) {
          swigCMemOwn = false;
          ConnectedSpacesPlatformDotNetPINVOKE.delete_csp_multiplayer_CinematicCameraSpaceComponent(swigCPtr);
        }
        swigCPtr = new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero);
      }
      base.Dispose(disposing);
    }
  }

  [System.ComponentModel.EditorBrowsable(System.ComponentModel.EditorBrowsableState.Never)]
  global::System.Runtime.InteropServices.HandleRef IThirdPartyComponentRef.GetInterfaceCPtr() {
    return new global::System.Runtime.InteropServices.HandleRef(this, ConnectedSpacesPlatformDotNetPINVOKE.csp_multiplayer_CinematicCameraSpaceComponent_IThirdPartyComponentRef_GetInterfaceCPtr(swigCPtr.Handle));
  }

  [System.ComponentModel.EditorBrowsable(System.ComponentModel.EditorBrowsableState.Never)]
  global::System.Runtime.InteropServices.HandleRef IPositionComponent.GetInterfaceCPtr() {
    return new global::System.Runtime.InteropServices.HandleRef(this, ConnectedSpacesPlatformDotNetPINVOKE.csp_multiplayer_CinematicCameraSpaceComponent_IPositionComponent_GetInterfaceCPtr(swigCPtr.Handle));
  }

  [System.ComponentModel.EditorBrowsable(System.ComponentModel.EditorBrowsableState.Never)]
  global::System.Runtime.InteropServices.HandleRef IRotationComponent.GetInterfaceCPtr() {
    return new global::System.Runtime.InteropServices.HandleRef(this, ConnectedSpacesPlatformDotNetPINVOKE.csp_multiplayer_CinematicCameraSpaceComponent_IRotationComponent_GetInterfaceCPtr(swigCPtr.Handle));
  }

  [System.ComponentModel.EditorBrowsable(System.ComponentModel.EditorBrowsableState.Never)]
  global::System.Runtime.InteropServices.HandleRef IEnableableComponent.GetInterfaceCPtr() {
    return new global::System.Runtime.InteropServices.HandleRef(this, ConnectedSpacesPlatformDotNetPINVOKE.csp_multiplayer_CinematicCameraSpaceComponent_IEnableableComponent_GetInterfaceCPtr(swigCPtr.Handle));
  }


  // Returns null on failure.
  public static csp.multiplayer.CinematicCameraSpaceComponent? TryFromBaseCast(csp.multiplayer.ComponentBase baseObj)
  {
    return NativeFromBaseCast(baseObj);
  }

  // Throws ArgumentException on failure.
  public static csp.multiplayer.CinematicCameraSpaceComponent FromBaseCast(csp.multiplayer.ComponentBase baseObj)
  {
    csp.multiplayer.CinematicCameraSpaceComponent? derived = TryFromBaseCast(baseObj);
    if (derived == null){
      throw new System.ArgumentException("Failed to cast " + nameof(csp.multiplayer.ComponentBase) + " to " + nameof(csp.multiplayer.CinematicCameraSpaceComponent), "baseObj");
    }
    return derived;
  }


  public CinematicCameraSpaceComponent(csp.common.LogSystem LogSystem, csp.multiplayer.SpaceEntity Parent) : this(ConnectedSpacesPlatformDotNetPINVOKE.new_csp_multiplayer_CinematicCameraSpaceComponent((LogSystem != null && csp.common.LogSystem.getCPtr(LogSystem).Handle == global::System.IntPtr.Zero) ? throw new global::System.ObjectDisposedException("LogSystem", "Passed a disposed C# SWIG wrapper (null native handle) to C++. This indicates an object lifecycle bug needing investigation. Note: This does not detect C++-side deletions.") : csp.common.LogSystem.getCPtr(LogSystem), (Parent != null && csp.multiplayer.SpaceEntity.getCPtr(Parent).Handle == global::System.IntPtr.Zero) ? throw new global::System.ObjectDisposedException("Parent", "Passed a disposed C# SWIG wrapper (null native handle) to C++. This indicates an object lifecycle bug needing investigation. Note: This does not detect C++-side deletions.") : csp.multiplayer.SpaceEntity.getCPtr(Parent)), true) {
    if (ConnectedSpacesPlatformDotNetPINVOKE.SWIGPendingException.Pending) throw ConnectedSpacesPlatformDotNetPINVOKE.SWIGPendingException.Retrieve();
  }

  public float GetFov() {
    float ret = ConnectedSpacesPlatformDotNetPINVOKE.csp_multiplayer_CinematicCameraSpaceComponent_GetFov(swigCPtr);
    if (ConnectedSpacesPlatformDotNetPINVOKE.SWIGPendingException.Pending) throw ConnectedSpacesPlatformDotNetPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public virtual csp.common.Vector3 GetPosition() {
  global::System.IntPtr cPtr = ConnectedSpacesPlatformDotNetPINVOKE.csp_multiplayer_CinematicCameraSpaceComponent_GetPosition(swigCPtr);
    if (ConnectedSpacesPlatformDotNetPINVOKE.SWIGPendingException.Pending) throw ConnectedSpacesPlatformDotNetPINVOKE.SWIGPendingException.Retrieve();
  csp.common.Vector3 ret = null;
  if (cPtr != global::System.IntPtr.Zero) {
    ret = new csp.common.Vector3(cPtr, false);
    ret.OuterObjectPin = this;
  }
  return ret;
}

  public virtual void SetPosition(csp.common.Vector3 InValue) {
    ConnectedSpacesPlatformDotNetPINVOKE.csp_multiplayer_CinematicCameraSpaceComponent_SetPosition(swigCPtr, csp.common.Vector3.getCPtr(InValue));
    if (ConnectedSpacesPlatformDotNetPINVOKE.SWIGPendingException.Pending) throw ConnectedSpacesPlatformDotNetPINVOKE.SWIGPendingException.Retrieve();
  }

  public virtual csp.common.Vector4 GetRotation() {
  global::System.IntPtr cPtr = ConnectedSpacesPlatformDotNetPINVOKE.csp_multiplayer_CinematicCameraSpaceComponent_GetRotation(swigCPtr);
    if (ConnectedSpacesPlatformDotNetPINVOKE.SWIGPendingException.Pending) throw ConnectedSpacesPlatformDotNetPINVOKE.SWIGPendingException.Retrieve();
  csp.common.Vector4 ret = null;
  if (cPtr != global::System.IntPtr.Zero) {
    ret = new csp.common.Vector4(cPtr, false);
    ret.OuterObjectPin = this;
  }
  return ret;
}

  public virtual void SetRotation(csp.common.Vector4 InValue) {
    ConnectedSpacesPlatformDotNetPINVOKE.csp_multiplayer_CinematicCameraSpaceComponent_SetRotation(swigCPtr, csp.common.Vector4.getCPtr(InValue));
    if (ConnectedSpacesPlatformDotNetPINVOKE.SWIGPendingException.Pending) throw ConnectedSpacesPlatformDotNetPINVOKE.SWIGPendingException.Retrieve();
  }

  public float GetFocalLength() {
    float ret = ConnectedSpacesPlatformDotNetPINVOKE.csp_multiplayer_CinematicCameraSpaceComponent_GetFocalLength(swigCPtr);
    if (ConnectedSpacesPlatformDotNetPINVOKE.SWIGPendingException.Pending) throw ConnectedSpacesPlatformDotNetPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public void SetFocalLength(float Value) {
    ConnectedSpacesPlatformDotNetPINVOKE.csp_multiplayer_CinematicCameraSpaceComponent_SetFocalLength(swigCPtr, Value);
    if (ConnectedSpacesPlatformDotNetPINVOKE.SWIGPendingException.Pending) throw ConnectedSpacesPlatformDotNetPINVOKE.SWIGPendingException.Retrieve();
  }

  public float GetAspectRatio() {
    float ret = ConnectedSpacesPlatformDotNetPINVOKE.csp_multiplayer_CinematicCameraSpaceComponent_GetAspectRatio(swigCPtr);
    if (ConnectedSpacesPlatformDotNetPINVOKE.SWIGPendingException.Pending) throw ConnectedSpacesPlatformDotNetPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public void SetAspectRatio(float Value) {
    ConnectedSpacesPlatformDotNetPINVOKE.csp_multiplayer_CinematicCameraSpaceComponent_SetAspectRatio(swigCPtr, Value);
    if (ConnectedSpacesPlatformDotNetPINVOKE.SWIGPendingException.Pending) throw ConnectedSpacesPlatformDotNetPINVOKE.SWIGPendingException.Retrieve();
  }

  public csp.common.Vector2 GetSensorSize() {
  global::System.IntPtr cPtr = ConnectedSpacesPlatformDotNetPINVOKE.csp_multiplayer_CinematicCameraSpaceComponent_GetSensorSize(swigCPtr);
    if (ConnectedSpacesPlatformDotNetPINVOKE.SWIGPendingException.Pending) throw ConnectedSpacesPlatformDotNetPINVOKE.SWIGPendingException.Retrieve();
  csp.common.Vector2 ret = null;
  if (cPtr != global::System.IntPtr.Zero) {
    ret = new csp.common.Vector2(cPtr, false);
    ret.OuterObjectPin = this;
  }
  return ret;
}

  public void SetSensorSize(csp.common.Vector2 Value) {
    ConnectedSpacesPlatformDotNetPINVOKE.csp_multiplayer_CinematicCameraSpaceComponent_SetSensorSize(swigCPtr, csp.common.Vector2.getCPtr(Value));
    if (ConnectedSpacesPlatformDotNetPINVOKE.SWIGPendingException.Pending) throw ConnectedSpacesPlatformDotNetPINVOKE.SWIGPendingException.Retrieve();
  }

  public float GetNearClip() {
    float ret = ConnectedSpacesPlatformDotNetPINVOKE.csp_multiplayer_CinematicCameraSpaceComponent_GetNearClip(swigCPtr);
    if (ConnectedSpacesPlatformDotNetPINVOKE.SWIGPendingException.Pending) throw ConnectedSpacesPlatformDotNetPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public void SetNearClip(float Value) {
    ConnectedSpacesPlatformDotNetPINVOKE.csp_multiplayer_CinematicCameraSpaceComponent_SetNearClip(swigCPtr, Value);
    if (ConnectedSpacesPlatformDotNetPINVOKE.SWIGPendingException.Pending) throw ConnectedSpacesPlatformDotNetPINVOKE.SWIGPendingException.Retrieve();
  }

  public float GetFarClip() {
    float ret = ConnectedSpacesPlatformDotNetPINVOKE.csp_multiplayer_CinematicCameraSpaceComponent_GetFarClip(swigCPtr);
    if (ConnectedSpacesPlatformDotNetPINVOKE.SWIGPendingException.Pending) throw ConnectedSpacesPlatformDotNetPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public void SetFarClip(float Value) {
    ConnectedSpacesPlatformDotNetPINVOKE.csp_multiplayer_CinematicCameraSpaceComponent_SetFarClip(swigCPtr, Value);
    if (ConnectedSpacesPlatformDotNetPINVOKE.SWIGPendingException.Pending) throw ConnectedSpacesPlatformDotNetPINVOKE.SWIGPendingException.Retrieve();
  }

  public float GetIso() {
    float ret = ConnectedSpacesPlatformDotNetPINVOKE.csp_multiplayer_CinematicCameraSpaceComponent_GetIso(swigCPtr);
    if (ConnectedSpacesPlatformDotNetPINVOKE.SWIGPendingException.Pending) throw ConnectedSpacesPlatformDotNetPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public void SetIso(float Value) {
    ConnectedSpacesPlatformDotNetPINVOKE.csp_multiplayer_CinematicCameraSpaceComponent_SetIso(swigCPtr, Value);
    if (ConnectedSpacesPlatformDotNetPINVOKE.SWIGPendingException.Pending) throw ConnectedSpacesPlatformDotNetPINVOKE.SWIGPendingException.Retrieve();
  }

  public float GetShutterSpeed() {
    float ret = ConnectedSpacesPlatformDotNetPINVOKE.csp_multiplayer_CinematicCameraSpaceComponent_GetShutterSpeed(swigCPtr);
    if (ConnectedSpacesPlatformDotNetPINVOKE.SWIGPendingException.Pending) throw ConnectedSpacesPlatformDotNetPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public void SetShutterSpeed(float Value) {
    ConnectedSpacesPlatformDotNetPINVOKE.csp_multiplayer_CinematicCameraSpaceComponent_SetShutterSpeed(swigCPtr, Value);
    if (ConnectedSpacesPlatformDotNetPINVOKE.SWIGPendingException.Pending) throw ConnectedSpacesPlatformDotNetPINVOKE.SWIGPendingException.Retrieve();
  }

  public float GetAperture() {
    float ret = ConnectedSpacesPlatformDotNetPINVOKE.csp_multiplayer_CinematicCameraSpaceComponent_GetAperture(swigCPtr);
    if (ConnectedSpacesPlatformDotNetPINVOKE.SWIGPendingException.Pending) throw ConnectedSpacesPlatformDotNetPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public void SetAperture(float Value) {
    ConnectedSpacesPlatformDotNetPINVOKE.csp_multiplayer_CinematicCameraSpaceComponent_SetAperture(swigCPtr, Value);
    if (ConnectedSpacesPlatformDotNetPINVOKE.SWIGPendingException.Pending) throw ConnectedSpacesPlatformDotNetPINVOKE.SWIGPendingException.Retrieve();
  }

  public bool GetIsViewerCamera() {
    bool ret = ConnectedSpacesPlatformDotNetPINVOKE.csp_multiplayer_CinematicCameraSpaceComponent_GetIsViewerCamera(swigCPtr);
    if (ConnectedSpacesPlatformDotNetPINVOKE.SWIGPendingException.Pending) throw ConnectedSpacesPlatformDotNetPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public void SetIsViewerCamera(bool Value) {
    ConnectedSpacesPlatformDotNetPINVOKE.csp_multiplayer_CinematicCameraSpaceComponent_SetIsViewerCamera(swigCPtr, Value);
    if (ConnectedSpacesPlatformDotNetPINVOKE.SWIGPendingException.Pending) throw ConnectedSpacesPlatformDotNetPINVOKE.SWIGPendingException.Retrieve();
  }

  public virtual bool GetIsEnabled() {
    bool ret = ConnectedSpacesPlatformDotNetPINVOKE.csp_multiplayer_CinematicCameraSpaceComponent_GetIsEnabled(swigCPtr);
    if (ConnectedSpacesPlatformDotNetPINVOKE.SWIGPendingException.Pending) throw ConnectedSpacesPlatformDotNetPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public virtual void SetIsEnabled(bool InValue) {
    ConnectedSpacesPlatformDotNetPINVOKE.csp_multiplayer_CinematicCameraSpaceComponent_SetIsEnabled(swigCPtr, InValue);
    if (ConnectedSpacesPlatformDotNetPINVOKE.SWIGPendingException.Pending) throw ConnectedSpacesPlatformDotNetPINVOKE.SWIGPendingException.Retrieve();
  }

  public virtual string GetThirdPartyComponentRef() {
    string ret = ConnectedSpacesPlatformDotNetPINVOKE.csp_multiplayer_CinematicCameraSpaceComponent_GetThirdPartyComponentRef(swigCPtr);
    if (ConnectedSpacesPlatformDotNetPINVOKE.SWIGPendingException.Pending) throw ConnectedSpacesPlatformDotNetPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public virtual void SetThirdPartyComponentRef(string InValue) {
    ConnectedSpacesPlatformDotNetPINVOKE.csp_multiplayer_CinematicCameraSpaceComponent_SetThirdPartyComponentRef(swigCPtr, InValue);
    if (ConnectedSpacesPlatformDotNetPINVOKE.SWIGPendingException.Pending) throw ConnectedSpacesPlatformDotNetPINVOKE.SWIGPendingException.Retrieve();
  }

  // Any time this object is returned from an outer C++ object via reference, this is set
  // to prevent premature garbage collection causing premature C++ memory deallocation.
  public object OuterObjectPin { private get; set; }

  internal static csp.multiplayer.CinematicCameraSpaceComponent NativeFromBaseCast(csp.multiplayer.ComponentBase baseObj) {
    global::System.IntPtr cPtr = ConnectedSpacesPlatformDotNetPINVOKE.csp_multiplayer_CinematicCameraSpaceComponent_NativeFromBaseCast((baseObj != null && csp.multiplayer.ComponentBase.getCPtr(baseObj).Handle == global::System.IntPtr.Zero) ? throw new global::System.ObjectDisposedException("baseObj", "Passed a disposed C# SWIG wrapper (null native handle) to C++. This indicates an object lifecycle bug needing investigation. Note: This does not detect C++-side deletions.") : csp.multiplayer.ComponentBase.getCPtr(baseObj));
    csp.multiplayer.CinematicCameraSpaceComponent ret = (cPtr == global::System.IntPtr.Zero) ? null : new csp.multiplayer.CinematicCameraSpaceComponent(cPtr, false);
    if (ConnectedSpacesPlatformDotNetPINVOKE.SWIGPendingException.Pending) throw ConnectedSpacesPlatformDotNetPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

}

}
