//------------------------------------------------------------------------------
// <auto-generated />
//
// This file was automatically generated by SWIG (https://www.swig.org).
// Version 4.4.0
//
// Do not make changes to this file unless you know what you are doing - modify
// the SWIG interface file instead.
//------------------------------------------------------------------------------

namespace csp.multiplayer {

public enum ComponentType {
  Invalid = 0,
  Core = 1,
  UIController_DEPRECATED = 2,
  StaticModel = 3,
  AnimatedModel = 4,
  MediaSurface_DEPRECATED = 5,
  VideoPlayer = 6,
  ImageSequencer_DEPRECATED = 7,
  ExternalLink = 8,
  AvatarData = 9,
  Light = 10,
  Button = 11,
  Image = 12,
  ScriptData = 13,
  Custom = 14,
  Conversation = 15,
  Portal = 16,
  Audio = 17,
  Spline = 18,
  Collision = 19,
  Reflection = 20,
  Fog = 21,
  ECommerce = 22,
  FiducialMarker = 23,
  GaussianSplat = 24,
  Text = 25,
  Hotspot = 26,
  CinematicCamera = 27,
  ScreenSharing = 28,
  AIChatbot = 29,
  Delete = 56
}

}
