//------------------------------------------------------------------------------
// <auto-generated />
//
// This file was automatically generated by SWIG (https://www.swig.org).
// Version 4.4.0
//
// Do not make changes to this file unless you know what you are doing - modify
// the SWIG interface file instead.
//------------------------------------------------------------------------------

namespace csp.multiplayer {

#nullable enable

public class IAudioControlComponentSwigImpl : IAudioControlComponent, global::System.IDisposable {
  private global::System.Runtime.InteropServices.HandleRef swigCPtr;
  protected bool swigCMemOwn;

  internal IAudioControlComponentSwigImpl(global::System.IntPtr cPtr, bool cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = new global::System.Runtime.InteropServices.HandleRef(this, cPtr);
  }

  internal static global::System.Runtime.InteropServices.HandleRef getCPtr(IAudioControlComponentSwigImpl obj) {
    return (obj == null) ? new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero) : obj.swigCPtr;
  }

  internal static global::System.Runtime.InteropServices.HandleRef swigRelease(IAudioControlComponentSwigImpl obj) {
    if (obj != null) {
      if (!obj.swigCMemOwn)
        throw new global::System.ApplicationException("Cannot release ownership as memory is not owned");
      global::System.Runtime.InteropServices.HandleRef ptr = obj.swigCPtr;
      obj.swigCMemOwn = false;
      obj.Dispose();
      return ptr;
    } else {
      return new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero);
    }
  }

  ~IAudioControlComponentSwigImpl() {
    Dispose(false);
  }

  public void Dispose() {
    Dispose(true);
    global::System.GC.SuppressFinalize(this);
  }

  protected virtual void Dispose(bool disposing) {
    lock(this) {
      if (swigCPtr.Handle != global::System.IntPtr.Zero) {
        if (swigCMemOwn) {
          swigCMemOwn = false;
          throw new global::System.MethodAccessException("C++ destructor does not have public access");
        }
        swigCPtr = new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero);
      }
    }
  }

  [System.ComponentModel.EditorBrowsable(System.ComponentModel.EditorBrowsableState.Never)]
  global::System.Runtime.InteropServices.HandleRef IAudioControlComponent.GetInterfaceCPtr() {
    return new global::System.Runtime.InteropServices.HandleRef(this, ConnectedSpacesPlatformDotNetPINVOKE.csp_multiplayer_IAudioControlComponentSwigImpl_IAudioControlComponent_GetInterfaceCPtr(swigCPtr.Handle));
  }

  public virtual csp.multiplayer.AudioType GetAudioType() {
    csp.multiplayer.AudioType ret = (csp.multiplayer.AudioType)ConnectedSpacesPlatformDotNetPINVOKE.csp_multiplayer_IAudioControlComponentSwigImpl_GetAudioType(swigCPtr);
    if (ConnectedSpacesPlatformDotNetPINVOKE.SWIGPendingException.Pending) throw ConnectedSpacesPlatformDotNetPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public virtual void SetAudioType(csp.multiplayer.AudioType Value) {
    ConnectedSpacesPlatformDotNetPINVOKE.csp_multiplayer_IAudioControlComponentSwigImpl_SetAudioType(swigCPtr, (int)Value);
    if (ConnectedSpacesPlatformDotNetPINVOKE.SWIGPendingException.Pending) throw ConnectedSpacesPlatformDotNetPINVOKE.SWIGPendingException.Retrieve();
  }

  public virtual float GetAttenuationRadius() {
    float ret = ConnectedSpacesPlatformDotNetPINVOKE.csp_multiplayer_IAudioControlComponentSwigImpl_GetAttenuationRadius(swigCPtr);
    if (ConnectedSpacesPlatformDotNetPINVOKE.SWIGPendingException.Pending) throw ConnectedSpacesPlatformDotNetPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public virtual void SetAttenuationRadius(float Value) {
    ConnectedSpacesPlatformDotNetPINVOKE.csp_multiplayer_IAudioControlComponentSwigImpl_SetAttenuationRadius(swigCPtr, Value);
    if (ConnectedSpacesPlatformDotNetPINVOKE.SWIGPendingException.Pending) throw ConnectedSpacesPlatformDotNetPINVOKE.SWIGPendingException.Retrieve();
  }

  public virtual float GetVolume() {
    float ret = ConnectedSpacesPlatformDotNetPINVOKE.csp_multiplayer_IAudioControlComponentSwigImpl_GetVolume(swigCPtr);
    if (ConnectedSpacesPlatformDotNetPINVOKE.SWIGPendingException.Pending) throw ConnectedSpacesPlatformDotNetPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public virtual void SetVolume(float Value) {
    ConnectedSpacesPlatformDotNetPINVOKE.csp_multiplayer_IAudioControlComponentSwigImpl_SetVolume(swigCPtr, Value);
    if (ConnectedSpacesPlatformDotNetPINVOKE.SWIGPendingException.Pending) throw ConnectedSpacesPlatformDotNetPINVOKE.SWIGPendingException.Retrieve();
  }

}

}
