//------------------------------------------------------------------------------
// <auto-generated />
//
// This file was automatically generated by SWIG (https://www.swig.org).
// Version 4.4.0
//
// Do not make changes to this file unless you know what you are doing - modify
// the SWIG interface file instead.
//------------------------------------------------------------------------------

namespace csp.multiplayer {

#nullable enable

public class IVisibleComponentSwigImpl : IVisibleComponent, global::System.IDisposable {
  private global::System.Runtime.InteropServices.HandleRef swigCPtr;
  protected bool swigCMemOwn;

  internal IVisibleComponentSwigImpl(global::System.IntPtr cPtr, bool cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = new global::System.Runtime.InteropServices.HandleRef(this, cPtr);
  }

  internal static global::System.Runtime.InteropServices.HandleRef getCPtr(IVisibleComponentSwigImpl obj) {
    return (obj == null) ? new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero) : obj.swigCPtr;
  }

  internal static global::System.Runtime.InteropServices.HandleRef swigRelease(IVisibleComponentSwigImpl obj) {
    if (obj != null) {
      if (!obj.swigCMemOwn)
        throw new global::System.ApplicationException("Cannot release ownership as memory is not owned");
      global::System.Runtime.InteropServices.HandleRef ptr = obj.swigCPtr;
      obj.swigCMemOwn = false;
      obj.Dispose();
      return ptr;
    } else {
      return new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero);
    }
  }

  ~IVisibleComponentSwigImpl() {
    Dispose(false);
  }

  public void Dispose() {
    Dispose(true);
    global::System.GC.SuppressFinalize(this);
  }

  protected virtual void Dispose(bool disposing) {
    lock(this) {
      if (swigCPtr.Handle != global::System.IntPtr.Zero) {
        if (swigCMemOwn) {
          swigCMemOwn = false;
          throw new global::System.MethodAccessException("C++ destructor does not have public access");
        }
        swigCPtr = new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero);
      }
    }
  }

  [System.ComponentModel.EditorBrowsable(System.ComponentModel.EditorBrowsableState.Never)]
  global::System.Runtime.InteropServices.HandleRef IVisibleComponent.GetInterfaceCPtr() {
    return new global::System.Runtime.InteropServices.HandleRef(this, ConnectedSpacesPlatformDotNetPINVOKE.csp_multiplayer_IVisibleComponentSwigImpl_IVisibleComponent_GetInterfaceCPtr(swigCPtr.Handle));
  }

  public virtual bool GetIsVisible() {
    bool ret = ConnectedSpacesPlatformDotNetPINVOKE.csp_multiplayer_IVisibleComponentSwigImpl_GetIsVisible(swigCPtr);
    if (ConnectedSpacesPlatformDotNetPINVOKE.SWIGPendingException.Pending) throw ConnectedSpacesPlatformDotNetPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public virtual void SetIsVisible(bool InValue) {
    ConnectedSpacesPlatformDotNetPINVOKE.csp_multiplayer_IVisibleComponentSwigImpl_SetIsVisible(swigCPtr, InValue);
    if (ConnectedSpacesPlatformDotNetPINVOKE.SWIGPendingException.Pending) throw ConnectedSpacesPlatformDotNetPINVOKE.SWIGPendingException.Retrieve();
  }

  public virtual bool GetIsARVisible() {
    bool ret = ConnectedSpacesPlatformDotNetPINVOKE.csp_multiplayer_IVisibleComponentSwigImpl_GetIsARVisible(swigCPtr);
    if (ConnectedSpacesPlatformDotNetPINVOKE.SWIGPendingException.Pending) throw ConnectedSpacesPlatformDotNetPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public virtual void SetIsARVisible(bool InValue) {
    ConnectedSpacesPlatformDotNetPINVOKE.csp_multiplayer_IVisibleComponentSwigImpl_SetIsARVisible(swigCPtr, InValue);
    if (ConnectedSpacesPlatformDotNetPINVOKE.SWIGPendingException.Pending) throw ConnectedSpacesPlatformDotNetPINVOKE.SWIGPendingException.Retrieve();
  }

  public virtual bool GetIsVirtualVisible() {
    bool ret = ConnectedSpacesPlatformDotNetPINVOKE.csp_multiplayer_IVisibleComponentSwigImpl_GetIsVirtualVisible(swigCPtr);
    if (ConnectedSpacesPlatformDotNetPINVOKE.SWIGPendingException.Pending) throw ConnectedSpacesPlatformDotNetPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public virtual void SetIsVirtualVisible(bool InValue) {
    ConnectedSpacesPlatformDotNetPINVOKE.csp_multiplayer_IVisibleComponentSwigImpl_SetIsVirtualVisible(swigCPtr, InValue);
    if (ConnectedSpacesPlatformDotNetPINVOKE.SWIGPendingException.Pending) throw ConnectedSpacesPlatformDotNetPINVOKE.SWIGPendingException.Retrieve();
  }

}

}
