//------------------------------------------------------------------------------
// <auto-generated />
//
// This file was automatically generated by SWIG (https://www.swig.org).
// Version 4.4.0
//
// Do not make changes to this file unless you know what you are doing - modify
// the SWIG interface file instead.
//------------------------------------------------------------------------------

namespace csp.multiplayer {

#nullable enable

public class PortalSpaceComponent : csp.multiplayer.ComponentBase, IEnableableComponent, IPositionComponent {
  private global::System.Runtime.InteropServices.HandleRef swigCPtr;

  internal PortalSpaceComponent(global::System.IntPtr cPtr, bool cMemoryOwn) : base(ConnectedSpacesPlatformDotNetPINVOKE.csp_multiplayer_PortalSpaceComponent_SWIGUpcast(cPtr), cMemoryOwn) {
    swigCPtr = new global::System.Runtime.InteropServices.HandleRef(this, cPtr);
  }

  internal static global::System.Runtime.InteropServices.HandleRef getCPtr(PortalSpaceComponent obj) {
    return (obj == null) ? new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero) : obj.swigCPtr;
  }

  internal static global::System.Runtime.InteropServices.HandleRef swigRelease(PortalSpaceComponent obj) {
    if (obj != null) {
      if (!obj.swigCMemOwn)
        throw new global::System.ApplicationException("Cannot release ownership as memory is not owned");
      global::System.Runtime.InteropServices.HandleRef ptr = obj.swigCPtr;
      obj.swigCMemOwn = false;
      obj.Dispose();
      return ptr;
    } else {
      return new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero);
    }
  }

  protected override void Dispose(bool disposing) {
    lock(this) {
      if (swigCPtr.Handle != global::System.IntPtr.Zero) {
        if (swigCMemOwn) {
          swigCMemOwn = false;
          ConnectedSpacesPlatformDotNetPINVOKE.delete_csp_multiplayer_PortalSpaceComponent(swigCPtr);
        }
        swigCPtr = new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero);
      }
      base.Dispose(disposing);
    }
  }

  [System.ComponentModel.EditorBrowsable(System.ComponentModel.EditorBrowsableState.Never)]
  global::System.Runtime.InteropServices.HandleRef IEnableableComponent.GetInterfaceCPtr() {
    return new global::System.Runtime.InteropServices.HandleRef(this, ConnectedSpacesPlatformDotNetPINVOKE.csp_multiplayer_PortalSpaceComponent_IEnableableComponent_GetInterfaceCPtr(swigCPtr.Handle));
  }

  [System.ComponentModel.EditorBrowsable(System.ComponentModel.EditorBrowsableState.Never)]
  global::System.Runtime.InteropServices.HandleRef IPositionComponent.GetInterfaceCPtr() {
    return new global::System.Runtime.InteropServices.HandleRef(this, ConnectedSpacesPlatformDotNetPINVOKE.csp_multiplayer_PortalSpaceComponent_IPositionComponent_GetInterfaceCPtr(swigCPtr.Handle));
  }


  // Returns null on failure.
  public static csp.multiplayer.PortalSpaceComponent? TryFromBaseCast(csp.multiplayer.ComponentBase baseObj)
  {
    return NativeFromBaseCast(baseObj);
  }

  // Throws ArgumentException on failure.
  public static csp.multiplayer.PortalSpaceComponent FromBaseCast(csp.multiplayer.ComponentBase baseObj)
  {
    csp.multiplayer.PortalSpaceComponent? derived = TryFromBaseCast(baseObj);
    if (derived == null){
      throw new System.ArgumentException("Failed to cast " + nameof(csp.multiplayer.ComponentBase) + " to " + nameof(csp.multiplayer.PortalSpaceComponent), "baseObj");
    }
    return derived;
  }


  public PortalSpaceComponent(csp.common.LogSystem LogSystem, csp.multiplayer.SpaceEntity Parent) : this(ConnectedSpacesPlatformDotNetPINVOKE.new_csp_multiplayer_PortalSpaceComponent((LogSystem != null && csp.common.LogSystem.getCPtr(LogSystem).Handle == global::System.IntPtr.Zero) ? throw new global::System.ObjectDisposedException("LogSystem", "Passed a disposed C# SWIG wrapper (null native handle) to C++. This indicates an object lifecycle bug needing investigation. Note: This does not detect C++-side deletions.") : csp.common.LogSystem.getCPtr(LogSystem), (Parent != null && csp.multiplayer.SpaceEntity.getCPtr(Parent).Handle == global::System.IntPtr.Zero) ? throw new global::System.ObjectDisposedException("Parent", "Passed a disposed C# SWIG wrapper (null native handle) to C++. This indicates an object lifecycle bug needing investigation. Note: This does not detect C++-side deletions.") : csp.multiplayer.SpaceEntity.getCPtr(Parent)), true) {
    if (ConnectedSpacesPlatformDotNetPINVOKE.SWIGPendingException.Pending) throw ConnectedSpacesPlatformDotNetPINVOKE.SWIGPendingException.Retrieve();
  }

  public string GetSpaceId() {
    string ret = ConnectedSpacesPlatformDotNetPINVOKE.csp_multiplayer_PortalSpaceComponent_GetSpaceId(swigCPtr);
    if (ConnectedSpacesPlatformDotNetPINVOKE.SWIGPendingException.Pending) throw ConnectedSpacesPlatformDotNetPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public void SetSpaceId(string Value) {
    ConnectedSpacesPlatformDotNetPINVOKE.csp_multiplayer_PortalSpaceComponent_SetSpaceId(swigCPtr, Value);
    if (ConnectedSpacesPlatformDotNetPINVOKE.SWIGPendingException.Pending) throw ConnectedSpacesPlatformDotNetPINVOKE.SWIGPendingException.Retrieve();
  }

  public virtual csp.common.Vector3 GetPosition() {
  global::System.IntPtr cPtr = ConnectedSpacesPlatformDotNetPINVOKE.csp_multiplayer_PortalSpaceComponent_GetPosition(swigCPtr);
    if (ConnectedSpacesPlatformDotNetPINVOKE.SWIGPendingException.Pending) throw ConnectedSpacesPlatformDotNetPINVOKE.SWIGPendingException.Retrieve();
  csp.common.Vector3 ret = null;
  if (cPtr != global::System.IntPtr.Zero) {
    ret = new csp.common.Vector3(cPtr, false);
    ret.OuterObjectPin = this;
  }
  return ret;
}

  public virtual void SetPosition(csp.common.Vector3 InValue) {
    ConnectedSpacesPlatformDotNetPINVOKE.csp_multiplayer_PortalSpaceComponent_SetPosition(swigCPtr, csp.common.Vector3.getCPtr(InValue));
    if (ConnectedSpacesPlatformDotNetPINVOKE.SWIGPendingException.Pending) throw ConnectedSpacesPlatformDotNetPINVOKE.SWIGPendingException.Retrieve();
  }

  public float GetRadius() {
    float ret = ConnectedSpacesPlatformDotNetPINVOKE.csp_multiplayer_PortalSpaceComponent_GetRadius(swigCPtr);
    if (ConnectedSpacesPlatformDotNetPINVOKE.SWIGPendingException.Pending) throw ConnectedSpacesPlatformDotNetPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public void SetRadius(float Value) {
    ConnectedSpacesPlatformDotNetPINVOKE.csp_multiplayer_PortalSpaceComponent_SetRadius(swigCPtr, Value);
    if (ConnectedSpacesPlatformDotNetPINVOKE.SWIGPendingException.Pending) throw ConnectedSpacesPlatformDotNetPINVOKE.SWIGPendingException.Retrieve();
  }

  public virtual bool GetIsEnabled() {
    bool ret = ConnectedSpacesPlatformDotNetPINVOKE.csp_multiplayer_PortalSpaceComponent_GetIsEnabled(swigCPtr);
    if (ConnectedSpacesPlatformDotNetPINVOKE.SWIGPendingException.Pending) throw ConnectedSpacesPlatformDotNetPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public virtual void SetIsEnabled(bool InValue) {
    ConnectedSpacesPlatformDotNetPINVOKE.csp_multiplayer_PortalSpaceComponent_SetIsEnabled(swigCPtr, InValue);
    if (ConnectedSpacesPlatformDotNetPINVOKE.SWIGPendingException.Pending) throw ConnectedSpacesPlatformDotNetPINVOKE.SWIGPendingException.Retrieve();
  }

  // Any time this object is returned from an outer C++ object via reference, this is set
  // to prevent premature garbage collection causing premature C++ memory deallocation.
  public object OuterObjectPin { private get; set; }

  internal static csp.multiplayer.PortalSpaceComponent NativeFromBaseCast(csp.multiplayer.ComponentBase baseObj) {
    global::System.IntPtr cPtr = ConnectedSpacesPlatformDotNetPINVOKE.csp_multiplayer_PortalSpaceComponent_NativeFromBaseCast((baseObj != null && csp.multiplayer.ComponentBase.getCPtr(baseObj).Handle == global::System.IntPtr.Zero) ? throw new global::System.ObjectDisposedException("baseObj", "Passed a disposed C# SWIG wrapper (null native handle) to C++. This indicates an object lifecycle bug needing investigation. Note: This does not detect C++-side deletions.") : csp.multiplayer.ComponentBase.getCPtr(baseObj));
    csp.multiplayer.PortalSpaceComponent ret = (cPtr == global::System.IntPtr.Zero) ? null : new csp.multiplayer.PortalSpaceComponent(cPtr, false);
    if (ConnectedSpacesPlatformDotNetPINVOKE.SWIGPendingException.Pending) throw ConnectedSpacesPlatformDotNetPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

}

}
