//------------------------------------------------------------------------------
// <auto-generated />
//
// This file was automatically generated by SWIG (https://www.swig.org).
// Version 4.4.0
//
// Do not make changes to this file unless you know what you are doing - modify
// the SWIG interface file instead.
//------------------------------------------------------------------------------

namespace csp.multiplayer {

public enum ReflectionPropertyKeys {
  Name_DEPRECATED,
  ReflectionAssetId,
  AssetCollectionId,
  Position,
  Rotation_NOT_USED,
  Scale,
  ReflectionShape,
  ThirdPartyComponentRef,
  Num
}

}
