//------------------------------------------------------------------------------
// <auto-generated />
//
// This file was automatically generated by SWIG (https://www.swig.org).
// Version 4.4.0
//
// Do not make changes to this file unless you know what you are doing - modify
// the SWIG interface file instead.
//------------------------------------------------------------------------------

namespace csp.multiplayer {

#nullable enable

public class TextSpaceComponent : csp.multiplayer.ComponentBase, ITransformComponent, IPositionComponent, IRotationComponent, IScaleComponent, IVisibleComponent {
  private global::System.Runtime.InteropServices.HandleRef swigCPtr;

  internal TextSpaceComponent(global::System.IntPtr cPtr, bool cMemoryOwn) : base(ConnectedSpacesPlatformDotNetPINVOKE.csp_multiplayer_TextSpaceComponent_SWIGUpcast(cPtr), cMemoryOwn) {
    swigCPtr = new global::System.Runtime.InteropServices.HandleRef(this, cPtr);
  }

  internal static global::System.Runtime.InteropServices.HandleRef getCPtr(TextSpaceComponent obj) {
    return (obj == null) ? new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero) : obj.swigCPtr;
  }

  internal static global::System.Runtime.InteropServices.HandleRef swigRelease(TextSpaceComponent obj) {
    if (obj != null) {
      if (!obj.swigCMemOwn)
        throw new global::System.ApplicationException("Cannot release ownership as memory is not owned");
      global::System.Runtime.InteropServices.HandleRef ptr = obj.swigCPtr;
      obj.swigCMemOwn = false;
      obj.Dispose();
      return ptr;
    } else {
      return new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero);
    }
  }

  protected override void Dispose(bool disposing) {
    lock(this) {
      if (swigCPtr.Handle != global::System.IntPtr.Zero) {
        if (swigCMemOwn) {
          swigCMemOwn = false;
          ConnectedSpacesPlatformDotNetPINVOKE.delete_csp_multiplayer_TextSpaceComponent(swigCPtr);
        }
        swigCPtr = new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero);
      }
      base.Dispose(disposing);
    }
  }

  [System.ComponentModel.EditorBrowsable(System.ComponentModel.EditorBrowsableState.Never)]
  global::System.Runtime.InteropServices.HandleRef ITransformComponent.GetInterfaceCPtr() {
    return new global::System.Runtime.InteropServices.HandleRef(this, ConnectedSpacesPlatformDotNetPINVOKE.csp_multiplayer_TextSpaceComponent_ITransformComponent_GetInterfaceCPtr(swigCPtr.Handle));
  }

  [System.ComponentModel.EditorBrowsable(System.ComponentModel.EditorBrowsableState.Never)]
  global::System.Runtime.InteropServices.HandleRef IPositionComponent.GetInterfaceCPtr() {
    return new global::System.Runtime.InteropServices.HandleRef(this, ConnectedSpacesPlatformDotNetPINVOKE.csp_multiplayer_TextSpaceComponent_IPositionComponent_GetInterfaceCPtr(swigCPtr.Handle));
  }

  [System.ComponentModel.EditorBrowsable(System.ComponentModel.EditorBrowsableState.Never)]
  global::System.Runtime.InteropServices.HandleRef IRotationComponent.GetInterfaceCPtr() {
    return new global::System.Runtime.InteropServices.HandleRef(this, ConnectedSpacesPlatformDotNetPINVOKE.csp_multiplayer_TextSpaceComponent_IRotationComponent_GetInterfaceCPtr(swigCPtr.Handle));
  }

  [System.ComponentModel.EditorBrowsable(System.ComponentModel.EditorBrowsableState.Never)]
  global::System.Runtime.InteropServices.HandleRef IScaleComponent.GetInterfaceCPtr() {
    return new global::System.Runtime.InteropServices.HandleRef(this, ConnectedSpacesPlatformDotNetPINVOKE.csp_multiplayer_TextSpaceComponent_IScaleComponent_GetInterfaceCPtr(swigCPtr.Handle));
  }

  [System.ComponentModel.EditorBrowsable(System.ComponentModel.EditorBrowsableState.Never)]
  global::System.Runtime.InteropServices.HandleRef IVisibleComponent.GetInterfaceCPtr() {
    return new global::System.Runtime.InteropServices.HandleRef(this, ConnectedSpacesPlatformDotNetPINVOKE.csp_multiplayer_TextSpaceComponent_IVisibleComponent_GetInterfaceCPtr(swigCPtr.Handle));
  }


  // Returns null on failure.
  public static csp.multiplayer.TextSpaceComponent? TryFromBaseCast(csp.multiplayer.ComponentBase baseObj)
  {
    return NativeFromBaseCast(baseObj);
  }

  // Throws ArgumentException on failure.
  public static csp.multiplayer.TextSpaceComponent FromBaseCast(csp.multiplayer.ComponentBase baseObj)
  {
    csp.multiplayer.TextSpaceComponent? derived = TryFromBaseCast(baseObj);
    if (derived == null){
      throw new System.ArgumentException("Failed to cast " + nameof(csp.multiplayer.ComponentBase) + " to " + nameof(csp.multiplayer.TextSpaceComponent), "baseObj");
    }
    return derived;
  }


  public TextSpaceComponent(csp.common.LogSystem LogSystem, csp.multiplayer.SpaceEntity Parent) : this(ConnectedSpacesPlatformDotNetPINVOKE.new_csp_multiplayer_TextSpaceComponent(csp.common.LogSystem.getCPtr(LogSystem), csp.multiplayer.SpaceEntity.getCPtr(Parent)), true) {
    if (ConnectedSpacesPlatformDotNetPINVOKE.SWIGPendingException.Pending) throw ConnectedSpacesPlatformDotNetPINVOKE.SWIGPendingException.Retrieve();
  }

  public string GetText() {
    string ret = ConnectedSpacesPlatformDotNetPINVOKE.csp_multiplayer_TextSpaceComponent_GetText(swigCPtr);
    if (ConnectedSpacesPlatformDotNetPINVOKE.SWIGPendingException.Pending) throw ConnectedSpacesPlatformDotNetPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public void SetText(string Value) {
    ConnectedSpacesPlatformDotNetPINVOKE.csp_multiplayer_TextSpaceComponent_SetText(swigCPtr, Value);
    if (ConnectedSpacesPlatformDotNetPINVOKE.SWIGPendingException.Pending) throw ConnectedSpacesPlatformDotNetPINVOKE.SWIGPendingException.Retrieve();
  }

  public csp.common.Vector3 GetTextColor() {
  global::System.IntPtr cPtr = ConnectedSpacesPlatformDotNetPINVOKE.csp_multiplayer_TextSpaceComponent_GetTextColor(swigCPtr);
    if (ConnectedSpacesPlatformDotNetPINVOKE.SWIGPendingException.Pending) throw ConnectedSpacesPlatformDotNetPINVOKE.SWIGPendingException.Retrieve();
  csp.common.Vector3 ret = null;
  if (cPtr != global::System.IntPtr.Zero) {
    ret = new csp.common.Vector3(cPtr, false);
    ret.OuterObjectPin = this;
  }
  return ret;
}

  public void SetTextColor(csp.common.Vector3 Value) {
    ConnectedSpacesPlatformDotNetPINVOKE.csp_multiplayer_TextSpaceComponent_SetTextColor(swigCPtr, csp.common.Vector3.getCPtr(Value));
    if (ConnectedSpacesPlatformDotNetPINVOKE.SWIGPendingException.Pending) throw ConnectedSpacesPlatformDotNetPINVOKE.SWIGPendingException.Retrieve();
  }

  public csp.common.Vector3 GetBackgroundColor() {
  global::System.IntPtr cPtr = ConnectedSpacesPlatformDotNetPINVOKE.csp_multiplayer_TextSpaceComponent_GetBackgroundColor(swigCPtr);
    if (ConnectedSpacesPlatformDotNetPINVOKE.SWIGPendingException.Pending) throw ConnectedSpacesPlatformDotNetPINVOKE.SWIGPendingException.Retrieve();
  csp.common.Vector3 ret = null;
  if (cPtr != global::System.IntPtr.Zero) {
    ret = new csp.common.Vector3(cPtr, false);
    ret.OuterObjectPin = this;
  }
  return ret;
}

  public void SetBackgroundColor(csp.common.Vector3 Value) {
    ConnectedSpacesPlatformDotNetPINVOKE.csp_multiplayer_TextSpaceComponent_SetBackgroundColor(swigCPtr, csp.common.Vector3.getCPtr(Value));
    if (ConnectedSpacesPlatformDotNetPINVOKE.SWIGPendingException.Pending) throw ConnectedSpacesPlatformDotNetPINVOKE.SWIGPendingException.Retrieve();
  }

  public bool GetIsBackgroundVisible() {
    bool ret = ConnectedSpacesPlatformDotNetPINVOKE.csp_multiplayer_TextSpaceComponent_GetIsBackgroundVisible(swigCPtr);
    if (ConnectedSpacesPlatformDotNetPINVOKE.SWIGPendingException.Pending) throw ConnectedSpacesPlatformDotNetPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public void SetIsBackgroundVisible(bool InValue) {
    ConnectedSpacesPlatformDotNetPINVOKE.csp_multiplayer_TextSpaceComponent_SetIsBackgroundVisible(swigCPtr, InValue);
    if (ConnectedSpacesPlatformDotNetPINVOKE.SWIGPendingException.Pending) throw ConnectedSpacesPlatformDotNetPINVOKE.SWIGPendingException.Retrieve();
  }

  public float GetWidth() {
    float ret = ConnectedSpacesPlatformDotNetPINVOKE.csp_multiplayer_TextSpaceComponent_GetWidth(swigCPtr);
    if (ConnectedSpacesPlatformDotNetPINVOKE.SWIGPendingException.Pending) throw ConnectedSpacesPlatformDotNetPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public void SetWidth(float InValue) {
    ConnectedSpacesPlatformDotNetPINVOKE.csp_multiplayer_TextSpaceComponent_SetWidth(swigCPtr, InValue);
    if (ConnectedSpacesPlatformDotNetPINVOKE.SWIGPendingException.Pending) throw ConnectedSpacesPlatformDotNetPINVOKE.SWIGPendingException.Retrieve();
  }

  public float GetHeight() {
    float ret = ConnectedSpacesPlatformDotNetPINVOKE.csp_multiplayer_TextSpaceComponent_GetHeight(swigCPtr);
    if (ConnectedSpacesPlatformDotNetPINVOKE.SWIGPendingException.Pending) throw ConnectedSpacesPlatformDotNetPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public void SetHeight(float InValue) {
    ConnectedSpacesPlatformDotNetPINVOKE.csp_multiplayer_TextSpaceComponent_SetHeight(swigCPtr, InValue);
    if (ConnectedSpacesPlatformDotNetPINVOKE.SWIGPendingException.Pending) throw ConnectedSpacesPlatformDotNetPINVOKE.SWIGPendingException.Retrieve();
  }

  public virtual csp.common.Vector3 GetPosition() {
  global::System.IntPtr cPtr = ConnectedSpacesPlatformDotNetPINVOKE.csp_multiplayer_TextSpaceComponent_GetPosition(swigCPtr);
    if (ConnectedSpacesPlatformDotNetPINVOKE.SWIGPendingException.Pending) throw ConnectedSpacesPlatformDotNetPINVOKE.SWIGPendingException.Retrieve();
  csp.common.Vector3 ret = null;
  if (cPtr != global::System.IntPtr.Zero) {
    ret = new csp.common.Vector3(cPtr, false);
    ret.OuterObjectPin = this;
  }
  return ret;
}

  public virtual void SetPosition(csp.common.Vector3 InValue) {
    ConnectedSpacesPlatformDotNetPINVOKE.csp_multiplayer_TextSpaceComponent_SetPosition(swigCPtr, csp.common.Vector3.getCPtr(InValue));
    if (ConnectedSpacesPlatformDotNetPINVOKE.SWIGPendingException.Pending) throw ConnectedSpacesPlatformDotNetPINVOKE.SWIGPendingException.Retrieve();
  }

  public virtual csp.common.Vector4 GetRotation() {
  global::System.IntPtr cPtr = ConnectedSpacesPlatformDotNetPINVOKE.csp_multiplayer_TextSpaceComponent_GetRotation(swigCPtr);
    if (ConnectedSpacesPlatformDotNetPINVOKE.SWIGPendingException.Pending) throw ConnectedSpacesPlatformDotNetPINVOKE.SWIGPendingException.Retrieve();
  csp.common.Vector4 ret = null;
  if (cPtr != global::System.IntPtr.Zero) {
    ret = new csp.common.Vector4(cPtr, false);
    ret.OuterObjectPin = this;
  }
  return ret;
}

  public virtual void SetRotation(csp.common.Vector4 InValue) {
    ConnectedSpacesPlatformDotNetPINVOKE.csp_multiplayer_TextSpaceComponent_SetRotation(swigCPtr, csp.common.Vector4.getCPtr(InValue));
    if (ConnectedSpacesPlatformDotNetPINVOKE.SWIGPendingException.Pending) throw ConnectedSpacesPlatformDotNetPINVOKE.SWIGPendingException.Retrieve();
  }

  public virtual csp.common.Vector3 GetScale() {
  global::System.IntPtr cPtr = ConnectedSpacesPlatformDotNetPINVOKE.csp_multiplayer_TextSpaceComponent_GetScale(swigCPtr);
    if (ConnectedSpacesPlatformDotNetPINVOKE.SWIGPendingException.Pending) throw ConnectedSpacesPlatformDotNetPINVOKE.SWIGPendingException.Retrieve();
  csp.common.Vector3 ret = null;
  if (cPtr != global::System.IntPtr.Zero) {
    ret = new csp.common.Vector3(cPtr, false);
    ret.OuterObjectPin = this;
  }
  return ret;
}

  public virtual void SetScale(csp.common.Vector3 InValue) {
    ConnectedSpacesPlatformDotNetPINVOKE.csp_multiplayer_TextSpaceComponent_SetScale(swigCPtr, csp.common.Vector3.getCPtr(InValue));
    if (ConnectedSpacesPlatformDotNetPINVOKE.SWIGPendingException.Pending) throw ConnectedSpacesPlatformDotNetPINVOKE.SWIGPendingException.Retrieve();
  }

  public virtual csp.multiplayer.SpaceTransform GetTransform() {
    csp.multiplayer.SpaceTransform ret = new csp.multiplayer.SpaceTransform(ConnectedSpacesPlatformDotNetPINVOKE.csp_multiplayer_TextSpaceComponent_GetTransform(swigCPtr), true);
    if (ConnectedSpacesPlatformDotNetPINVOKE.SWIGPendingException.Pending) throw ConnectedSpacesPlatformDotNetPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public virtual void SetTransform(csp.multiplayer.SpaceTransform InValue) {
    ConnectedSpacesPlatformDotNetPINVOKE.csp_multiplayer_TextSpaceComponent_SetTransform(swigCPtr, csp.multiplayer.SpaceTransform.getCPtr(InValue));
    if (ConnectedSpacesPlatformDotNetPINVOKE.SWIGPendingException.Pending) throw ConnectedSpacesPlatformDotNetPINVOKE.SWIGPendingException.Retrieve();
  }

  public csp.multiplayer.BillboardMode GetBillboardMode() {
    csp.multiplayer.BillboardMode ret = (csp.multiplayer.BillboardMode)ConnectedSpacesPlatformDotNetPINVOKE.csp_multiplayer_TextSpaceComponent_GetBillboardMode(swigCPtr);
    if (ConnectedSpacesPlatformDotNetPINVOKE.SWIGPendingException.Pending) throw ConnectedSpacesPlatformDotNetPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public void SetBillboardMode(csp.multiplayer.BillboardMode billboardMode) {
    ConnectedSpacesPlatformDotNetPINVOKE.csp_multiplayer_TextSpaceComponent_SetBillboardMode(swigCPtr, (int)billboardMode);
    if (ConnectedSpacesPlatformDotNetPINVOKE.SWIGPendingException.Pending) throw ConnectedSpacesPlatformDotNetPINVOKE.SWIGPendingException.Retrieve();
  }

  public virtual bool GetIsVisible() {
    bool ret = ConnectedSpacesPlatformDotNetPINVOKE.csp_multiplayer_TextSpaceComponent_GetIsVisible(swigCPtr);
    if (ConnectedSpacesPlatformDotNetPINVOKE.SWIGPendingException.Pending) throw ConnectedSpacesPlatformDotNetPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public virtual void SetIsVisible(bool InValue) {
    ConnectedSpacesPlatformDotNetPINVOKE.csp_multiplayer_TextSpaceComponent_SetIsVisible(swigCPtr, InValue);
    if (ConnectedSpacesPlatformDotNetPINVOKE.SWIGPendingException.Pending) throw ConnectedSpacesPlatformDotNetPINVOKE.SWIGPendingException.Retrieve();
  }

  public virtual bool GetIsARVisible() {
    bool ret = ConnectedSpacesPlatformDotNetPINVOKE.csp_multiplayer_TextSpaceComponent_GetIsARVisible(swigCPtr);
    if (ConnectedSpacesPlatformDotNetPINVOKE.SWIGPendingException.Pending) throw ConnectedSpacesPlatformDotNetPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public virtual void SetIsARVisible(bool InValue) {
    ConnectedSpacesPlatformDotNetPINVOKE.csp_multiplayer_TextSpaceComponent_SetIsARVisible(swigCPtr, InValue);
    if (ConnectedSpacesPlatformDotNetPINVOKE.SWIGPendingException.Pending) throw ConnectedSpacesPlatformDotNetPINVOKE.SWIGPendingException.Retrieve();
  }

  public virtual bool GetIsVirtualVisible() {
    bool ret = ConnectedSpacesPlatformDotNetPINVOKE.csp_multiplayer_TextSpaceComponent_GetIsVirtualVisible(swigCPtr);
    if (ConnectedSpacesPlatformDotNetPINVOKE.SWIGPendingException.Pending) throw ConnectedSpacesPlatformDotNetPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public virtual void SetIsVirtualVisible(bool InValue) {
    ConnectedSpacesPlatformDotNetPINVOKE.csp_multiplayer_TextSpaceComponent_SetIsVirtualVisible(swigCPtr, InValue);
    if (ConnectedSpacesPlatformDotNetPINVOKE.SWIGPendingException.Pending) throw ConnectedSpacesPlatformDotNetPINVOKE.SWIGPendingException.Retrieve();
  }

  // Any time this object is returned from an outer C++ object via reference, this is set
  // to prevent premature garbage collection causing premature C++ memory deallocation.
  public object OuterObjectPin { private get; set; }

  internal static csp.multiplayer.TextSpaceComponent NativeFromBaseCast(csp.multiplayer.ComponentBase baseObj) {
    global::System.IntPtr cPtr = ConnectedSpacesPlatformDotNetPINVOKE.csp_multiplayer_TextSpaceComponent_NativeFromBaseCast(csp.multiplayer.ComponentBase.getCPtr(baseObj));
    csp.multiplayer.TextSpaceComponent ret = (cPtr == global::System.IntPtr.Zero) ? null : new csp.multiplayer.TextSpaceComponent(cPtr, false);
    if (ConnectedSpacesPlatformDotNetPINVOKE.SWIGPendingException.Pending) throw ConnectedSpacesPlatformDotNetPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

}

}
