//------------------------------------------------------------------------------
// <auto-generated />
//
// This file was automatically generated by SWIG (https://www.swig.org).
// Version 4.4.0
//
// Do not make changes to this file unless you know what you are doing - modify
// the SWIG interface file instead.
//------------------------------------------------------------------------------

namespace csp.multiplayer {

#nullable enable

public class VideoPlayerSpaceComponent : csp.multiplayer.ComponentBase, IAudioControlComponent, IEnableableComponent, ITransformComponent, IPositionComponent, IRotationComponent, IScaleComponent, IVisibleComponent {
  private global::System.Runtime.InteropServices.HandleRef swigCPtr;

  internal VideoPlayerSpaceComponent(global::System.IntPtr cPtr, bool cMemoryOwn) : base(ConnectedSpacesPlatformDotNetPINVOKE.csp_multiplayer_VideoPlayerSpaceComponent_SWIGUpcast(cPtr), cMemoryOwn) {
    swigCPtr = new global::System.Runtime.InteropServices.HandleRef(this, cPtr);
  }

  internal static global::System.Runtime.InteropServices.HandleRef getCPtr(VideoPlayerSpaceComponent obj) {
    return (obj == null) ? new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero) : obj.swigCPtr;
  }

  internal static global::System.Runtime.InteropServices.HandleRef swigRelease(VideoPlayerSpaceComponent obj) {
    if (obj != null) {
      if (!obj.swigCMemOwn)
        throw new global::System.ApplicationException("Cannot release ownership as memory is not owned");
      global::System.Runtime.InteropServices.HandleRef ptr = obj.swigCPtr;
      obj.swigCMemOwn = false;
      obj.Dispose();
      return ptr;
    } else {
      return new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero);
    }
  }

  protected override void Dispose(bool disposing) {
    lock(this) {
      if (swigCPtr.Handle != global::System.IntPtr.Zero) {
        if (swigCMemOwn) {
          swigCMemOwn = false;
          ConnectedSpacesPlatformDotNetPINVOKE.delete_csp_multiplayer_VideoPlayerSpaceComponent(swigCPtr);
        }
        swigCPtr = new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero);
      }
      base.Dispose(disposing);
    }
  }

  [System.ComponentModel.EditorBrowsable(System.ComponentModel.EditorBrowsableState.Never)]
  global::System.Runtime.InteropServices.HandleRef IAudioControlComponent.GetInterfaceCPtr() {
    return new global::System.Runtime.InteropServices.HandleRef(this, ConnectedSpacesPlatformDotNetPINVOKE.csp_multiplayer_VideoPlayerSpaceComponent_IAudioControlComponent_GetInterfaceCPtr(swigCPtr.Handle));
  }

  [System.ComponentModel.EditorBrowsable(System.ComponentModel.EditorBrowsableState.Never)]
  global::System.Runtime.InteropServices.HandleRef IEnableableComponent.GetInterfaceCPtr() {
    return new global::System.Runtime.InteropServices.HandleRef(this, ConnectedSpacesPlatformDotNetPINVOKE.csp_multiplayer_VideoPlayerSpaceComponent_IEnableableComponent_GetInterfaceCPtr(swigCPtr.Handle));
  }

  [System.ComponentModel.EditorBrowsable(System.ComponentModel.EditorBrowsableState.Never)]
  global::System.Runtime.InteropServices.HandleRef ITransformComponent.GetInterfaceCPtr() {
    return new global::System.Runtime.InteropServices.HandleRef(this, ConnectedSpacesPlatformDotNetPINVOKE.csp_multiplayer_VideoPlayerSpaceComponent_ITransformComponent_GetInterfaceCPtr(swigCPtr.Handle));
  }

  [System.ComponentModel.EditorBrowsable(System.ComponentModel.EditorBrowsableState.Never)]
  global::System.Runtime.InteropServices.HandleRef IPositionComponent.GetInterfaceCPtr() {
    return new global::System.Runtime.InteropServices.HandleRef(this, ConnectedSpacesPlatformDotNetPINVOKE.csp_multiplayer_VideoPlayerSpaceComponent_IPositionComponent_GetInterfaceCPtr(swigCPtr.Handle));
  }

  [System.ComponentModel.EditorBrowsable(System.ComponentModel.EditorBrowsableState.Never)]
  global::System.Runtime.InteropServices.HandleRef IRotationComponent.GetInterfaceCPtr() {
    return new global::System.Runtime.InteropServices.HandleRef(this, ConnectedSpacesPlatformDotNetPINVOKE.csp_multiplayer_VideoPlayerSpaceComponent_IRotationComponent_GetInterfaceCPtr(swigCPtr.Handle));
  }

  [System.ComponentModel.EditorBrowsable(System.ComponentModel.EditorBrowsableState.Never)]
  global::System.Runtime.InteropServices.HandleRef IScaleComponent.GetInterfaceCPtr() {
    return new global::System.Runtime.InteropServices.HandleRef(this, ConnectedSpacesPlatformDotNetPINVOKE.csp_multiplayer_VideoPlayerSpaceComponent_IScaleComponent_GetInterfaceCPtr(swigCPtr.Handle));
  }

  [System.ComponentModel.EditorBrowsable(System.ComponentModel.EditorBrowsableState.Never)]
  global::System.Runtime.InteropServices.HandleRef IVisibleComponent.GetInterfaceCPtr() {
    return new global::System.Runtime.InteropServices.HandleRef(this, ConnectedSpacesPlatformDotNetPINVOKE.csp_multiplayer_VideoPlayerSpaceComponent_IVisibleComponent_GetInterfaceCPtr(swigCPtr.Handle));
  }


  // Returns null on failure.
  public static csp.multiplayer.VideoPlayerSpaceComponent? TryFromBaseCast(csp.multiplayer.ComponentBase baseObj)
  {
    return NativeFromBaseCast(baseObj);
  }

  // Throws ArgumentException on failure.
  public static csp.multiplayer.VideoPlayerSpaceComponent FromBaseCast(csp.multiplayer.ComponentBase baseObj)
  {
    csp.multiplayer.VideoPlayerSpaceComponent? derived = TryFromBaseCast(baseObj);
    if (derived == null){
      throw new System.ArgumentException("Failed to cast " + nameof(csp.multiplayer.ComponentBase) + " to " + nameof(csp.multiplayer.VideoPlayerSpaceComponent), "baseObj");
    }
    return derived;
  }


  public VideoPlayerSpaceComponent(csp.common.LogSystem LogSystem, csp.multiplayer.SpaceEntity Parent) : this(ConnectedSpacesPlatformDotNetPINVOKE.new_csp_multiplayer_VideoPlayerSpaceComponent((LogSystem != null && csp.common.LogSystem.getCPtr(LogSystem).Handle == global::System.IntPtr.Zero) ? throw new global::System.ObjectDisposedException("LogSystem", "Passed a disposed C# SWIG wrapper (null native handle) to C++. This indicates an object lifecycle bug needing investigation. Note: This does not detect C++-side deletions.") : csp.common.LogSystem.getCPtr(LogSystem), (Parent != null && csp.multiplayer.SpaceEntity.getCPtr(Parent).Handle == global::System.IntPtr.Zero) ? throw new global::System.ObjectDisposedException("Parent", "Passed a disposed C# SWIG wrapper (null native handle) to C++. This indicates an object lifecycle bug needing investigation. Note: This does not detect C++-side deletions.") : csp.multiplayer.SpaceEntity.getCPtr(Parent)), true) {
    if (ConnectedSpacesPlatformDotNetPINVOKE.SWIGPendingException.Pending) throw ConnectedSpacesPlatformDotNetPINVOKE.SWIGPendingException.Retrieve();
  }

  public string GetName() {
    string ret = ConnectedSpacesPlatformDotNetPINVOKE.csp_multiplayer_VideoPlayerSpaceComponent_GetName(swigCPtr);
    if (ConnectedSpacesPlatformDotNetPINVOKE.SWIGPendingException.Pending) throw ConnectedSpacesPlatformDotNetPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public void SetName(string Value) {
    ConnectedSpacesPlatformDotNetPINVOKE.csp_multiplayer_VideoPlayerSpaceComponent_SetName(swigCPtr, Value);
    if (ConnectedSpacesPlatformDotNetPINVOKE.SWIGPendingException.Pending) throw ConnectedSpacesPlatformDotNetPINVOKE.SWIGPendingException.Retrieve();
  }

  public string GetVideoAssetId() {
    string ret = ConnectedSpacesPlatformDotNetPINVOKE.csp_multiplayer_VideoPlayerSpaceComponent_GetVideoAssetId(swigCPtr);
    if (ConnectedSpacesPlatformDotNetPINVOKE.SWIGPendingException.Pending) throw ConnectedSpacesPlatformDotNetPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public void SetVideoAssetId(string Value) {
    ConnectedSpacesPlatformDotNetPINVOKE.csp_multiplayer_VideoPlayerSpaceComponent_SetVideoAssetId(swigCPtr, Value);
    if (ConnectedSpacesPlatformDotNetPINVOKE.SWIGPendingException.Pending) throw ConnectedSpacesPlatformDotNetPINVOKE.SWIGPendingException.Retrieve();
  }

  public string GetVideoAssetURL() {
    string ret = ConnectedSpacesPlatformDotNetPINVOKE.csp_multiplayer_VideoPlayerSpaceComponent_GetVideoAssetURL(swigCPtr);
    if (ConnectedSpacesPlatformDotNetPINVOKE.SWIGPendingException.Pending) throw ConnectedSpacesPlatformDotNetPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public void SetVideoAssetURL(string Value) {
    ConnectedSpacesPlatformDotNetPINVOKE.csp_multiplayer_VideoPlayerSpaceComponent_SetVideoAssetURL(swigCPtr, Value);
    if (ConnectedSpacesPlatformDotNetPINVOKE.SWIGPendingException.Pending) throw ConnectedSpacesPlatformDotNetPINVOKE.SWIGPendingException.Retrieve();
  }

  public string GetAssetCollectionId() {
    string ret = ConnectedSpacesPlatformDotNetPINVOKE.csp_multiplayer_VideoPlayerSpaceComponent_GetAssetCollectionId(swigCPtr);
    if (ConnectedSpacesPlatformDotNetPINVOKE.SWIGPendingException.Pending) throw ConnectedSpacesPlatformDotNetPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public void SetAssetCollectionId(string Value) {
    ConnectedSpacesPlatformDotNetPINVOKE.csp_multiplayer_VideoPlayerSpaceComponent_SetAssetCollectionId(swigCPtr, Value);
    if (ConnectedSpacesPlatformDotNetPINVOKE.SWIGPendingException.Pending) throw ConnectedSpacesPlatformDotNetPINVOKE.SWIGPendingException.Retrieve();
  }

  public virtual csp.common.Vector3 GetPosition() {
  global::System.IntPtr cPtr = ConnectedSpacesPlatformDotNetPINVOKE.csp_multiplayer_VideoPlayerSpaceComponent_GetPosition(swigCPtr);
    if (ConnectedSpacesPlatformDotNetPINVOKE.SWIGPendingException.Pending) throw ConnectedSpacesPlatformDotNetPINVOKE.SWIGPendingException.Retrieve();
  csp.common.Vector3 ret = null;
  if (cPtr != global::System.IntPtr.Zero) {
    ret = new csp.common.Vector3(cPtr, false);
    ret.OuterObjectPin = this;
  }
  return ret;
}

  public virtual void SetPosition(csp.common.Vector3 InValue) {
    ConnectedSpacesPlatformDotNetPINVOKE.csp_multiplayer_VideoPlayerSpaceComponent_SetPosition(swigCPtr, csp.common.Vector3.getCPtr(InValue));
    if (ConnectedSpacesPlatformDotNetPINVOKE.SWIGPendingException.Pending) throw ConnectedSpacesPlatformDotNetPINVOKE.SWIGPendingException.Retrieve();
  }

  public virtual csp.common.Vector4 GetRotation() {
  global::System.IntPtr cPtr = ConnectedSpacesPlatformDotNetPINVOKE.csp_multiplayer_VideoPlayerSpaceComponent_GetRotation(swigCPtr);
    if (ConnectedSpacesPlatformDotNetPINVOKE.SWIGPendingException.Pending) throw ConnectedSpacesPlatformDotNetPINVOKE.SWIGPendingException.Retrieve();
  csp.common.Vector4 ret = null;
  if (cPtr != global::System.IntPtr.Zero) {
    ret = new csp.common.Vector4(cPtr, false);
    ret.OuterObjectPin = this;
  }
  return ret;
}

  public virtual void SetRotation(csp.common.Vector4 InValue) {
    ConnectedSpacesPlatformDotNetPINVOKE.csp_multiplayer_VideoPlayerSpaceComponent_SetRotation(swigCPtr, csp.common.Vector4.getCPtr(InValue));
    if (ConnectedSpacesPlatformDotNetPINVOKE.SWIGPendingException.Pending) throw ConnectedSpacesPlatformDotNetPINVOKE.SWIGPendingException.Retrieve();
  }

  public virtual csp.common.Vector3 GetScale() {
  global::System.IntPtr cPtr = ConnectedSpacesPlatformDotNetPINVOKE.csp_multiplayer_VideoPlayerSpaceComponent_GetScale(swigCPtr);
    if (ConnectedSpacesPlatformDotNetPINVOKE.SWIGPendingException.Pending) throw ConnectedSpacesPlatformDotNetPINVOKE.SWIGPendingException.Retrieve();
  csp.common.Vector3 ret = null;
  if (cPtr != global::System.IntPtr.Zero) {
    ret = new csp.common.Vector3(cPtr, false);
    ret.OuterObjectPin = this;
  }
  return ret;
}

  public virtual void SetScale(csp.common.Vector3 InValue) {
    ConnectedSpacesPlatformDotNetPINVOKE.csp_multiplayer_VideoPlayerSpaceComponent_SetScale(swigCPtr, csp.common.Vector3.getCPtr(InValue));
    if (ConnectedSpacesPlatformDotNetPINVOKE.SWIGPendingException.Pending) throw ConnectedSpacesPlatformDotNetPINVOKE.SWIGPendingException.Retrieve();
  }

  public virtual csp.multiplayer.SpaceTransform GetTransform() {
    csp.multiplayer.SpaceTransform ret = new csp.multiplayer.SpaceTransform(ConnectedSpacesPlatformDotNetPINVOKE.csp_multiplayer_VideoPlayerSpaceComponent_GetTransform(swigCPtr), true);
    if (ConnectedSpacesPlatformDotNetPINVOKE.SWIGPendingException.Pending) throw ConnectedSpacesPlatformDotNetPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public virtual void SetTransform(csp.multiplayer.SpaceTransform InValue) {
    ConnectedSpacesPlatformDotNetPINVOKE.csp_multiplayer_VideoPlayerSpaceComponent_SetTransform(swigCPtr, csp.multiplayer.SpaceTransform.getCPtr(InValue));
    if (ConnectedSpacesPlatformDotNetPINVOKE.SWIGPendingException.Pending) throw ConnectedSpacesPlatformDotNetPINVOKE.SWIGPendingException.Retrieve();
  }

  public bool GetIsStateShared() {
    bool ret = ConnectedSpacesPlatformDotNetPINVOKE.csp_multiplayer_VideoPlayerSpaceComponent_GetIsStateShared(swigCPtr);
    if (ConnectedSpacesPlatformDotNetPINVOKE.SWIGPendingException.Pending) throw ConnectedSpacesPlatformDotNetPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public void SetIsStateShared(bool Value) {
    ConnectedSpacesPlatformDotNetPINVOKE.csp_multiplayer_VideoPlayerSpaceComponent_SetIsStateShared(swigCPtr, Value);
    if (ConnectedSpacesPlatformDotNetPINVOKE.SWIGPendingException.Pending) throw ConnectedSpacesPlatformDotNetPINVOKE.SWIGPendingException.Retrieve();
  }

  public bool GetIsAutoPlay() {
    bool ret = ConnectedSpacesPlatformDotNetPINVOKE.csp_multiplayer_VideoPlayerSpaceComponent_GetIsAutoPlay(swigCPtr);
    if (ConnectedSpacesPlatformDotNetPINVOKE.SWIGPendingException.Pending) throw ConnectedSpacesPlatformDotNetPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public void SetIsAutoPlay(bool Value) {
    ConnectedSpacesPlatformDotNetPINVOKE.csp_multiplayer_VideoPlayerSpaceComponent_SetIsAutoPlay(swigCPtr, Value);
    if (ConnectedSpacesPlatformDotNetPINVOKE.SWIGPendingException.Pending) throw ConnectedSpacesPlatformDotNetPINVOKE.SWIGPendingException.Retrieve();
  }

  public bool GetIsLoopPlayback() {
    bool ret = ConnectedSpacesPlatformDotNetPINVOKE.csp_multiplayer_VideoPlayerSpaceComponent_GetIsLoopPlayback(swigCPtr);
    if (ConnectedSpacesPlatformDotNetPINVOKE.SWIGPendingException.Pending) throw ConnectedSpacesPlatformDotNetPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public void SetIsLoopPlayback(bool Value) {
    ConnectedSpacesPlatformDotNetPINVOKE.csp_multiplayer_VideoPlayerSpaceComponent_SetIsLoopPlayback(swigCPtr, Value);
    if (ConnectedSpacesPlatformDotNetPINVOKE.SWIGPendingException.Pending) throw ConnectedSpacesPlatformDotNetPINVOKE.SWIGPendingException.Retrieve();
  }

  public bool GetIsAutoResize() {
    bool ret = ConnectedSpacesPlatformDotNetPINVOKE.csp_multiplayer_VideoPlayerSpaceComponent_GetIsAutoResize(swigCPtr);
    if (ConnectedSpacesPlatformDotNetPINVOKE.SWIGPendingException.Pending) throw ConnectedSpacesPlatformDotNetPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public void SetIsAutoResize(bool Value) {
    ConnectedSpacesPlatformDotNetPINVOKE.csp_multiplayer_VideoPlayerSpaceComponent_SetIsAutoResize(swigCPtr, Value);
    if (ConnectedSpacesPlatformDotNetPINVOKE.SWIGPendingException.Pending) throw ConnectedSpacesPlatformDotNetPINVOKE.SWIGPendingException.Retrieve();
  }

  public csp.multiplayer.VideoPlayerPlaybackState GetPlaybackState() {
    csp.multiplayer.VideoPlayerPlaybackState ret = (csp.multiplayer.VideoPlayerPlaybackState)ConnectedSpacesPlatformDotNetPINVOKE.csp_multiplayer_VideoPlayerSpaceComponent_GetPlaybackState(swigCPtr);
    if (ConnectedSpacesPlatformDotNetPINVOKE.SWIGPendingException.Pending) throw ConnectedSpacesPlatformDotNetPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public void SetPlaybackState(csp.multiplayer.VideoPlayerPlaybackState Value) {
    ConnectedSpacesPlatformDotNetPINVOKE.csp_multiplayer_VideoPlayerSpaceComponent_SetPlaybackState(swigCPtr, (int)Value);
    if (ConnectedSpacesPlatformDotNetPINVOKE.SWIGPendingException.Pending) throw ConnectedSpacesPlatformDotNetPINVOKE.SWIGPendingException.Retrieve();
  }

  public float GetCurrentPlayheadPosition() {
    float ret = ConnectedSpacesPlatformDotNetPINVOKE.csp_multiplayer_VideoPlayerSpaceComponent_GetCurrentPlayheadPosition(swigCPtr);
    if (ConnectedSpacesPlatformDotNetPINVOKE.SWIGPendingException.Pending) throw ConnectedSpacesPlatformDotNetPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public void SetCurrentPlayheadPosition(float Value) {
    ConnectedSpacesPlatformDotNetPINVOKE.csp_multiplayer_VideoPlayerSpaceComponent_SetCurrentPlayheadPosition(swigCPtr, Value);
    if (ConnectedSpacesPlatformDotNetPINVOKE.SWIGPendingException.Pending) throw ConnectedSpacesPlatformDotNetPINVOKE.SWIGPendingException.Retrieve();
  }

  public float GetTimeSincePlay() {
    float ret = ConnectedSpacesPlatformDotNetPINVOKE.csp_multiplayer_VideoPlayerSpaceComponent_GetTimeSincePlay(swigCPtr);
    if (ConnectedSpacesPlatformDotNetPINVOKE.SWIGPendingException.Pending) throw ConnectedSpacesPlatformDotNetPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public void SetTimeSincePlay(float Value) {
    ConnectedSpacesPlatformDotNetPINVOKE.csp_multiplayer_VideoPlayerSpaceComponent_SetTimeSincePlay(swigCPtr, Value);
    if (ConnectedSpacesPlatformDotNetPINVOKE.SWIGPendingException.Pending) throw ConnectedSpacesPlatformDotNetPINVOKE.SWIGPendingException.Retrieve();
  }

  public csp.multiplayer.VideoPlayerSourceType GetVideoPlayerSourceType() {
    csp.multiplayer.VideoPlayerSourceType ret = (csp.multiplayer.VideoPlayerSourceType)ConnectedSpacesPlatformDotNetPINVOKE.csp_multiplayer_VideoPlayerSpaceComponent_GetVideoPlayerSourceType(swigCPtr);
    if (ConnectedSpacesPlatformDotNetPINVOKE.SWIGPendingException.Pending) throw ConnectedSpacesPlatformDotNetPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public void SetVideoPlayerSourceType(csp.multiplayer.VideoPlayerSourceType Value) {
    ConnectedSpacesPlatformDotNetPINVOKE.csp_multiplayer_VideoPlayerSpaceComponent_SetVideoPlayerSourceType(swigCPtr, (int)Value);
    if (ConnectedSpacesPlatformDotNetPINVOKE.SWIGPendingException.Pending) throw ConnectedSpacesPlatformDotNetPINVOKE.SWIGPendingException.Retrieve();
  }

  public csp.multiplayer.StereoVideoType GetStereoVideoType() {
    csp.multiplayer.StereoVideoType ret = (csp.multiplayer.StereoVideoType)ConnectedSpacesPlatformDotNetPINVOKE.csp_multiplayer_VideoPlayerSpaceComponent_GetStereoVideoType(swigCPtr);
    if (ConnectedSpacesPlatformDotNetPINVOKE.SWIGPendingException.Pending) throw ConnectedSpacesPlatformDotNetPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public void SetStereoVideoType(csp.multiplayer.StereoVideoType Value) {
    ConnectedSpacesPlatformDotNetPINVOKE.csp_multiplayer_VideoPlayerSpaceComponent_SetStereoVideoType(swigCPtr, (int)Value);
    if (ConnectedSpacesPlatformDotNetPINVOKE.SWIGPendingException.Pending) throw ConnectedSpacesPlatformDotNetPINVOKE.SWIGPendingException.Retrieve();
  }

  public bool GetIsStereoFlipped() {
    bool ret = ConnectedSpacesPlatformDotNetPINVOKE.csp_multiplayer_VideoPlayerSpaceComponent_GetIsStereoFlipped(swigCPtr);
    if (ConnectedSpacesPlatformDotNetPINVOKE.SWIGPendingException.Pending) throw ConnectedSpacesPlatformDotNetPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public void SetIsStereoFlipped(bool Value) {
    ConnectedSpacesPlatformDotNetPINVOKE.csp_multiplayer_VideoPlayerSpaceComponent_SetIsStereoFlipped(swigCPtr, Value);
    if (ConnectedSpacesPlatformDotNetPINVOKE.SWIGPendingException.Pending) throw ConnectedSpacesPlatformDotNetPINVOKE.SWIGPendingException.Retrieve();
  }

  public virtual csp.multiplayer.AudioType GetAudioType() {
    csp.multiplayer.AudioType ret = (csp.multiplayer.AudioType)ConnectedSpacesPlatformDotNetPINVOKE.csp_multiplayer_VideoPlayerSpaceComponent_GetAudioType(swigCPtr);
    if (ConnectedSpacesPlatformDotNetPINVOKE.SWIGPendingException.Pending) throw ConnectedSpacesPlatformDotNetPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public virtual void SetAudioType(csp.multiplayer.AudioType Value) {
    ConnectedSpacesPlatformDotNetPINVOKE.csp_multiplayer_VideoPlayerSpaceComponent_SetAudioType(swigCPtr, (int)Value);
    if (ConnectedSpacesPlatformDotNetPINVOKE.SWIGPendingException.Pending) throw ConnectedSpacesPlatformDotNetPINVOKE.SWIGPendingException.Retrieve();
  }

  public virtual float GetAttenuationRadius() {
    float ret = ConnectedSpacesPlatformDotNetPINVOKE.csp_multiplayer_VideoPlayerSpaceComponent_GetAttenuationRadius(swigCPtr);
    if (ConnectedSpacesPlatformDotNetPINVOKE.SWIGPendingException.Pending) throw ConnectedSpacesPlatformDotNetPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public virtual void SetAttenuationRadius(float Value) {
    ConnectedSpacesPlatformDotNetPINVOKE.csp_multiplayer_VideoPlayerSpaceComponent_SetAttenuationRadius(swigCPtr, Value);
    if (ConnectedSpacesPlatformDotNetPINVOKE.SWIGPendingException.Pending) throw ConnectedSpacesPlatformDotNetPINVOKE.SWIGPendingException.Retrieve();
  }

  public virtual float GetVolume() {
    float ret = ConnectedSpacesPlatformDotNetPINVOKE.csp_multiplayer_VideoPlayerSpaceComponent_GetVolume(swigCPtr);
    if (ConnectedSpacesPlatformDotNetPINVOKE.SWIGPendingException.Pending) throw ConnectedSpacesPlatformDotNetPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public virtual void SetVolume(float Value) {
    ConnectedSpacesPlatformDotNetPINVOKE.csp_multiplayer_VideoPlayerSpaceComponent_SetVolume(swigCPtr, Value);
    if (ConnectedSpacesPlatformDotNetPINVOKE.SWIGPendingException.Pending) throw ConnectedSpacesPlatformDotNetPINVOKE.SWIGPendingException.Retrieve();
  }

  public virtual bool GetIsVisible() {
    bool ret = ConnectedSpacesPlatformDotNetPINVOKE.csp_multiplayer_VideoPlayerSpaceComponent_GetIsVisible(swigCPtr);
    if (ConnectedSpacesPlatformDotNetPINVOKE.SWIGPendingException.Pending) throw ConnectedSpacesPlatformDotNetPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public virtual void SetIsVisible(bool InValue) {
    ConnectedSpacesPlatformDotNetPINVOKE.csp_multiplayer_VideoPlayerSpaceComponent_SetIsVisible(swigCPtr, InValue);
    if (ConnectedSpacesPlatformDotNetPINVOKE.SWIGPendingException.Pending) throw ConnectedSpacesPlatformDotNetPINVOKE.SWIGPendingException.Retrieve();
  }

  public virtual bool GetIsARVisible() {
    bool ret = ConnectedSpacesPlatformDotNetPINVOKE.csp_multiplayer_VideoPlayerSpaceComponent_GetIsARVisible(swigCPtr);
    if (ConnectedSpacesPlatformDotNetPINVOKE.SWIGPendingException.Pending) throw ConnectedSpacesPlatformDotNetPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public virtual void SetIsARVisible(bool InValue) {
    ConnectedSpacesPlatformDotNetPINVOKE.csp_multiplayer_VideoPlayerSpaceComponent_SetIsARVisible(swigCPtr, InValue);
    if (ConnectedSpacesPlatformDotNetPINVOKE.SWIGPendingException.Pending) throw ConnectedSpacesPlatformDotNetPINVOKE.SWIGPendingException.Retrieve();
  }

  public virtual bool GetIsVirtualVisible() {
    bool ret = ConnectedSpacesPlatformDotNetPINVOKE.csp_multiplayer_VideoPlayerSpaceComponent_GetIsVirtualVisible(swigCPtr);
    if (ConnectedSpacesPlatformDotNetPINVOKE.SWIGPendingException.Pending) throw ConnectedSpacesPlatformDotNetPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public virtual void SetIsVirtualVisible(bool InValue) {
    ConnectedSpacesPlatformDotNetPINVOKE.csp_multiplayer_VideoPlayerSpaceComponent_SetIsVirtualVisible(swigCPtr, InValue);
    if (ConnectedSpacesPlatformDotNetPINVOKE.SWIGPendingException.Pending) throw ConnectedSpacesPlatformDotNetPINVOKE.SWIGPendingException.Retrieve();
  }

  public virtual bool GetIsEnabled() {
    bool ret = ConnectedSpacesPlatformDotNetPINVOKE.csp_multiplayer_VideoPlayerSpaceComponent_GetIsEnabled(swigCPtr);
    if (ConnectedSpacesPlatformDotNetPINVOKE.SWIGPendingException.Pending) throw ConnectedSpacesPlatformDotNetPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public virtual void SetIsEnabled(bool InValue) {
    ConnectedSpacesPlatformDotNetPINVOKE.csp_multiplayer_VideoPlayerSpaceComponent_SetIsEnabled(swigCPtr, InValue);
    if (ConnectedSpacesPlatformDotNetPINVOKE.SWIGPendingException.Pending) throw ConnectedSpacesPlatformDotNetPINVOKE.SWIGPendingException.Retrieve();
  }

  // Any time this object is returned from an outer C++ object via reference, this is set
  // to prevent premature garbage collection causing premature C++ memory deallocation.
  public object OuterObjectPin { private get; set; }

  internal static csp.multiplayer.VideoPlayerSpaceComponent NativeFromBaseCast(csp.multiplayer.ComponentBase baseObj) {
    global::System.IntPtr cPtr = ConnectedSpacesPlatformDotNetPINVOKE.csp_multiplayer_VideoPlayerSpaceComponent_NativeFromBaseCast((baseObj != null && csp.multiplayer.ComponentBase.getCPtr(baseObj).Handle == global::System.IntPtr.Zero) ? throw new global::System.ObjectDisposedException("baseObj", "Passed a disposed C# SWIG wrapper (null native handle) to C++. This indicates an object lifecycle bug needing investigation. Note: This does not detect C++-side deletions.") : csp.multiplayer.ComponentBase.getCPtr(baseObj));
    csp.multiplayer.VideoPlayerSpaceComponent ret = (cPtr == global::System.IntPtr.Zero) ? null : new csp.multiplayer.VideoPlayerSpaceComponent(cPtr, false);
    if (ConnectedSpacesPlatformDotNetPINVOKE.SWIGPendingException.Pending) throw ConnectedSpacesPlatformDotNetPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

}

}
