//------------------------------------------------------------------------------
// <auto-generated />
//
// This file was automatically generated by SWIG (https://www.swig.org).
// Version 4.4.0
//
// Do not make changes to this file unless you know what you are doing - modify
// the SWIG interface file instead.
//------------------------------------------------------------------------------

namespace csp.common {

#nullable enable

public class LoginState : global::System.IDisposable {
  private global::System.Runtime.InteropServices.HandleRef swigCPtr;
  protected bool swigCMemOwn;

  internal LoginState(global::System.IntPtr cPtr, bool cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = new global::System.Runtime.InteropServices.HandleRef(this, cPtr);
  }

  internal static global::System.Runtime.InteropServices.HandleRef getCPtr(LoginState obj) {
    return (obj == null) ? new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero) : obj.swigCPtr;
  }

  internal static global::System.Runtime.InteropServices.HandleRef swigRelease(LoginState obj) {
    if (obj != null) {
      if (!obj.swigCMemOwn)
        throw new global::System.ApplicationException("Cannot release ownership as memory is not owned");
      global::System.Runtime.InteropServices.HandleRef ptr = obj.swigCPtr;
      obj.swigCMemOwn = false;
      obj.Dispose();
      return ptr;
    } else {
      return new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero);
    }
  }

  ~LoginState() {
    Dispose(false);
  }

  public void Dispose() {
    Dispose(true);
    global::System.GC.SuppressFinalize(this);
  }

  protected virtual void Dispose(bool disposing) {
    lock(this) {
      if (swigCPtr.Handle != global::System.IntPtr.Zero) {
        if (swigCMemOwn) {
          swigCMemOwn = false;
          ConnectedSpacesPlatformDotNetPINVOKE.delete_csp_common_LoginState(swigCPtr);
        }
        swigCPtr = new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero);
      }
    }
  }

  public LoginState() : this(ConnectedSpacesPlatformDotNetPINVOKE.new_csp_common_LoginState__SWIG_0(), true) {
    if (ConnectedSpacesPlatformDotNetPINVOKE.SWIGPendingException.Pending) throw ConnectedSpacesPlatformDotNetPINVOKE.SWIGPendingException.Retrieve();
  }

  public LoginState(csp.common.LoginState OtherState) : this(ConnectedSpacesPlatformDotNetPINVOKE.new_csp_common_LoginState__SWIG_1(csp.common.LoginState.getCPtr(OtherState)), true) {
    if (ConnectedSpacesPlatformDotNetPINVOKE.SWIGPendingException.Pending) throw ConnectedSpacesPlatformDotNetPINVOKE.SWIGPendingException.Retrieve();
  }

  public bool RefreshNeeded() {
    bool ret = ConnectedSpacesPlatformDotNetPINVOKE.csp_common_LoginState_RefreshNeeded(swigCPtr);
    if (ConnectedSpacesPlatformDotNetPINVOKE.SWIGPendingException.Pending) throw ConnectedSpacesPlatformDotNetPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public csp.common.ELoginState State {
    set {
      ConnectedSpacesPlatformDotNetPINVOKE.csp_common_LoginState_State_set(swigCPtr, (int)value);
      if (ConnectedSpacesPlatformDotNetPINVOKE.SWIGPendingException.Pending) throw ConnectedSpacesPlatformDotNetPINVOKE.SWIGPendingException.Retrieve();
    } 
    get {
      csp.common.ELoginState ret = (csp.common.ELoginState)ConnectedSpacesPlatformDotNetPINVOKE.csp_common_LoginState_State_get(swigCPtr);
      if (ConnectedSpacesPlatformDotNetPINVOKE.SWIGPendingException.Pending) throw ConnectedSpacesPlatformDotNetPINVOKE.SWIGPendingException.Retrieve();
      return ret;
    } 
  }

  public string AccessToken {
    set {
      ConnectedSpacesPlatformDotNetPINVOKE.csp_common_LoginState_AccessToken_set(swigCPtr, value);
      if (ConnectedSpacesPlatformDotNetPINVOKE.SWIGPendingException.Pending) throw ConnectedSpacesPlatformDotNetPINVOKE.SWIGPendingException.Retrieve();
    } 
    get {
      string ret = ConnectedSpacesPlatformDotNetPINVOKE.csp_common_LoginState_AccessToken_get(swigCPtr);
      if (ConnectedSpacesPlatformDotNetPINVOKE.SWIGPendingException.Pending) throw ConnectedSpacesPlatformDotNetPINVOKE.SWIGPendingException.Retrieve();
      return ret;
    } 
  }

  public string AccessTokenExpiryLength {
    set {
      ConnectedSpacesPlatformDotNetPINVOKE.csp_common_LoginState_AccessTokenExpiryLength_set(swigCPtr, value);
      if (ConnectedSpacesPlatformDotNetPINVOKE.SWIGPendingException.Pending) throw ConnectedSpacesPlatformDotNetPINVOKE.SWIGPendingException.Retrieve();
    } 
    get {
      string ret = ConnectedSpacesPlatformDotNetPINVOKE.csp_common_LoginState_AccessTokenExpiryLength_get(swigCPtr);
      if (ConnectedSpacesPlatformDotNetPINVOKE.SWIGPendingException.Pending) throw ConnectedSpacesPlatformDotNetPINVOKE.SWIGPendingException.Retrieve();
      return ret;
    } 
  }

  public string RefreshToken {
    set {
      ConnectedSpacesPlatformDotNetPINVOKE.csp_common_LoginState_RefreshToken_set(swigCPtr, value);
      if (ConnectedSpacesPlatformDotNetPINVOKE.SWIGPendingException.Pending) throw ConnectedSpacesPlatformDotNetPINVOKE.SWIGPendingException.Retrieve();
    } 
    get {
      string ret = ConnectedSpacesPlatformDotNetPINVOKE.csp_common_LoginState_RefreshToken_get(swigCPtr);
      if (ConnectedSpacesPlatformDotNetPINVOKE.SWIGPendingException.Pending) throw ConnectedSpacesPlatformDotNetPINVOKE.SWIGPendingException.Retrieve();
      return ret;
    } 
  }

  public string RefreshTokenExpiryLength {
    set {
      ConnectedSpacesPlatformDotNetPINVOKE.csp_common_LoginState_RefreshTokenExpiryLength_set(swigCPtr, value);
      if (ConnectedSpacesPlatformDotNetPINVOKE.SWIGPendingException.Pending) throw ConnectedSpacesPlatformDotNetPINVOKE.SWIGPendingException.Retrieve();
    } 
    get {
      string ret = ConnectedSpacesPlatformDotNetPINVOKE.csp_common_LoginState_RefreshTokenExpiryLength_get(swigCPtr);
      if (ConnectedSpacesPlatformDotNetPINVOKE.SWIGPendingException.Pending) throw ConnectedSpacesPlatformDotNetPINVOKE.SWIGPendingException.Retrieve();
      return ret;
    } 
  }

  public string UserId {
    set {
      ConnectedSpacesPlatformDotNetPINVOKE.csp_common_LoginState_UserId_set(swigCPtr, value);
      if (ConnectedSpacesPlatformDotNetPINVOKE.SWIGPendingException.Pending) throw ConnectedSpacesPlatformDotNetPINVOKE.SWIGPendingException.Retrieve();
    } 
    get {
      string ret = ConnectedSpacesPlatformDotNetPINVOKE.csp_common_LoginState_UserId_get(swigCPtr);
      if (ConnectedSpacesPlatformDotNetPINVOKE.SWIGPendingException.Pending) throw ConnectedSpacesPlatformDotNetPINVOKE.SWIGPendingException.Retrieve();
      return ret;
    } 
  }

  public string DeviceId {
    set {
      ConnectedSpacesPlatformDotNetPINVOKE.csp_common_LoginState_DeviceId_set(swigCPtr, value);
      if (ConnectedSpacesPlatformDotNetPINVOKE.SWIGPendingException.Pending) throw ConnectedSpacesPlatformDotNetPINVOKE.SWIGPendingException.Retrieve();
    } 
    get {
      string ret = ConnectedSpacesPlatformDotNetPINVOKE.csp_common_LoginState_DeviceId_get(swigCPtr);
      if (ConnectedSpacesPlatformDotNetPINVOKE.SWIGPendingException.Pending) throw ConnectedSpacesPlatformDotNetPINVOKE.SWIGPendingException.Retrieve();
      return ret;
    } 
  }

  public csp.common.ApplicationSettingsList DefaultApplicationSettings {
    set {
      ConnectedSpacesPlatformDotNetPINVOKE.csp_common_LoginState_DefaultApplicationSettings_set(swigCPtr, csp.common.ApplicationSettingsList.getCPtr(value));
      if (ConnectedSpacesPlatformDotNetPINVOKE.SWIGPendingException.Pending) throw ConnectedSpacesPlatformDotNetPINVOKE.SWIGPendingException.Retrieve();
    } 
    get {
      global::System.IntPtr cPtr = ConnectedSpacesPlatformDotNetPINVOKE.csp_common_LoginState_DefaultApplicationSettings_get(swigCPtr);
      if (ConnectedSpacesPlatformDotNetPINVOKE.SWIGPendingException.Pending) throw ConnectedSpacesPlatformDotNetPINVOKE.SWIGPendingException.Retrieve();
      csp.common.ApplicationSettingsList ret = null;
      if (cPtr != global::System.IntPtr.Zero) {
        ret = new csp.common.ApplicationSettingsList(cPtr, false);
        ret.OuterObjectPin = this;
      }
      return ret;
    }

  }

  public csp.common.SettingsCollectionList DefaultSettings {
    set {
      ConnectedSpacesPlatformDotNetPINVOKE.csp_common_LoginState_DefaultSettings_set(swigCPtr, csp.common.SettingsCollectionList.getCPtr(value));
      if (ConnectedSpacesPlatformDotNetPINVOKE.SWIGPendingException.Pending) throw ConnectedSpacesPlatformDotNetPINVOKE.SWIGPendingException.Retrieve();
    } 
    get {
      global::System.IntPtr cPtr = ConnectedSpacesPlatformDotNetPINVOKE.csp_common_LoginState_DefaultSettings_get(swigCPtr);
      if (ConnectedSpacesPlatformDotNetPINVOKE.SWIGPendingException.Pending) throw ConnectedSpacesPlatformDotNetPINVOKE.SWIGPendingException.Retrieve();
      csp.common.SettingsCollectionList ret = null;
      if (cPtr != global::System.IntPtr.Zero) {
        ret = new csp.common.SettingsCollectionList(cPtr, false);
        ret.OuterObjectPin = this;
      }
      return ret;
    }

  }

  // Any time this object is returned from an outer C++ object via reference, this is set
  // to prevent premature garbage collection causing premature C++ memory deallocation.
  public object OuterObjectPin { private get; set; }

}

}
