//------------------------------------------------------------------------------
// <auto-generated />
//
// This file was automatically generated by SWIG (https://www.swig.org).
// Version 4.4.0
//
// Do not make changes to this file unless you know what you are doing - modify
// the SWIG interface file instead.
//------------------------------------------------------------------------------

namespace csp.common {

#nullable enable

public class LogSystem : global::System.IDisposable {
  private global::System.Runtime.InteropServices.HandleRef swigCPtr;
  protected bool swigCMemOwn;

  internal LogSystem(global::System.IntPtr cPtr, bool cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = new global::System.Runtime.InteropServices.HandleRef(this, cPtr);
  }

  internal static global::System.Runtime.InteropServices.HandleRef getCPtr(LogSystem obj) {
    return (obj == null) ? new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero) : obj.swigCPtr;
  }

  internal static global::System.Runtime.InteropServices.HandleRef swigRelease(LogSystem obj) {
    if (obj != null) {
      if (!obj.swigCMemOwn)
        throw new global::System.ApplicationException("Cannot release ownership as memory is not owned");
      global::System.Runtime.InteropServices.HandleRef ptr = obj.swigCPtr;
      obj.swigCMemOwn = false;
      obj.Dispose();
      return ptr;
    } else {
      return new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero);
    }
  }

  ~LogSystem() {
    Dispose(false);
  }

  public void Dispose() {
    Dispose(true);
    global::System.GC.SuppressFinalize(this);
  }

  protected virtual void Dispose(bool disposing) {
    lock(this) {
      if (swigCPtr.Handle != global::System.IntPtr.Zero) {
        if (swigCMemOwn) {
          swigCMemOwn = false;
          ConnectedSpacesPlatformDotNetPINVOKE.delete_csp_common_LogSystem(swigCPtr);
        }
        swigCPtr = new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero);
      }
    }
  }

  public LogSystem() : this(ConnectedSpacesPlatformDotNetPINVOKE.new_csp_common_LogSystem(), true) {
    if (ConnectedSpacesPlatformDotNetPINVOKE.SWIGPendingException.Pending) throw ConnectedSpacesPlatformDotNetPINVOKE.SWIGPendingException.Retrieve();
  }

  public void SetLogCallback(LogCallbackHandlerAdapter InLogCallback) {
    ConnectedSpacesPlatformDotNetPINVOKE.csp_common_LogSystem_SetLogCallback(swigCPtr, LogCallbackHandlerAdapter.getCPtr(InLogCallback));
    if (ConnectedSpacesPlatformDotNetPINVOKE.SWIGPendingException.Pending) throw ConnectedSpacesPlatformDotNetPINVOKE.SWIGPendingException.Retrieve();
  }

  public void SetEventCallback(EventCallbackHandlerAdapter InEventCallback) {
    ConnectedSpacesPlatformDotNetPINVOKE.csp_common_LogSystem_SetEventCallback(swigCPtr, EventCallbackHandlerAdapter.getCPtr(InEventCallback));
    if (ConnectedSpacesPlatformDotNetPINVOKE.SWIGPendingException.Pending) throw ConnectedSpacesPlatformDotNetPINVOKE.SWIGPendingException.Retrieve();
  }

  public void SetBeginMarkerCallback(BeginMarkerCallbackHandlerAdapter InBeginCallback) {
    ConnectedSpacesPlatformDotNetPINVOKE.csp_common_LogSystem_SetBeginMarkerCallback(swigCPtr, BeginMarkerCallbackHandlerAdapter.getCPtr(InBeginCallback));
    if (ConnectedSpacesPlatformDotNetPINVOKE.SWIGPendingException.Pending) throw ConnectedSpacesPlatformDotNetPINVOKE.SWIGPendingException.Retrieve();
  }

  public void SetEndMarkerCallback(EndMarkerCallbackHandlerAdapter InEndCallback) {
    ConnectedSpacesPlatformDotNetPINVOKE.csp_common_LogSystem_SetEndMarkerCallback(swigCPtr, EndMarkerCallbackHandlerAdapter.getCPtr(InEndCallback));
    if (ConnectedSpacesPlatformDotNetPINVOKE.SWIGPendingException.Pending) throw ConnectedSpacesPlatformDotNetPINVOKE.SWIGPendingException.Retrieve();
  }

  public void SetSystemLevel(csp.common.LogLevel InSystemLevel) {
    ConnectedSpacesPlatformDotNetPINVOKE.csp_common_LogSystem_SetSystemLevel(swigCPtr, (int)InSystemLevel);
    if (ConnectedSpacesPlatformDotNetPINVOKE.SWIGPendingException.Pending) throw ConnectedSpacesPlatformDotNetPINVOKE.SWIGPendingException.Retrieve();
  }

  public csp.common.LogLevel GetSystemLevel() {
    csp.common.LogLevel ret = (csp.common.LogLevel)ConnectedSpacesPlatformDotNetPINVOKE.csp_common_LogSystem_GetSystemLevel(swigCPtr);
    if (ConnectedSpacesPlatformDotNetPINVOKE.SWIGPendingException.Pending) throw ConnectedSpacesPlatformDotNetPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public bool LoggingEnabled(csp.common.LogLevel Level) {
    bool ret = ConnectedSpacesPlatformDotNetPINVOKE.csp_common_LogSystem_LoggingEnabled(swigCPtr, (int)Level);
    if (ConnectedSpacesPlatformDotNetPINVOKE.SWIGPendingException.Pending) throw ConnectedSpacesPlatformDotNetPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public void LogMsg(csp.common.LogLevel Level, string InMessage) {
    ConnectedSpacesPlatformDotNetPINVOKE.csp_common_LogSystem_LogMsg(swigCPtr, (int)Level, InMessage);
    if (ConnectedSpacesPlatformDotNetPINVOKE.SWIGPendingException.Pending) throw ConnectedSpacesPlatformDotNetPINVOKE.SWIGPendingException.Retrieve();
  }

  public void LogEvent(string InEvent) {
    ConnectedSpacesPlatformDotNetPINVOKE.csp_common_LogSystem_LogEvent(swigCPtr, InEvent);
    if (ConnectedSpacesPlatformDotNetPINVOKE.SWIGPendingException.Pending) throw ConnectedSpacesPlatformDotNetPINVOKE.SWIGPendingException.Retrieve();
  }

  public void BeginMarker(string InMarker) {
    ConnectedSpacesPlatformDotNetPINVOKE.csp_common_LogSystem_BeginMarker(swigCPtr, InMarker);
    if (ConnectedSpacesPlatformDotNetPINVOKE.SWIGPendingException.Pending) throw ConnectedSpacesPlatformDotNetPINVOKE.SWIGPendingException.Retrieve();
  }

  public void EndMarker() {
    ConnectedSpacesPlatformDotNetPINVOKE.csp_common_LogSystem_EndMarker(swigCPtr);
    if (ConnectedSpacesPlatformDotNetPINVOKE.SWIGPendingException.Pending) throw ConnectedSpacesPlatformDotNetPINVOKE.SWIGPendingException.Retrieve();
  }

  public void ClearAllCallbacks() {
    ConnectedSpacesPlatformDotNetPINVOKE.csp_common_LogSystem_ClearAllCallbacks(swigCPtr);
    if (ConnectedSpacesPlatformDotNetPINVOKE.SWIGPendingException.Pending) throw ConnectedSpacesPlatformDotNetPINVOKE.SWIGPendingException.Retrieve();
  }


    // Single native action adapter instance for this event
    private ConnectedSpacesPlatformDotNet.LogCallback? _OnLogReceivedAdapter;

    /// <summary>
    /// C# event exposing the native callback.
    /// Subscribers are automatically registered/unregistered with native code.
    /// </summary>
    public event System.Action<csp.common.LogLevel,string> OnLogReceived
    {
        add
        {
            if (_OnLogReceivedAdapter == null)
            {
                // First subscriber, create adapter. Note that this automatically subscribes the passed value.
                _OnLogReceivedAdapter = new ConnectedSpacesPlatformDotNet.LogCallback(value);
                // Register with native code
                SetLogCallback(_OnLogReceivedAdapter);
            }
            else
            {
                // We already had an adapter existing, just subscribe to the event.
                _OnLogReceivedAdapter!.Invoked += value;
                // Note: we should not need to call the SetLogCallback again since it was supposed to be set on adapter creation.
            }
        }
        remove
        {
            if (_OnLogReceivedAdapter == null)
            {
                // This should not happen
                var eventNameAdapter = nameof(_OnLogReceivedAdapter);
                var eventName = nameof(OnLogReceived);

                UnityEngine.Debug.LogError($"{eventNameAdapter} is null when trying to remove subscriber from {eventName}.");

                return;
            }

            _OnLogReceivedAdapter.Invoked -= value;

            if (!_OnLogReceivedAdapter.HasSubscribers)
            {
                // Unregister from native code
                SetLogCallback(null);

                // No more subscribers, clean up adapter
                _OnLogReceivedAdapter = null;
            }
        }
    }


  public void LogAfterSeconds(bool value, int seconds, TestBooleanResultCallbackAdapter callback) {
    ConnectedSpacesPlatformDotNetPINVOKE.csp_common_LogSystem_LogAfterSeconds(swigCPtr, value, seconds, TestBooleanResultCallbackAdapter.getCPtr(callback));
    if (ConnectedSpacesPlatformDotNetPINVOKE.SWIGPendingException.Pending) throw ConnectedSpacesPlatformDotNetPINVOKE.SWIGPendingException.Retrieve();
  }

  public void LogAndThrow(TestBooleanResultCallbackAdapter callback) {
    ConnectedSpacesPlatformDotNetPINVOKE.csp_common_LogSystem_LogAndThrow(swigCPtr, TestBooleanResultCallbackAdapter.getCPtr(callback));
    if (ConnectedSpacesPlatformDotNetPINVOKE.SWIGPendingException.Pending) throw ConnectedSpacesPlatformDotNetPINVOKE.SWIGPendingException.Retrieve();
  }

  public void ThrowImmediately() {
    ConnectedSpacesPlatformDotNetPINVOKE.csp_common_LogSystem_ThrowImmediately(swigCPtr);
    if (ConnectedSpacesPlatformDotNetPINVOKE.SWIGPendingException.Pending) throw ConnectedSpacesPlatformDotNetPINVOKE.SWIGPendingException.Retrieve();
  }


  public System.Threading.Tasks.Task<extra.test.TestBooleanResult> LogAfterSecondsAsync(bool boolValue,int seconds)
  {
    // Create a TaskCompletionSource to represent the async operation.
    System.Threading.Tasks.TaskCompletionSource<extra.test.TestBooleanResult> tcs = 
        new System.Threading.Tasks.TaskCompletionSource<extra.test.TestBooleanResult>(System.Threading.Tasks.TaskCreationOptions.RunContinuationsAsynchronously);

    /*@SWIG:D:\a\connected-spaces-platform-unity\connected-spaces-platform-unity\interface\swigutils\AsyncAdapters.i,129,MAKE_ROOTED_ASYNC_CALLBACK_BODY@*/
    ConnectedSpacesPlatformDotNet.TestBooleanResultCallback callback =
        new ConnectedSpacesPlatformDotNet.TestBooleanResultCallback();

    // Define the callback that will be called by the C++ code
    System.Action<extra.test.TestBooleanResult>? handler = null;
    handler = new ((extra.test.TestBooleanResult result) =>
    {
        try
        {
           /* This is a bit jank. Due to the desire to use passthrough macros between async
            * and actions, we have this result param which yes, can be
            * a comma separated list for action style callbacks, but in async (awaitable) functions,
            * it's only ever a single name.
            * It ISNT always a ResultBase type (although that would simplify things if CSP would do that...)
            * Sometime's it's just a space entity, or a bool, or something else. */

            if((object)result is csp.systems.ResultBase _result)
            {
                // It's a result base

                // Convert the failing result to a throw if we have that option enabled
                _result.ThrowOnFailure(nameof(LogAfterSecondsAsync));


                // Use _result here because we need to call ResultBase api, but we still pass the fully specified type in the TrySetResult
                // Remember that callbacks also have `init` and `inProgress` status's. We will often receive this callback more than once,
                // only finish when we get a final status.  
                if (_result.GetResultCode() == csp.systems.EResultCode.Success ||
                    _result.GetResultCode() == csp.systems.EResultCode.Failed)
                {
                    tcs.TrySetResult(result);
                    // Now that the callback has been invoked and returned success or failure, we no longer need to
                    // await, so we unsubscribe, which should empty the invocation list and unroot the reference for GC. 
                    // Instead, if the result was still pending we would have still needed to await and keep this alive.
                    callback.Invoked -= handler;
                }
            }
            else
            {
                // It's something else
                tcs.TrySetResult(result);
                // Now that the callback has been invoked, we unsubscribe, so that if there is no other subscriber
                // the callback gets automatically unrooted. We do this because we do not expect
                // any more callbacks to come since this is not a ResultBase with pending status. This will
                // trigger the GC of the callback safely, since we no longer await for it.
                callback.Invoked -= handler;
            }
        }
        catch (System.Exception ex)
        {
            // If any other exception occurs, we set it on the task completion source. Failsafe.
            tcs.TrySetException(ex);
        }
    });

    // Subscribe to the callback. 
    // Note that this will automatically root the callback since it has at least one subscriber.
    callback.Invoked += handler;

/*@SWIG@*/;

    // Run the method with the provided arguments and the callback
    // callback is defined in MAKE_AWAITABLE_CALLBACK_BODY
    LogAfterSeconds(boolValue,seconds, callback);

    return tcs.Task;
  }

  public System.Threading.Tasks.Task<extra.test.TestBooleanResult> LogAndThrowAsync()
  {  
    // Create a TaskCompletionSource to represent the async operation.
    System.Threading.Tasks.TaskCompletionSource<extra.test.TestBooleanResult> tcs = 
        new System.Threading.Tasks.TaskCompletionSource<extra.test.TestBooleanResult>(System.Threading.Tasks.TaskCreationOptions.RunContinuationsAsynchronously);

    /*@SWIG:D:\a\connected-spaces-platform-unity\connected-spaces-platform-unity\interface\swigutils\AsyncAdapters.i,129,MAKE_ROOTED_ASYNC_CALLBACK_BODY@*/
    ConnectedSpacesPlatformDotNet.TestBooleanResultCallback callback =
        new ConnectedSpacesPlatformDotNet.TestBooleanResultCallback();

    // Define the callback that will be called by the C++ code
    System.Action<extra.test.TestBooleanResult>? handler = null;
    handler = new ((extra.test.TestBooleanResult result) =>
    {
        try
        {
           /* This is a bit jank. Due to the desire to use passthrough macros between async
            * and actions, we have this result param which yes, can be
            * a comma separated list for action style callbacks, but in async (awaitable) functions,
            * it's only ever a single name.
            * It ISNT always a ResultBase type (although that would simplify things if CSP would do that...)
            * Sometime's it's just a space entity, or a bool, or something else. */

            if((object)result is csp.systems.ResultBase _result)
            {
                // It's a result base

                // Convert the failing result to a throw if we have that option enabled
                _result.ThrowOnFailure(nameof(LogAndThrowAsync));


                // Use _result here because we need to call ResultBase api, but we still pass the fully specified type in the TrySetResult
                // Remember that callbacks also have `init` and `inProgress` status's. We will often receive this callback more than once,
                // only finish when we get a final status.  
                if (_result.GetResultCode() == csp.systems.EResultCode.Success ||
                    _result.GetResultCode() == csp.systems.EResultCode.Failed)
                {
                    tcs.TrySetResult(result);
                    // Now that the callback has been invoked and returned success or failure, we no longer need to
                    // await, so we unsubscribe, which should empty the invocation list and unroot the reference for GC. 
                    // Instead, if the result was still pending we would have still needed to await and keep this alive.
                    callback.Invoked -= handler;
                }
            }
            else
            {
                // It's something else
                tcs.TrySetResult(result);
                // Now that the callback has been invoked, we unsubscribe, so that if there is no other subscriber
                // the callback gets automatically unrooted. We do this because we do not expect
                // any more callbacks to come since this is not a ResultBase with pending status. This will
                // trigger the GC of the callback safely, since we no longer await for it.
                callback.Invoked -= handler;
            }
        }
        catch (System.Exception ex)
        {
            // If any other exception occurs, we set it on the task completion source. Failsafe.
            tcs.TrySetException(ex);
        }
    });

    // Subscribe to the callback. 
    // Note that this will automatically root the callback since it has at least one subscriber.
    callback.Invoked += handler;

/*@SWIG@*/;

    // Run the method with the provided arguments and the callback
    LogAndThrow(callback);

    return tcs.Task;

  }

}

}
