//------------------------------------------------------------------------------
// <auto-generated />
//
// This file was automatically generated by SWIG (https://www.swig.org).
// Version 4.4.0
//
// Do not make changes to this file unless you know what you are doing - modify
// the SWIG interface file instead.
//------------------------------------------------------------------------------

namespace csp.common {

#nullable enable

public class ProductInfoArray : global::System.IDisposable, global::System.Collections.Generic.IReadOnlyList<csp.systems.ProductInfo> {
  private global::System.Runtime.InteropServices.HandleRef swigCPtr;
  protected bool swigCMemOwn;

  internal ProductInfoArray(global::System.IntPtr cPtr, bool cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = new global::System.Runtime.InteropServices.HandleRef(this, cPtr);
  }

  internal static global::System.Runtime.InteropServices.HandleRef getCPtr(ProductInfoArray obj) {
    return (obj == null) ? new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero) : obj.swigCPtr;
  }

  internal static global::System.Runtime.InteropServices.HandleRef swigRelease(ProductInfoArray obj) {
    if (obj != null) {
      if (!obj.swigCMemOwn)
        throw new global::System.ApplicationException("Cannot release ownership as memory is not owned");
      global::System.Runtime.InteropServices.HandleRef ptr = obj.swigCPtr;
      obj.swigCMemOwn = false;
      obj.Dispose();
      return ptr;
    } else {
      return new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero);
    }
  }

  ~ProductInfoArray() {
    Dispose(false);
  }

  public void Dispose() {
    Dispose(true);
    global::System.GC.SuppressFinalize(this);
  }

  protected virtual void Dispose(bool disposing) {
    lock(this) {
      if (swigCPtr.Handle != global::System.IntPtr.Zero) {
        if (swigCMemOwn) {
          swigCMemOwn = false;
          ConnectedSpacesPlatformDotNetPINVOKE.delete_csp_common_ProductInfoArray(swigCPtr);
        }
        swigCPtr = new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero);
      }
    }
  }

  public ProductInfoArray(global::System.Collections.ICollection c) : this(c != null ? (uint)c.Count : 0) {
    if (c == null) {
      // This is the expected error for a null input to a collection.
      // We'd get NullReferenceException if we did't guard the initializer list constructor arg (Count)
      throw new global::System.ArgumentNullException("c");
    } 
    int count = this.Count;
    int i = 0;
    foreach (csp.systems.ProductInfo element in c) {
      if (i >= count)
        break;
      this[i++] = element;
    }
  }

  public csp.systems.ProductInfo this[int index]  {
    get {
      return getitem(index);
    }
    set {
      setitem(index, value);
    }
  }

  public int Count {
    get {
      return (int)Size();
    }
  }

  public void CopyTo(csp.systems.ProductInfo[] array)
  {
    CopyTo(0, array, 0, this.Count);
  }

  public void CopyTo(csp.systems.ProductInfo[] array, int arrayIndex)
  {
    CopyTo(0, array, arrayIndex, this.Count);
  }

  public void CopyTo(int index, csp.systems.ProductInfo[] array, int arrayIndex, int count)
  {
    if (array == null)
      throw new global::System.ArgumentNullException("array");
    if (index < 0)
      throw new global::System.ArgumentOutOfRangeException("index", "Value is less than zero");
    if (arrayIndex < 0)
      throw new global::System.ArgumentOutOfRangeException("arrayIndex", "Value is less than zero");
    if (count < 0)
      throw new global::System.ArgumentOutOfRangeException("count", "Value is less than zero");
    if (array.Rank > 1)
      throw new global::System.ArgumentException("Multi dimensional array.", "array");
    if (index+count > this.Count || arrayIndex+count > array.Length)
      throw new global::System.ArgumentException("Number of elements to copy is too large.");
    for (int i=0; i<count; i++)
      array.SetValue(getitemcopy(index+i), arrayIndex+i);
  }

  public csp.systems.ProductInfo[] DeepCopyToArray()
  {
    int count = this.Count;
    csp.systems.ProductInfo[] result = new csp.systems.ProductInfo[count];
    for (int i = 0; i < count; i++)
      result[i] = getitemcopy(i);
    return result;
  }
  
  public global::System.Collections.Generic.List<csp.systems.ProductInfo> DeepCopyToList()
  {
    int count = this.Count;
    global::System.Collections.Generic.List<csp.systems.ProductInfo> result = 
      new global::System.Collections.Generic.List<csp.systems.ProductInfo>(count);
    for (int i = 0; i < count; i++)
      result.Add(getitemcopy(i));
    return result;
  }

  global::System.Collections.Generic.IEnumerator<csp.systems.ProductInfo> global::System.Collections.Generic.IEnumerable<csp.systems.ProductInfo>.GetEnumerator() {
    return new ProductInfoArrayEnumerator(this);
  }

  global::System.Collections.IEnumerator global::System.Collections.IEnumerable.GetEnumerator() {
    return new ProductInfoArrayEnumerator(this);
  }

  public ProductInfoArrayEnumerator GetEnumerator() {
    return new ProductInfoArrayEnumerator(this);
  }

  // Type-safe enumerator
  /// Note that the IEnumerator documentation requires an InvalidOperationException to be thrown
  /// whenever the collection is modified. This has been done for changes in the size of the
  /// collection but not when one of the elements of the collection is modified as it is a bit
  /// tricky to detect unmanaged code that modifies the collection under our feet.
  public sealed class ProductInfoArrayEnumerator : global::System.Collections.IEnumerator
    , global::System.Collections.Generic.IEnumerator<csp.systems.ProductInfo>
  {
    private ProductInfoArray collectionRef;
    private int currentIndex;
    private object currentObject;
    private int currentSize;

    public ProductInfoArrayEnumerator(ProductInfoArray collection) {
      collectionRef = collection;
      currentIndex = -1;
      currentObject = null;
      currentSize = collectionRef.Count;
    }

    // Type-safe iterator Current
    public csp.systems.ProductInfo Current {
      get {
        if (currentIndex == -1)
          throw new global::System.InvalidOperationException("Enumeration not started.");
        if (currentIndex > currentSize - 1)
          throw new global::System.InvalidOperationException("Enumeration finished.");
        if (currentObject == null)
          throw new global::System.InvalidOperationException("Collection modified.");
        return (csp.systems.ProductInfo)currentObject;
      }
    }

    // Type-unsafe IEnumerator.Current
    object global::System.Collections.IEnumerator.Current {
      get {
        return Current;
      }
    }

    public bool MoveNext() {
      int size = collectionRef.Count;
      bool moveOkay = (currentIndex+1 < size) && (size == currentSize);
      if (moveOkay) {
        currentIndex++;
        currentObject = collectionRef[currentIndex];
      } else {
        currentObject = null;
      }
      return moveOkay;
    }

    public void Reset() {
      currentIndex = -1;
      currentObject = null;
      if (collectionRef.Count != currentSize) {
        throw new global::System.InvalidOperationException("Collection modified.");
      }
    }

    public void Dispose() {
        currentIndex = -1;
        currentObject = null;
    }
  }

  public ProductInfoArray() : this(ConnectedSpacesPlatformDotNetPINVOKE.new_csp_common_ProductInfoArray__SWIG_0(), true) {
    if (ConnectedSpacesPlatformDotNetPINVOKE.SWIGPendingException.Pending) throw ConnectedSpacesPlatformDotNetPINVOKE.SWIGPendingException.Retrieve();
  }

  public ProductInfoArray(uint Size) : this(ConnectedSpacesPlatformDotNetPINVOKE.new_csp_common_ProductInfoArray__SWIG_1(Size), true) {
    if (ConnectedSpacesPlatformDotNetPINVOKE.SWIGPendingException.Pending) throw ConnectedSpacesPlatformDotNetPINVOKE.SWIGPendingException.Retrieve();
  }

  private uint Size() {
    uint ret = ConnectedSpacesPlatformDotNetPINVOKE.csp_common_ProductInfoArray_Size(swigCPtr);
    if (ConnectedSpacesPlatformDotNetPINVOKE.SWIGPendingException.Pending) throw ConnectedSpacesPlatformDotNetPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public bool IsEmpty() {
    bool ret = ConnectedSpacesPlatformDotNetPINVOKE.csp_common_ProductInfoArray_IsEmpty(swigCPtr);
    if (ConnectedSpacesPlatformDotNetPINVOKE.SWIGPendingException.Pending) throw ConnectedSpacesPlatformDotNetPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  private csp.systems.ProductInfo getitemcopy(int index) {
    csp.systems.ProductInfo ret = new csp.systems.ProductInfo(ConnectedSpacesPlatformDotNetPINVOKE.csp_common_ProductInfoArray_getitemcopy(swigCPtr, index), true);
    if (ConnectedSpacesPlatformDotNetPINVOKE.SWIGPendingException.Pending) throw ConnectedSpacesPlatformDotNetPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  private csp.systems.ProductInfo getitem(int index) {
  global::System.IntPtr cPtr = ConnectedSpacesPlatformDotNetPINVOKE.csp_common_ProductInfoArray_getitem(swigCPtr, index);
    if (ConnectedSpacesPlatformDotNetPINVOKE.SWIGPendingException.Pending) throw ConnectedSpacesPlatformDotNetPINVOKE.SWIGPendingException.Retrieve();
  csp.systems.ProductInfo ret = null;
  if (cPtr != global::System.IntPtr.Zero) {
    ret = new csp.systems.ProductInfo(cPtr, false);
    ret.OuterObjectPin = this;
  }
  return ret;
}

  private void setitem(int index, csp.systems.ProductInfo val) {
    ConnectedSpacesPlatformDotNetPINVOKE.csp_common_ProductInfoArray_setitem(swigCPtr, index, csp.systems.ProductInfo.getCPtr(val));
    if (ConnectedSpacesPlatformDotNetPINVOKE.SWIGPendingException.Pending) throw ConnectedSpacesPlatformDotNetPINVOKE.SWIGPendingException.Retrieve();
  }

  public void Reverse() {
    ConnectedSpacesPlatformDotNetPINVOKE.csp_common_ProductInfoArray_Reverse__SWIG_0(swigCPtr);
    if (ConnectedSpacesPlatformDotNetPINVOKE.SWIGPendingException.Pending) throw ConnectedSpacesPlatformDotNetPINVOKE.SWIGPendingException.Retrieve();
  }

  public void Reverse(int index, int count) {
    ConnectedSpacesPlatformDotNetPINVOKE.csp_common_ProductInfoArray_Reverse__SWIG_1(swigCPtr, index, count);
    if (ConnectedSpacesPlatformDotNetPINVOKE.SWIGPendingException.Pending) throw ConnectedSpacesPlatformDotNetPINVOKE.SWIGPendingException.Retrieve();
  }

  public void Fill(csp.systems.ProductInfo value) {
    ConnectedSpacesPlatformDotNetPINVOKE.csp_common_ProductInfoArray_Fill(swigCPtr, csp.systems.ProductInfo.getCPtr(value));
    if (ConnectedSpacesPlatformDotNetPINVOKE.SWIGPendingException.Pending) throw ConnectedSpacesPlatformDotNetPINVOKE.SWIGPendingException.Retrieve();
  }

  // Any time this object is returned from an outer C++ object via reference, this is set
  // to prevent premature garbage collection causing premature C++ memory deallocation.
  public object OuterObjectPin { private get; set; }

}

}
