//------------------------------------------------------------------------------
// <auto-generated />
//
// This file was automatically generated by SWIG (https://www.swig.org).
// Version 4.4.0
//
// Do not make changes to this file unless you know what you are doing - modify
// the SWIG interface file instead.
//------------------------------------------------------------------------------

namespace csp.common {

#nullable enable

public class SettingsCollection : global::System.IDisposable, System.IEquatable<SettingsCollection> {
  private global::System.Runtime.InteropServices.HandleRef swigCPtr;
  protected bool swigCMemOwn;

  internal SettingsCollection(global::System.IntPtr cPtr, bool cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = new global::System.Runtime.InteropServices.HandleRef(this, cPtr);
  }

  internal static global::System.Runtime.InteropServices.HandleRef getCPtr(SettingsCollection obj) {
    return (obj == null) ? new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero) : obj.swigCPtr;
  }

  internal static global::System.Runtime.InteropServices.HandleRef swigRelease(SettingsCollection obj) {
    if (obj != null) {
      if (!obj.swigCMemOwn)
        throw new global::System.ApplicationException("Cannot release ownership as memory is not owned");
      global::System.Runtime.InteropServices.HandleRef ptr = obj.swigCPtr;
      obj.swigCMemOwn = false;
      obj.Dispose();
      return ptr;
    } else {
      return new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero);
    }
  }

  ~SettingsCollection() {
    Dispose(false);
  }

  public void Dispose() {
    Dispose(true);
    global::System.GC.SuppressFinalize(this);
  }

  protected virtual void Dispose(bool disposing) {
    lock(this) {
      if (swigCPtr.Handle != global::System.IntPtr.Zero) {
        if (swigCMemOwn) {
          swigCMemOwn = false;
          ConnectedSpacesPlatformDotNetPINVOKE.delete_csp_common_SettingsCollection(swigCPtr);
        }
        swigCPtr = new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero);
      }
    }
  }


  public bool Equals(SettingsCollection? obj)
  {
    if (ReferenceEquals(this, obj)) return true;
    if (obj is null) return false;
    return NativeEquals(obj);
  }

  public override bool Equals(object? obj) {
    return Equals(obj as SettingsCollection);
  }

  public override int GetHashCode() {

    //GetStdHashCode is size_t, may be different lengths on different platforms
    long hash = (long)GetStdHashCode();

    // GetHashCode wants a 32 bit int, XOR the ptr with itself, shifting the upper part down, so we
    // avoid collisions with values that have the same lower bits but different higher bits.
    // In the case of a 32 bit system, we just shift 0's so this is a no-op.
    // In checked contexts, this cast from long to int can trigger overflow exceptions.
    // `unchecked` prevents this, overflow is well defined in C#, so hashes remain stable.
    return unchecked((int)(hash ^ (hash >> 32)));
  }

  public static bool operator ==(SettingsCollection left, SettingsCollection right)
  {
    if (left is null) return right is null;
    return left.Equals(right);
  }

  public static bool operator !=(SettingsCollection left, SettingsCollection right)
  {
    return !(left == right);
  }


  public SettingsCollection() : this(ConnectedSpacesPlatformDotNetPINVOKE.new_csp_common_SettingsCollection(), true) {
    if (ConnectedSpacesPlatformDotNetPINVOKE.SWIGPendingException.Pending) throw ConnectedSpacesPlatformDotNetPINVOKE.SWIGPendingException.Retrieve();
  }

  public string UserId {
    set {
      ConnectedSpacesPlatformDotNetPINVOKE.csp_common_SettingsCollection_UserId_set(swigCPtr, value);
      if (ConnectedSpacesPlatformDotNetPINVOKE.SWIGPendingException.Pending) throw ConnectedSpacesPlatformDotNetPINVOKE.SWIGPendingException.Retrieve();
    } 
    get {
      string ret = ConnectedSpacesPlatformDotNetPINVOKE.csp_common_SettingsCollection_UserId_get(swigCPtr);
      if (ConnectedSpacesPlatformDotNetPINVOKE.SWIGPendingException.Pending) throw ConnectedSpacesPlatformDotNetPINVOKE.SWIGPendingException.Retrieve();
      return ret;
    } 
  }

  public string Context {
    set {
      ConnectedSpacesPlatformDotNetPINVOKE.csp_common_SettingsCollection_Context_set(swigCPtr, value);
      if (ConnectedSpacesPlatformDotNetPINVOKE.SWIGPendingException.Pending) throw ConnectedSpacesPlatformDotNetPINVOKE.SWIGPendingException.Retrieve();
    } 
    get {
      string ret = ConnectedSpacesPlatformDotNetPINVOKE.csp_common_SettingsCollection_Context_get(swigCPtr);
      if (ConnectedSpacesPlatformDotNetPINVOKE.SWIGPendingException.Pending) throw ConnectedSpacesPlatformDotNetPINVOKE.SWIGPendingException.Retrieve();
      return ret;
    } 
  }

  public csp.common.StringDict Settings {
    set {
      ConnectedSpacesPlatformDotNetPINVOKE.csp_common_SettingsCollection_Settings_set(swigCPtr, (value != null && csp.common.StringDict.getCPtr(value).Handle == global::System.IntPtr.Zero) ? throw new global::System.ObjectDisposedException("value", "Passed a disposed C# SWIG wrapper (null native handle) to C++. This indicates an object lifecycle bug needing investigation. Note: This does not detect C++-side deletions.") : csp.common.StringDict.getCPtr(value));
      if (ConnectedSpacesPlatformDotNetPINVOKE.SWIGPendingException.Pending) throw ConnectedSpacesPlatformDotNetPINVOKE.SWIGPendingException.Retrieve();
    } 
    get {
      global::System.IntPtr cPtr = ConnectedSpacesPlatformDotNetPINVOKE.csp_common_SettingsCollection_Settings_get(swigCPtr);
      if (ConnectedSpacesPlatformDotNetPINVOKE.SWIGPendingException.Pending) throw ConnectedSpacesPlatformDotNetPINVOKE.SWIGPendingException.Retrieve();
      csp.common.StringDict ret = null;
      if (cPtr != global::System.IntPtr.Zero) {
        ret = new csp.common.StringDict(cPtr, false);
        ret.OuterObjectPin = this;
      }
      return ret;
    }

  }

  internal bool NativeEquals(csp.common.SettingsCollection other) {
    bool ret = ConnectedSpacesPlatformDotNetPINVOKE.csp_common_SettingsCollection_NativeEquals(swigCPtr, csp.common.SettingsCollection.getCPtr(other));
    if (ConnectedSpacesPlatformDotNetPINVOKE.SWIGPendingException.Pending) throw ConnectedSpacesPlatformDotNetPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  internal uint GetStdHashCode() {
    uint ret = ConnectedSpacesPlatformDotNetPINVOKE.csp_common_SettingsCollection_GetStdHashCode(swigCPtr);
    if (ConnectedSpacesPlatformDotNetPINVOKE.SWIGPendingException.Pending) throw ConnectedSpacesPlatformDotNetPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  // Any time this object is returned from an outer C++ object via reference, this is set
  // to prevent premature garbage collection causing premature C++ memory deallocation.
  public object OuterObjectPin { private get; set; }

}

}
