//------------------------------------------------------------------------------
// <auto-generated />
//
// This file was automatically generated by SWIG (https://www.swig.org).
// Version 4.4.0
//
// Do not make changes to this file unless you know what you are doing - modify
// the SWIG interface file instead.
//------------------------------------------------------------------------------

namespace csp.common {

#nullable enable

public class Vector2 : global::System.IDisposable, System.IEquatable<Vector2> {
  private global::System.Runtime.InteropServices.HandleRef swigCPtr;
  protected bool swigCMemOwn;

  internal Vector2(global::System.IntPtr cPtr, bool cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = new global::System.Runtime.InteropServices.HandleRef(this, cPtr);
  }

  internal static global::System.Runtime.InteropServices.HandleRef getCPtr(Vector2 obj) {
    return (obj == null) ? new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero) : obj.swigCPtr;
  }

  internal static global::System.Runtime.InteropServices.HandleRef swigRelease(Vector2 obj) {
    if (obj != null) {
      if (!obj.swigCMemOwn)
        throw new global::System.ApplicationException("Cannot release ownership as memory is not owned");
      global::System.Runtime.InteropServices.HandleRef ptr = obj.swigCPtr;
      obj.swigCMemOwn = false;
      obj.Dispose();
      return ptr;
    } else {
      return new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero);
    }
  }

  ~Vector2() {
    Dispose(false);
  }

  public void Dispose() {
    Dispose(true);
    global::System.GC.SuppressFinalize(this);
  }

  protected virtual void Dispose(bool disposing) {
    lock(this) {
      if (swigCPtr.Handle != global::System.IntPtr.Zero) {
        if (swigCMemOwn) {
          swigCMemOwn = false;
          ConnectedSpacesPlatformDotNetPINVOKE.delete_csp_common_Vector2(swigCPtr);
        }
        swigCPtr = new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero);
      }
    }
  }


  public bool Equals(Vector2? obj)
  {
    if (ReferenceEquals(this, obj)) return true;
    if (obj is null) return false;
    return NativeEquals(obj);
  }

  public override bool Equals(object? obj) {
    return Equals(obj as Vector2);
  }

  public override int GetHashCode() {

    //GetStdHashCode is size_t, may be different lengths on different platforms
    long hash = (long)GetStdHashCode();

    // GetHashCode wants a 32 bit int, XOR the ptr with itself, shifting the upper part down, so we
    // avoid collisions with values that have the same lower bits but different higher bits.
    // In the case of a 32 bit system, we just shift 0's so this is a no-op.
    // In checked contexts, this cast from long to int can trigger overflow exceptions.
    // `unchecked` prevents this, overflow is well defined in C#, so hashes remain stable.
    return unchecked((int)(hash ^ (hash >> 32)));
  }

  public static bool operator ==(Vector2 left, Vector2 right)
  {
    if (left is null) return right is null;
    return left.Equals(right);
  }

  public static bool operator !=(Vector2 left, Vector2 right)
  {
    return !(left == right);
  }


  public static csp.common.Vector2 Zero() {
  global::System.IntPtr cPtr = ConnectedSpacesPlatformDotNetPINVOKE.csp_common_Vector2_Zero();
    if (ConnectedSpacesPlatformDotNetPINVOKE.SWIGPendingException.Pending) throw ConnectedSpacesPlatformDotNetPINVOKE.SWIGPendingException.Retrieve();
  csp.common.Vector2 ret = null;
  if (cPtr != global::System.IntPtr.Zero) {
    ret = new csp.common.Vector2(cPtr, false);
  }
  return ret;
}

  public static csp.common.Vector2 One() {
  global::System.IntPtr cPtr = ConnectedSpacesPlatformDotNetPINVOKE.csp_common_Vector2_One();
    if (ConnectedSpacesPlatformDotNetPINVOKE.SWIGPendingException.Pending) throw ConnectedSpacesPlatformDotNetPINVOKE.SWIGPendingException.Retrieve();
  csp.common.Vector2 ret = null;
  if (cPtr != global::System.IntPtr.Zero) {
    ret = new csp.common.Vector2(cPtr, false);
  }
  return ret;
}

  public Vector2() : this(ConnectedSpacesPlatformDotNetPINVOKE.new_csp_common_Vector2__SWIG_0(), true) {
    if (ConnectedSpacesPlatformDotNetPINVOKE.SWIGPendingException.Pending) throw ConnectedSpacesPlatformDotNetPINVOKE.SWIGPendingException.Retrieve();
  }

  public Vector2(float X, float Y) : this(ConnectedSpacesPlatformDotNetPINVOKE.new_csp_common_Vector2__SWIG_1(X, Y), true) {
    if (ConnectedSpacesPlatformDotNetPINVOKE.SWIGPendingException.Pending) throw ConnectedSpacesPlatformDotNetPINVOKE.SWIGPendingException.Retrieve();
  }

  public float x {
    set {
      ConnectedSpacesPlatformDotNetPINVOKE.csp_common_Vector2_x_set(swigCPtr, value);
      if (ConnectedSpacesPlatformDotNetPINVOKE.SWIGPendingException.Pending) throw ConnectedSpacesPlatformDotNetPINVOKE.SWIGPendingException.Retrieve();
    } 
    get {
      float ret = ConnectedSpacesPlatformDotNetPINVOKE.csp_common_Vector2_x_get(swigCPtr);
      if (ConnectedSpacesPlatformDotNetPINVOKE.SWIGPendingException.Pending) throw ConnectedSpacesPlatformDotNetPINVOKE.SWIGPendingException.Retrieve();
      return ret;
    } 
  }

  public float y {
    set {
      ConnectedSpacesPlatformDotNetPINVOKE.csp_common_Vector2_y_set(swigCPtr, value);
      if (ConnectedSpacesPlatformDotNetPINVOKE.SWIGPendingException.Pending) throw ConnectedSpacesPlatformDotNetPINVOKE.SWIGPendingException.Retrieve();
    } 
    get {
      float ret = ConnectedSpacesPlatformDotNetPINVOKE.csp_common_Vector2_y_get(swigCPtr);
      if (ConnectedSpacesPlatformDotNetPINVOKE.SWIGPendingException.Pending) throw ConnectedSpacesPlatformDotNetPINVOKE.SWIGPendingException.Retrieve();
      return ret;
    } 
  }

  internal bool NativeEquals(csp.common.Vector2 other) {
    bool ret = ConnectedSpacesPlatformDotNetPINVOKE.csp_common_Vector2_NativeEquals(swigCPtr, csp.common.Vector2.getCPtr(other));
    if (ConnectedSpacesPlatformDotNetPINVOKE.SWIGPendingException.Pending) throw ConnectedSpacesPlatformDotNetPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  internal uint GetStdHashCode() {
    uint ret = ConnectedSpacesPlatformDotNetPINVOKE.csp_common_Vector2_GetStdHashCode(swigCPtr);
    if (ConnectedSpacesPlatformDotNetPINVOKE.SWIGPendingException.Pending) throw ConnectedSpacesPlatformDotNetPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

#region UNITY EXTENSIONS
    public Vector2(UnityEngine.Vector2 UnityVec2) : this(UnityVec2.x, UnityVec2.y) { }
    public UnityEngine.Vector2 ToUnity() => new UnityEngine.Vector2(x, y);
#endregion

  // Any time this object is returned from an outer C++ object via reference, this is set
  // to prevent premature garbage collection causing premature C++ memory deallocation.
  public object OuterObjectPin { private get; set; }

}

}
