<Project Sdk="Microsoft.NET.Sdk">

	<PropertyGroup>
		<ImplicitUsings>enable</ImplicitUsings>
		<Nullable>enable</Nullable>
		<RootNamespace>InteropTestsXUnit</RootNamespace>
        <CheckForOverflowUnderflow>true</CheckForOverflowUnderflow>
		<TargetFramework>net8.0</TargetFramework>
		 <ExternalRoot>..\install</ExternalRoot>
	</PropertyGroup>

	<ItemGroup>
		<Content Include="xunit.runner.json" CopyToOutputDirectory="PreserveNewest" />
	</ItemGroup>

	<ItemGroup>
		<Using Include="Xunit" />
	</ItemGroup>

	 <ItemGroup>
    	<Compile Include="$(ExternalRoot)\include\**\*.cs" Link="ExternalInclude\%(RecursiveDir)%(Filename)%(Extension)" />
    </ItemGroup>

	<ItemGroup>
		<None Include="$(ExternalRoot)/bin/*ConnectedSpacesPlatform*.*">
			<CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
		</None>
		<None Include="$(ExternalRoot)/lib/*ConnectedSpacesPlatformDotNet*.*">
			<CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
		</None>
	</ItemGroup>

	<ItemGroup>
		<PackageReference Include="Microsoft.Diagnostics.NETCore.Client" Version="0.2.652701" />
		<PackageReference Include="Microsoft.NET.Test.Sdk" Version="17.13.0" />
		<PackageReference Include="xunit.v3" Version="3.1.0" />
		<PackageReference Include="xunit.runner.visualstudio" Version="3.1.5" />
	</ItemGroup>

</Project>
