//------------------------------------------------------------------------------
// <auto-generated />
//
// This file was automatically generated by SWIG (https://www.swig.org).
// Version 4.4.0
//
// Do not make changes to this file unless you know what you are doing - modify
// the SWIG interface file instead.
//------------------------------------------------------------------------------

namespace csp.systems {

#nullable enable

public class Anchor : global::System.IDisposable {
  private global::System.Runtime.InteropServices.HandleRef swigCPtr;
  protected bool swigCMemOwn;

  internal Anchor(global::System.IntPtr cPtr, bool cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = new global::System.Runtime.InteropServices.HandleRef(this, cPtr);
  }

  internal static global::System.Runtime.InteropServices.HandleRef getCPtr(Anchor obj) {
    return (obj == null) ? new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero) : obj.swigCPtr;
  }

  internal static global::System.Runtime.InteropServices.HandleRef swigRelease(Anchor obj) {
    if (obj != null) {
      if (!obj.swigCMemOwn)
        throw new global::System.ApplicationException("Cannot release ownership as memory is not owned");
      global::System.Runtime.InteropServices.HandleRef ptr = obj.swigCPtr;
      obj.swigCMemOwn = false;
      obj.Dispose();
      return ptr;
    } else {
      return new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero);
    }
  }

  ~Anchor() {
    Dispose(false);
  }

  public void Dispose() {
    Dispose(true);
    global::System.GC.SuppressFinalize(this);
  }

  protected virtual void Dispose(bool disposing) {
    lock(this) {
      if (swigCPtr.Handle != global::System.IntPtr.Zero) {
        if (swigCMemOwn) {
          swigCMemOwn = false;
          ConnectedSpacesPlatformDotNetPINVOKE.delete_csp_systems_Anchor(swigCPtr);
        }
        swigCPtr = new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero);
      }
    }
  }

  public Anchor() : this(ConnectedSpacesPlatformDotNetPINVOKE.new_csp_systems_Anchor(), true) {
    if (ConnectedSpacesPlatformDotNetPINVOKE.SWIGPendingException.Pending) throw ConnectedSpacesPlatformDotNetPINVOKE.SWIGPendingException.Retrieve();
  }

  public string Id {
    set {
      ConnectedSpacesPlatformDotNetPINVOKE.csp_systems_Anchor_Id_set(swigCPtr, value);
      if (ConnectedSpacesPlatformDotNetPINVOKE.SWIGPendingException.Pending) throw ConnectedSpacesPlatformDotNetPINVOKE.SWIGPendingException.Retrieve();
    } 
    get {
      string ret = ConnectedSpacesPlatformDotNetPINVOKE.csp_systems_Anchor_Id_get(swigCPtr);
      if (ConnectedSpacesPlatformDotNetPINVOKE.SWIGPendingException.Pending) throw ConnectedSpacesPlatformDotNetPINVOKE.SWIGPendingException.Retrieve();
      return ret;
    } 
  }

  public csp.systems.AnchorProvider ThirdPartyAnchorProvider {
    set {
      ConnectedSpacesPlatformDotNetPINVOKE.csp_systems_Anchor_ThirdPartyAnchorProvider_set(swigCPtr, (int)value);
      if (ConnectedSpacesPlatformDotNetPINVOKE.SWIGPendingException.Pending) throw ConnectedSpacesPlatformDotNetPINVOKE.SWIGPendingException.Retrieve();
    } 
    get {
      csp.systems.AnchorProvider ret = (csp.systems.AnchorProvider)ConnectedSpacesPlatformDotNetPINVOKE.csp_systems_Anchor_ThirdPartyAnchorProvider_get(swigCPtr);
      if (ConnectedSpacesPlatformDotNetPINVOKE.SWIGPendingException.Pending) throw ConnectedSpacesPlatformDotNetPINVOKE.SWIGPendingException.Retrieve();
      return ret;
    } 
  }

  public string ThirdPartyAnchorId {
    set {
      ConnectedSpacesPlatformDotNetPINVOKE.csp_systems_Anchor_ThirdPartyAnchorId_set(swigCPtr, value);
      if (ConnectedSpacesPlatformDotNetPINVOKE.SWIGPendingException.Pending) throw ConnectedSpacesPlatformDotNetPINVOKE.SWIGPendingException.Retrieve();
    } 
    get {
      string ret = ConnectedSpacesPlatformDotNetPINVOKE.csp_systems_Anchor_ThirdPartyAnchorId_get(swigCPtr);
      if (ConnectedSpacesPlatformDotNetPINVOKE.SWIGPendingException.Pending) throw ConnectedSpacesPlatformDotNetPINVOKE.SWIGPendingException.Retrieve();
      return ret;
    } 
  }

  public string CreatedBy {
    set {
      ConnectedSpacesPlatformDotNetPINVOKE.csp_systems_Anchor_CreatedBy_set(swigCPtr, value);
      if (ConnectedSpacesPlatformDotNetPINVOKE.SWIGPendingException.Pending) throw ConnectedSpacesPlatformDotNetPINVOKE.SWIGPendingException.Retrieve();
    } 
    get {
      string ret = ConnectedSpacesPlatformDotNetPINVOKE.csp_systems_Anchor_CreatedBy_get(swigCPtr);
      if (ConnectedSpacesPlatformDotNetPINVOKE.SWIGPendingException.Pending) throw ConnectedSpacesPlatformDotNetPINVOKE.SWIGPendingException.Retrieve();
      return ret;
    } 
  }

  public string CreatedAt {
    set {
      ConnectedSpacesPlatformDotNetPINVOKE.csp_systems_Anchor_CreatedAt_set(swigCPtr, value);
      if (ConnectedSpacesPlatformDotNetPINVOKE.SWIGPendingException.Pending) throw ConnectedSpacesPlatformDotNetPINVOKE.SWIGPendingException.Retrieve();
    } 
    get {
      string ret = ConnectedSpacesPlatformDotNetPINVOKE.csp_systems_Anchor_CreatedAt_get(swigCPtr);
      if (ConnectedSpacesPlatformDotNetPINVOKE.SWIGPendingException.Pending) throw ConnectedSpacesPlatformDotNetPINVOKE.SWIGPendingException.Retrieve();
      return ret;
    } 
  }

  public string SpaceId {
    set {
      ConnectedSpacesPlatformDotNetPINVOKE.csp_systems_Anchor_SpaceId_set(swigCPtr, value);
      if (ConnectedSpacesPlatformDotNetPINVOKE.SWIGPendingException.Pending) throw ConnectedSpacesPlatformDotNetPINVOKE.SWIGPendingException.Retrieve();
    } 
    get {
      string ret = ConnectedSpacesPlatformDotNetPINVOKE.csp_systems_Anchor_SpaceId_get(swigCPtr);
      if (ConnectedSpacesPlatformDotNetPINVOKE.SWIGPendingException.Pending) throw ConnectedSpacesPlatformDotNetPINVOKE.SWIGPendingException.Retrieve();
      return ret;
    } 
  }

  public ulong SpaceEntityId {
    set {
      ConnectedSpacesPlatformDotNetPINVOKE.csp_systems_Anchor_SpaceEntityId_set(swigCPtr, value);
      if (ConnectedSpacesPlatformDotNetPINVOKE.SWIGPendingException.Pending) throw ConnectedSpacesPlatformDotNetPINVOKE.SWIGPendingException.Retrieve();
    } 
    get {
      ulong ret = ConnectedSpacesPlatformDotNetPINVOKE.csp_systems_Anchor_SpaceEntityId_get(swigCPtr);
      if (ConnectedSpacesPlatformDotNetPINVOKE.SWIGPendingException.Pending) throw ConnectedSpacesPlatformDotNetPINVOKE.SWIGPendingException.Retrieve();
      return ret;
    } 
  }

  public string AssetCollectionId {
    set {
      ConnectedSpacesPlatformDotNetPINVOKE.csp_systems_Anchor_AssetCollectionId_set(swigCPtr, value);
      if (ConnectedSpacesPlatformDotNetPINVOKE.SWIGPendingException.Pending) throw ConnectedSpacesPlatformDotNetPINVOKE.SWIGPendingException.Retrieve();
    } 
    get {
      string ret = ConnectedSpacesPlatformDotNetPINVOKE.csp_systems_Anchor_AssetCollectionId_get(swigCPtr);
      if (ConnectedSpacesPlatformDotNetPINVOKE.SWIGPendingException.Pending) throw ConnectedSpacesPlatformDotNetPINVOKE.SWIGPendingException.Retrieve();
      return ret;
    } 
  }

  public csp.systems.GeoLocation Location {
    set {
      ConnectedSpacesPlatformDotNetPINVOKE.csp_systems_Anchor_Location_set(swigCPtr, csp.systems.GeoLocation.getCPtr(value));
      if (ConnectedSpacesPlatformDotNetPINVOKE.SWIGPendingException.Pending) throw ConnectedSpacesPlatformDotNetPINVOKE.SWIGPendingException.Retrieve();
    } 
    get {
      global::System.IntPtr cPtr = ConnectedSpacesPlatformDotNetPINVOKE.csp_systems_Anchor_Location_get(swigCPtr);
      if (ConnectedSpacesPlatformDotNetPINVOKE.SWIGPendingException.Pending) throw ConnectedSpacesPlatformDotNetPINVOKE.SWIGPendingException.Retrieve();
      csp.systems.GeoLocation ret = null;
      if (cPtr != global::System.IntPtr.Zero) {
        ret = new csp.systems.GeoLocation(cPtr, false);
        ret.OuterObjectPin = this;
      }
      return ret;
    }

  }

  public csp.systems.OlyAnchorPosition Position {
    set {
      ConnectedSpacesPlatformDotNetPINVOKE.csp_systems_Anchor_Position_set(swigCPtr, csp.systems.OlyAnchorPosition.getCPtr(value));
      if (ConnectedSpacesPlatformDotNetPINVOKE.SWIGPendingException.Pending) throw ConnectedSpacesPlatformDotNetPINVOKE.SWIGPendingException.Retrieve();
    } 
    get {
      global::System.IntPtr cPtr = ConnectedSpacesPlatformDotNetPINVOKE.csp_systems_Anchor_Position_get(swigCPtr);
      if (ConnectedSpacesPlatformDotNetPINVOKE.SWIGPendingException.Pending) throw ConnectedSpacesPlatformDotNetPINVOKE.SWIGPendingException.Retrieve();
      csp.systems.OlyAnchorPosition ret = null;
      if (cPtr != global::System.IntPtr.Zero) {
        ret = new csp.systems.OlyAnchorPosition(cPtr, false);
        ret.OuterObjectPin = this;
      }
      return ret;
    }

  }

  public csp.systems.OlyRotation Rotation {
    set {
      ConnectedSpacesPlatformDotNetPINVOKE.csp_systems_Anchor_Rotation_set(swigCPtr, csp.systems.OlyRotation.getCPtr(value));
      if (ConnectedSpacesPlatformDotNetPINVOKE.SWIGPendingException.Pending) throw ConnectedSpacesPlatformDotNetPINVOKE.SWIGPendingException.Retrieve();
    } 
    get {
      global::System.IntPtr cPtr = ConnectedSpacesPlatformDotNetPINVOKE.csp_systems_Anchor_Rotation_get(swigCPtr);
      if (ConnectedSpacesPlatformDotNetPINVOKE.SWIGPendingException.Pending) throw ConnectedSpacesPlatformDotNetPINVOKE.SWIGPendingException.Retrieve();
      csp.systems.OlyRotation ret = null;
      if (cPtr != global::System.IntPtr.Zero) {
        ret = new csp.systems.OlyRotation(cPtr, false);
        ret.OuterObjectPin = this;
      }
      return ret;
    }

  }

  public csp.common.StringArray Tags {
    set {
      ConnectedSpacesPlatformDotNetPINVOKE.csp_systems_Anchor_Tags_set(swigCPtr, csp.common.StringArray.getCPtr(value));
      if (ConnectedSpacesPlatformDotNetPINVOKE.SWIGPendingException.Pending) throw ConnectedSpacesPlatformDotNetPINVOKE.SWIGPendingException.Retrieve();
    } 
    get {
      global::System.IntPtr cPtr = ConnectedSpacesPlatformDotNetPINVOKE.csp_systems_Anchor_Tags_get(swigCPtr);
      if (ConnectedSpacesPlatformDotNetPINVOKE.SWIGPendingException.Pending) throw ConnectedSpacesPlatformDotNetPINVOKE.SWIGPendingException.Retrieve();
      csp.common.StringArray ret = null;
      if (cPtr != global::System.IntPtr.Zero) {
        ret = new csp.common.StringArray(cPtr, false);
        ret.OuterObjectPin = this;
      }
      return ret;
    }

  }

  public csp.common.StringDict SpatialKeyValue {
    set {
      ConnectedSpacesPlatformDotNetPINVOKE.csp_systems_Anchor_SpatialKeyValue_set(swigCPtr, csp.common.StringDict.getCPtr(value));
      if (ConnectedSpacesPlatformDotNetPINVOKE.SWIGPendingException.Pending) throw ConnectedSpacesPlatformDotNetPINVOKE.SWIGPendingException.Retrieve();
    } 
    get {
      global::System.IntPtr cPtr = ConnectedSpacesPlatformDotNetPINVOKE.csp_systems_Anchor_SpatialKeyValue_get(swigCPtr);
      if (ConnectedSpacesPlatformDotNetPINVOKE.SWIGPendingException.Pending) throw ConnectedSpacesPlatformDotNetPINVOKE.SWIGPendingException.Retrieve();
      csp.common.StringDict ret = null;
      if (cPtr != global::System.IntPtr.Zero) {
        ret = new csp.common.StringDict(cPtr, false);
        ret.OuterObjectPin = this;
      }
      return ret;
    }

  }

  // Any time this object is returned from an outer C++ object via reference, this is set
  // to prevent premature garbage collection causing premature C++ memory deallocation.
  public object OuterObjectPin { private get; set; }

}

}
