//------------------------------------------------------------------------------
// <auto-generated />
//
// This file was automatically generated by SWIG (https://www.swig.org).
// Version 4.4.0
//
// Do not make changes to this file unless you know what you are doing - modify
// the SWIG interface file instead.
//------------------------------------------------------------------------------

namespace csp.systems {

#nullable enable

public class Asset : global::System.IDisposable {
  private global::System.Runtime.InteropServices.HandleRef swigCPtr;
  protected bool swigCMemOwn;

  internal Asset(global::System.IntPtr cPtr, bool cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = new global::System.Runtime.InteropServices.HandleRef(this, cPtr);
  }

  internal static global::System.Runtime.InteropServices.HandleRef getCPtr(Asset obj) {
    return (obj == null) ? new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero) : obj.swigCPtr;
  }

  internal static global::System.Runtime.InteropServices.HandleRef swigRelease(Asset obj) {
    if (obj != null) {
      if (!obj.swigCMemOwn)
        throw new global::System.ApplicationException("Cannot release ownership as memory is not owned");
      global::System.Runtime.InteropServices.HandleRef ptr = obj.swigCPtr;
      obj.swigCMemOwn = false;
      obj.Dispose();
      return ptr;
    } else {
      return new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero);
    }
  }

  ~Asset() {
    Dispose(false);
  }

  public void Dispose() {
    Dispose(true);
    global::System.GC.SuppressFinalize(this);
  }

  protected virtual void Dispose(bool disposing) {
    lock(this) {
      if (swigCPtr.Handle != global::System.IntPtr.Zero) {
        if (swigCMemOwn) {
          swigCMemOwn = false;
          ConnectedSpacesPlatformDotNetPINVOKE.delete_csp_systems_Asset(swigCPtr);
        }
        swigCPtr = new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero);
      }
    }
  }

  public Asset() : this(ConnectedSpacesPlatformDotNetPINVOKE.new_csp_systems_Asset__SWIG_0(), true) {
    if (ConnectedSpacesPlatformDotNetPINVOKE.SWIGPendingException.Pending) throw ConnectedSpacesPlatformDotNetPINVOKE.SWIGPendingException.Retrieve();
  }

  public Asset(csp.systems.Asset Other) : this(ConnectedSpacesPlatformDotNetPINVOKE.new_csp_systems_Asset__SWIG_1(csp.systems.Asset.getCPtr(Other)), true) {
    if (ConnectedSpacesPlatformDotNetPINVOKE.SWIGPendingException.Pending) throw ConnectedSpacesPlatformDotNetPINVOKE.SWIGPendingException.Retrieve();
  }

  public string AssetCollectionId {
    set {
      ConnectedSpacesPlatformDotNetPINVOKE.csp_systems_Asset_AssetCollectionId_set(swigCPtr, value);
      if (ConnectedSpacesPlatformDotNetPINVOKE.SWIGPendingException.Pending) throw ConnectedSpacesPlatformDotNetPINVOKE.SWIGPendingException.Retrieve();
    } 
    get {
      string ret = ConnectedSpacesPlatformDotNetPINVOKE.csp_systems_Asset_AssetCollectionId_get(swigCPtr);
      if (ConnectedSpacesPlatformDotNetPINVOKE.SWIGPendingException.Pending) throw ConnectedSpacesPlatformDotNetPINVOKE.SWIGPendingException.Retrieve();
      return ret;
    } 
  }

  public string Id {
    set {
      ConnectedSpacesPlatformDotNetPINVOKE.csp_systems_Asset_Id_set(swigCPtr, value);
      if (ConnectedSpacesPlatformDotNetPINVOKE.SWIGPendingException.Pending) throw ConnectedSpacesPlatformDotNetPINVOKE.SWIGPendingException.Retrieve();
    } 
    get {
      string ret = ConnectedSpacesPlatformDotNetPINVOKE.csp_systems_Asset_Id_get(swigCPtr);
      if (ConnectedSpacesPlatformDotNetPINVOKE.SWIGPendingException.Pending) throw ConnectedSpacesPlatformDotNetPINVOKE.SWIGPendingException.Retrieve();
      return ret;
    } 
  }

  public string FileName {
    set {
      ConnectedSpacesPlatformDotNetPINVOKE.csp_systems_Asset_FileName_set(swigCPtr, value);
      if (ConnectedSpacesPlatformDotNetPINVOKE.SWIGPendingException.Pending) throw ConnectedSpacesPlatformDotNetPINVOKE.SWIGPendingException.Retrieve();
    } 
    get {
      string ret = ConnectedSpacesPlatformDotNetPINVOKE.csp_systems_Asset_FileName_get(swigCPtr);
      if (ConnectedSpacesPlatformDotNetPINVOKE.SWIGPendingException.Pending) throw ConnectedSpacesPlatformDotNetPINVOKE.SWIGPendingException.Retrieve();
      return ret;
    } 
  }

  public string Name {
    set {
      ConnectedSpacesPlatformDotNetPINVOKE.csp_systems_Asset_Name_set(swigCPtr, value);
      if (ConnectedSpacesPlatformDotNetPINVOKE.SWIGPendingException.Pending) throw ConnectedSpacesPlatformDotNetPINVOKE.SWIGPendingException.Retrieve();
    } 
    get {
      string ret = ConnectedSpacesPlatformDotNetPINVOKE.csp_systems_Asset_Name_get(swigCPtr);
      if (ConnectedSpacesPlatformDotNetPINVOKE.SWIGPendingException.Pending) throw ConnectedSpacesPlatformDotNetPINVOKE.SWIGPendingException.Retrieve();
      return ret;
    } 
  }

  public string LanguageCode {
    set {
      ConnectedSpacesPlatformDotNetPINVOKE.csp_systems_Asset_LanguageCode_set(swigCPtr, value);
      if (ConnectedSpacesPlatformDotNetPINVOKE.SWIGPendingException.Pending) throw ConnectedSpacesPlatformDotNetPINVOKE.SWIGPendingException.Retrieve();
    } 
    get {
      string ret = ConnectedSpacesPlatformDotNetPINVOKE.csp_systems_Asset_LanguageCode_get(swigCPtr);
      if (ConnectedSpacesPlatformDotNetPINVOKE.SWIGPendingException.Pending) throw ConnectedSpacesPlatformDotNetPINVOKE.SWIGPendingException.Retrieve();
      return ret;
    } 
  }

  public csp.systems.EAssetType Type {
    set {
      ConnectedSpacesPlatformDotNetPINVOKE.csp_systems_Asset_Type_set(swigCPtr, (int)value);
      if (ConnectedSpacesPlatformDotNetPINVOKE.SWIGPendingException.Pending) throw ConnectedSpacesPlatformDotNetPINVOKE.SWIGPendingException.Retrieve();
    } 
    get {
      csp.systems.EAssetType ret = (csp.systems.EAssetType)ConnectedSpacesPlatformDotNetPINVOKE.csp_systems_Asset_Type_get(swigCPtr);
      if (ConnectedSpacesPlatformDotNetPINVOKE.SWIGPendingException.Pending) throw ConnectedSpacesPlatformDotNetPINVOKE.SWIGPendingException.Retrieve();
      return ret;
    } 
  }

  public csp.common.EAssetPlatformArray Platforms {
    set {
      ConnectedSpacesPlatformDotNetPINVOKE.csp_systems_Asset_Platforms_set(swigCPtr, csp.common.EAssetPlatformArray.getCPtr(value));
      if (ConnectedSpacesPlatformDotNetPINVOKE.SWIGPendingException.Pending) throw ConnectedSpacesPlatformDotNetPINVOKE.SWIGPendingException.Retrieve();
    } 
    get {
      global::System.IntPtr cPtr = ConnectedSpacesPlatformDotNetPINVOKE.csp_systems_Asset_Platforms_get(swigCPtr);
      if (ConnectedSpacesPlatformDotNetPINVOKE.SWIGPendingException.Pending) throw ConnectedSpacesPlatformDotNetPINVOKE.SWIGPendingException.Retrieve();
      csp.common.EAssetPlatformArray ret = null;
      if (cPtr != global::System.IntPtr.Zero) {
        ret = new csp.common.EAssetPlatformArray(cPtr, false);
        ret.OuterObjectPin = this;
      }
      return ret;
    }

  }

  public csp.common.StringArray Styles {
    set {
      ConnectedSpacesPlatformDotNetPINVOKE.csp_systems_Asset_Styles_set(swigCPtr, csp.common.StringArray.getCPtr(value));
      if (ConnectedSpacesPlatformDotNetPINVOKE.SWIGPendingException.Pending) throw ConnectedSpacesPlatformDotNetPINVOKE.SWIGPendingException.Retrieve();
    } 
    get {
      global::System.IntPtr cPtr = ConnectedSpacesPlatformDotNetPINVOKE.csp_systems_Asset_Styles_get(swigCPtr);
      if (ConnectedSpacesPlatformDotNetPINVOKE.SWIGPendingException.Pending) throw ConnectedSpacesPlatformDotNetPINVOKE.SWIGPendingException.Retrieve();
      csp.common.StringArray ret = null;
      if (cPtr != global::System.IntPtr.Zero) {
        ret = new csp.common.StringArray(cPtr, false);
        ret.OuterObjectPin = this;
      }
      return ret;
    }

  }

  public string ExternalUri {
    set {
      ConnectedSpacesPlatformDotNetPINVOKE.csp_systems_Asset_ExternalUri_set(swigCPtr, value);
      if (ConnectedSpacesPlatformDotNetPINVOKE.SWIGPendingException.Pending) throw ConnectedSpacesPlatformDotNetPINVOKE.SWIGPendingException.Retrieve();
    } 
    get {
      string ret = ConnectedSpacesPlatformDotNetPINVOKE.csp_systems_Asset_ExternalUri_get(swigCPtr);
      if (ConnectedSpacesPlatformDotNetPINVOKE.SWIGPendingException.Pending) throw ConnectedSpacesPlatformDotNetPINVOKE.SWIGPendingException.Retrieve();
      return ret;
    } 
  }

  public string Uri {
    set {
      ConnectedSpacesPlatformDotNetPINVOKE.csp_systems_Asset_Uri_set(swigCPtr, value);
      if (ConnectedSpacesPlatformDotNetPINVOKE.SWIGPendingException.Pending) throw ConnectedSpacesPlatformDotNetPINVOKE.SWIGPendingException.Retrieve();
    } 
    get {
      string ret = ConnectedSpacesPlatformDotNetPINVOKE.csp_systems_Asset_Uri_get(swigCPtr);
      if (ConnectedSpacesPlatformDotNetPINVOKE.SWIGPendingException.Pending) throw ConnectedSpacesPlatformDotNetPINVOKE.SWIGPendingException.Retrieve();
      return ret;
    } 
  }

  public string Checksum {
    set {
      ConnectedSpacesPlatformDotNetPINVOKE.csp_systems_Asset_Checksum_set(swigCPtr, value);
      if (ConnectedSpacesPlatformDotNetPINVOKE.SWIGPendingException.Pending) throw ConnectedSpacesPlatformDotNetPINVOKE.SWIGPendingException.Retrieve();
    } 
    get {
      string ret = ConnectedSpacesPlatformDotNetPINVOKE.csp_systems_Asset_Checksum_get(swigCPtr);
      if (ConnectedSpacesPlatformDotNetPINVOKE.SWIGPendingException.Pending) throw ConnectedSpacesPlatformDotNetPINVOKE.SWIGPendingException.Retrieve();
      return ret;
    } 
  }

  public int Version {
    set {
      ConnectedSpacesPlatformDotNetPINVOKE.csp_systems_Asset_Version_set(swigCPtr, value);
      if (ConnectedSpacesPlatformDotNetPINVOKE.SWIGPendingException.Pending) throw ConnectedSpacesPlatformDotNetPINVOKE.SWIGPendingException.Retrieve();
    } 
    get {
      int ret = ConnectedSpacesPlatformDotNetPINVOKE.csp_systems_Asset_Version_get(swigCPtr);
      if (ConnectedSpacesPlatformDotNetPINVOKE.SWIGPendingException.Pending) throw ConnectedSpacesPlatformDotNetPINVOKE.SWIGPendingException.Retrieve();
      return ret;
    } 
  }

  public string MimeType {
    set {
      ConnectedSpacesPlatformDotNetPINVOKE.csp_systems_Asset_MimeType_set(swigCPtr, value);
      if (ConnectedSpacesPlatformDotNetPINVOKE.SWIGPendingException.Pending) throw ConnectedSpacesPlatformDotNetPINVOKE.SWIGPendingException.Retrieve();
    } 
    get {
      string ret = ConnectedSpacesPlatformDotNetPINVOKE.csp_systems_Asset_MimeType_get(swigCPtr);
      if (ConnectedSpacesPlatformDotNetPINVOKE.SWIGPendingException.Pending) throw ConnectedSpacesPlatformDotNetPINVOKE.SWIGPendingException.Retrieve();
      return ret;
    } 
  }

  public string ExternalMimeType {
    set {
      ConnectedSpacesPlatformDotNetPINVOKE.csp_systems_Asset_ExternalMimeType_set(swigCPtr, value);
      if (ConnectedSpacesPlatformDotNetPINVOKE.SWIGPendingException.Pending) throw ConnectedSpacesPlatformDotNetPINVOKE.SWIGPendingException.Retrieve();
    } 
    get {
      string ret = ConnectedSpacesPlatformDotNetPINVOKE.csp_systems_Asset_ExternalMimeType_get(swigCPtr);
      if (ConnectedSpacesPlatformDotNetPINVOKE.SWIGPendingException.Pending) throw ConnectedSpacesPlatformDotNetPINVOKE.SWIGPendingException.Retrieve();
      return ret;
    } 
  }

  public string ThirdPartyPackagedAssetIdentifier {
    set {
      ConnectedSpacesPlatformDotNetPINVOKE.csp_systems_Asset_ThirdPartyPackagedAssetIdentifier_set(swigCPtr, value);
      if (ConnectedSpacesPlatformDotNetPINVOKE.SWIGPendingException.Pending) throw ConnectedSpacesPlatformDotNetPINVOKE.SWIGPendingException.Retrieve();
    } 
    get {
      string ret = ConnectedSpacesPlatformDotNetPINVOKE.csp_systems_Asset_ThirdPartyPackagedAssetIdentifier_get(swigCPtr);
      if (ConnectedSpacesPlatformDotNetPINVOKE.SWIGPendingException.Pending) throw ConnectedSpacesPlatformDotNetPINVOKE.SWIGPendingException.Retrieve();
      return ret;
    } 
  }

  public csp.systems.EThirdPartyPlatform ThirdPartyPlatformType {
    set {
      ConnectedSpacesPlatformDotNetPINVOKE.csp_systems_Asset_ThirdPartyPlatformType_set(swigCPtr, (int)value);
      if (ConnectedSpacesPlatformDotNetPINVOKE.SWIGPendingException.Pending) throw ConnectedSpacesPlatformDotNetPINVOKE.SWIGPendingException.Retrieve();
    } 
    get {
      csp.systems.EThirdPartyPlatform ret = (csp.systems.EThirdPartyPlatform)ConnectedSpacesPlatformDotNetPINVOKE.csp_systems_Asset_ThirdPartyPlatformType_get(swigCPtr);
      if (ConnectedSpacesPlatformDotNetPINVOKE.SWIGPendingException.Pending) throw ConnectedSpacesPlatformDotNetPINVOKE.SWIGPendingException.Retrieve();
      return ret;
    } 
  }

  // Any time this object is returned from an outer C++ object via reference, this is set
  // to prevent premature garbage collection causing premature C++ memory deallocation.
  public object OuterObjectPin { private get; set; }

}

}
