//------------------------------------------------------------------------------
// <auto-generated />
//
// This file was automatically generated by SWIG (https://www.swig.org).
// Version 4.4.0
//
// Do not make changes to this file unless you know what you are doing - modify
// the SWIG interface file instead.
//------------------------------------------------------------------------------

namespace csp.systems {

#nullable enable

public class EventTicketingSystem : csp.systems.SystemBase {
  private global::System.Runtime.InteropServices.HandleRef swigCPtr;

  internal EventTicketingSystem(global::System.IntPtr cPtr, bool cMemoryOwn) : base(ConnectedSpacesPlatformDotNetPINVOKE.csp_systems_EventTicketingSystem_SWIGUpcast(cPtr), cMemoryOwn) {
    swigCPtr = new global::System.Runtime.InteropServices.HandleRef(this, cPtr);
  }

  internal static global::System.Runtime.InteropServices.HandleRef getCPtr(EventTicketingSystem obj) {
    return (obj == null) ? new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero) : obj.swigCPtr;
  }

  internal static global::System.Runtime.InteropServices.HandleRef swigRelease(EventTicketingSystem obj) {
    if (obj != null) {
      if (!obj.swigCMemOwn)
        throw new global::System.ApplicationException("Cannot release ownership as memory is not owned");
      global::System.Runtime.InteropServices.HandleRef ptr = obj.swigCPtr;
      obj.swigCMemOwn = false;
      obj.Dispose();
      return ptr;
    } else {
      return new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero);
    }
  }

  protected override void Dispose(bool disposing) {
    lock(this) {
      if (swigCPtr.Handle != global::System.IntPtr.Zero) {
        if (swigCMemOwn) {
          swigCMemOwn = false;
          throw new global::System.MethodAccessException("C++ destructor does not have public access");
        }
        swigCPtr = new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero);
      }
      base.Dispose(disposing);
    }
  }

  public void CreateTicketedEvent(string SpaceId, csp.systems.EventTicketingVendor Vendor, string VendorEventId, string VendorEventUri, bool IsTicketingActive, TicketedEventResultCallbackAdapter Callback) {
    ConnectedSpacesPlatformDotNetPINVOKE.csp_systems_EventTicketingSystem_CreateTicketedEvent(swigCPtr, SpaceId, (int)Vendor, VendorEventId, VendorEventUri, IsTicketingActive, TicketedEventResultCallbackAdapter.getCPtr(Callback));
    if (ConnectedSpacesPlatformDotNetPINVOKE.SWIGPendingException.Pending) throw ConnectedSpacesPlatformDotNetPINVOKE.SWIGPendingException.Retrieve();
  }

  public void UpdateTicketedEvent(string SpaceId, string EventId, csp.systems.EventTicketingVendor? Vendor, string VendorEventId, string VendorEventUri, bool? IsTicketingActive, TicketedEventResultCallbackAdapter Callback) {
    csp.common.OptEventTicketingVendor opt_Vendor = Vendor.HasValue ? new csp.common.OptEventTicketingVendor(Vendor.Value) : new csp.common.OptEventTicketingVendor();
    csp.common.OptBool opt_IsTicketingActive = IsTicketingActive.HasValue ? new csp.common.OptBool(IsTicketingActive.Value) : new csp.common.OptBool();
    {
      ConnectedSpacesPlatformDotNetPINVOKE.csp_systems_EventTicketingSystem_UpdateTicketedEvent(swigCPtr, SpaceId, EventId, csp.common.OptEventTicketingVendor.getCPtr(opt_Vendor), VendorEventId, VendorEventUri, csp.common.OptBool.getCPtr(opt_IsTicketingActive), TicketedEventResultCallbackAdapter.getCPtr(Callback));
      if (ConnectedSpacesPlatformDotNetPINVOKE.SWIGPendingException.Pending) throw ConnectedSpacesPlatformDotNetPINVOKE.SWIGPendingException.Retrieve();
    }
  }

  public void GetTicketedEvents(csp.common.StringArray SpaceIds, int? Skip, int? Limit, TicketedEventCollectionResultCallbackAdapter Callback) {
    csp.common.OptSignedInt32 opt_Skip = Skip.HasValue ? new csp.common.OptSignedInt32(Skip.Value) : new csp.common.OptSignedInt32();
    csp.common.OptSignedInt32 opt_Limit = Limit.HasValue ? new csp.common.OptSignedInt32(Limit.Value) : new csp.common.OptSignedInt32();
    {
      ConnectedSpacesPlatformDotNetPINVOKE.csp_systems_EventTicketingSystem_GetTicketedEvents(swigCPtr, csp.common.StringArray.getCPtr(SpaceIds), csp.common.OptSignedInt32.getCPtr(opt_Skip), csp.common.OptSignedInt32.getCPtr(opt_Limit), TicketedEventCollectionResultCallbackAdapter.getCPtr(Callback));
      if (ConnectedSpacesPlatformDotNetPINVOKE.SWIGPendingException.Pending) throw ConnectedSpacesPlatformDotNetPINVOKE.SWIGPendingException.Retrieve();
    }
  }

  public void SubmitEventTicket(string SpaceId, csp.systems.EventTicketingVendor Vendor, string VendorEventId, string VendorTicketId, string OnBehalfOfUserId, EventTicketResultCallbackAdapter Callback) {
    ConnectedSpacesPlatformDotNetPINVOKE.csp_systems_EventTicketingSystem_SubmitEventTicket(swigCPtr, SpaceId, (int)Vendor, VendorEventId, VendorTicketId, OnBehalfOfUserId, EventTicketResultCallbackAdapter.getCPtr(Callback));
    if (ConnectedSpacesPlatformDotNetPINVOKE.SWIGPendingException.Pending) throw ConnectedSpacesPlatformDotNetPINVOKE.SWIGPendingException.Retrieve();
  }

  public void GetVendorAuthorizeInfo(csp.systems.EventTicketingVendor Vendor, string UserId, TicketedEventVendorAuthInfoResultCallbackAdapter Callback) {
    ConnectedSpacesPlatformDotNetPINVOKE.csp_systems_EventTicketingSystem_GetVendorAuthorizeInfo(swigCPtr, (int)Vendor, UserId, TicketedEventVendorAuthInfoResultCallbackAdapter.getCPtr(Callback));
    if (ConnectedSpacesPlatformDotNetPINVOKE.SWIGPendingException.Pending) throw ConnectedSpacesPlatformDotNetPINVOKE.SWIGPendingException.Retrieve();
  }

  public void GetIsSpaceTicketed(string SpaceId, SpaceIsTicketedResultCallbackAdapter Callback) {
    ConnectedSpacesPlatformDotNetPINVOKE.csp_systems_EventTicketingSystem_GetIsSpaceTicketed(swigCPtr, SpaceId, SpaceIsTicketedResultCallbackAdapter.getCPtr(Callback));
    if (ConnectedSpacesPlatformDotNetPINVOKE.SWIGPendingException.Pending) throw ConnectedSpacesPlatformDotNetPINVOKE.SWIGPendingException.Retrieve();
  }


  public System.Threading.Tasks.Task<csp.systems.TicketedEventResult> CreateTicketedEventAsync(string spaceId,csp.systems.EventTicketingVendor vendor,string vendorEventId,string vendorEventUri,bool isTicketingActive, System.Action<float>? progressCallback = null)
  {
    // Create a TaskCompletionSource to represent the async operation.
    System.Threading.Tasks.TaskCompletionSource<csp.systems.TicketedEventResult> tcs = 
        new System.Threading.Tasks.TaskCompletionSource<csp.systems.TicketedEventResult>(System.Threading.Tasks.TaskCreationOptions.RunContinuationsAsynchronously);

    /*@SWIG:/Users/runner/work/connected-spaces-platform-unity/connected-spaces-platform-unity/interface/swigutils/AsyncAdapters.i,129,MAKE_ROOTED_ASYNC_CALLBACK_BODY@*/
    ConnectedSpacesPlatformDotNet.TicketedEventResultCallback callback =
        new ConnectedSpacesPlatformDotNet.TicketedEventResultCallback();

    // Define the callback that will be called by the C++ code
    System.Action<csp.systems.TicketedEventResult>? handler = null;
    handler = new ((csp.systems.TicketedEventResult result) =>
    {
        try
        {
           /* This is a bit jank. Due to the desire to use passthrough macros between async
            * and actions, we have this result param which yes, can be
            * a comma separated list for action style callbacks, but in async (awaitable) functions,
            * it's only ever a single name.
            * It ISNT always a ResultBase type (although that would simplify things if CSP would do that...)
            * Sometime's it's just a space entity, or a bool, or something else. */

            if((object)result is csp.systems.ResultBase _result)
            {
                // It's a result base

                // Convert the failing result to a throw if we have that option enabled
                _result.ThrowOnFailure(nameof(CreateTicketedEventAsync));


                // Use _result here because we need to call ResultBase api, but we still pass the fully specified type in the TrySetResult
                // Remember that callbacks also have `init` and `inProgress` status's. We will often receive this callback more than once,
                // only finish when we get a final status.  
                if (_result.GetResultCode() == csp.systems.EResultCode.Success ||
                    _result.GetResultCode() == csp.systems.EResultCode.Failed)
                {
                    tcs.TrySetResult(result);
                    // Now that the callback has been invoked and returned success or failure, we no longer need to
                    // await, so we unsubscribe, which should empty the invocation list and unroot the reference for GC. 
                    // Instead, if the result was still pending we would have still needed to await and keep this alive.
                    callback.Invoked -= handler;
                }
                else if (_result.GetResultCode() == csp.systems.EResultCode.InProgress)
                {
                    // Trigger the injected progress callback.
                    progressCallback?.Invoke(_result.GetRequestProgress());
                }
            }
            else
            {
                // It's something else
                tcs.TrySetResult(result);
                // Now that the callback has been invoked, we unsubscribe, so that if there is no other subscriber
                // the callback gets automatically unrooted. We do this because we do not expect
                // any more callbacks to come since this is not a ResultBase with pending status. This will
                // trigger the GC of the callback safely, since we no longer await for it.
                callback.Invoked -= handler;
            }
        }
        catch (System.Exception ex)
        {
            // If any other exception occurs, we set it on the task completion source. Failsafe.
            tcs.TrySetException(ex);
        }
    });

    // Subscribe to the callback. 
    // Note that this will automatically root the callback since it has at least one subscriber.
    callback.Invoked += handler;

/*@SWIG@*/;

    // Run the method with the provided arguments and the callback
    // callback is defined in MAKE_AWAITABLE_CALLBACK_BODY
    CreateTicketedEvent(spaceId,vendor,vendorEventId,vendorEventUri,isTicketingActive, callback);

    return tcs.Task;
  }


  public System.Threading.Tasks.Task<csp.systems.TicketedEventResult> UpdateTicketedEventAsync(string spaceId,string eventId,csp.systems.EventTicketingVendor? vendor,string? vendorEventId,string? vendorEventUri,bool? isTicketingActive, System.Action<float>? progressCallback = null)
  {
    // Create a TaskCompletionSource to represent the async operation.
    System.Threading.Tasks.TaskCompletionSource<csp.systems.TicketedEventResult> tcs = 
        new System.Threading.Tasks.TaskCompletionSource<csp.systems.TicketedEventResult>(System.Threading.Tasks.TaskCreationOptions.RunContinuationsAsynchronously);

    /*@SWIG:/Users/runner/work/connected-spaces-platform-unity/connected-spaces-platform-unity/interface/swigutils/AsyncAdapters.i,129,MAKE_ROOTED_ASYNC_CALLBACK_BODY@*/
    ConnectedSpacesPlatformDotNet.TicketedEventResultCallback callback =
        new ConnectedSpacesPlatformDotNet.TicketedEventResultCallback();

    // Define the callback that will be called by the C++ code
    System.Action<csp.systems.TicketedEventResult>? handler = null;
    handler = new ((csp.systems.TicketedEventResult result) =>
    {
        try
        {
           /* This is a bit jank. Due to the desire to use passthrough macros between async
            * and actions, we have this result param which yes, can be
            * a comma separated list for action style callbacks, but in async (awaitable) functions,
            * it's only ever a single name.
            * It ISNT always a ResultBase type (although that would simplify things if CSP would do that...)
            * Sometime's it's just a space entity, or a bool, or something else. */

            if((object)result is csp.systems.ResultBase _result)
            {
                // It's a result base

                // Convert the failing result to a throw if we have that option enabled
                _result.ThrowOnFailure(nameof(UpdateTicketedEventAsync));


                // Use _result here because we need to call ResultBase api, but we still pass the fully specified type in the TrySetResult
                // Remember that callbacks also have `init` and `inProgress` status's. We will often receive this callback more than once,
                // only finish when we get a final status.  
                if (_result.GetResultCode() == csp.systems.EResultCode.Success ||
                    _result.GetResultCode() == csp.systems.EResultCode.Failed)
                {
                    tcs.TrySetResult(result);
                    // Now that the callback has been invoked and returned success or failure, we no longer need to
                    // await, so we unsubscribe, which should empty the invocation list and unroot the reference for GC. 
                    // Instead, if the result was still pending we would have still needed to await and keep this alive.
                    callback.Invoked -= handler;
                }
                else if (_result.GetResultCode() == csp.systems.EResultCode.InProgress)
                {
                    // Trigger the injected progress callback.
                    progressCallback?.Invoke(_result.GetRequestProgress());
                }
            }
            else
            {
                // It's something else
                tcs.TrySetResult(result);
                // Now that the callback has been invoked, we unsubscribe, so that if there is no other subscriber
                // the callback gets automatically unrooted. We do this because we do not expect
                // any more callbacks to come since this is not a ResultBase with pending status. This will
                // trigger the GC of the callback safely, since we no longer await for it.
                callback.Invoked -= handler;
            }
        }
        catch (System.Exception ex)
        {
            // If any other exception occurs, we set it on the task completion source. Failsafe.
            tcs.TrySetException(ex);
        }
    });

    // Subscribe to the callback. 
    // Note that this will automatically root the callback since it has at least one subscriber.
    callback.Invoked += handler;

/*@SWIG@*/;

    // Run the method with the provided arguments and the callback
    // callback is defined in MAKE_AWAITABLE_CALLBACK_BODY
    UpdateTicketedEvent(spaceId,eventId,vendor,vendorEventId,vendorEventUri,isTicketingActive, callback);

    return tcs.Task;
  }


  public System.Threading.Tasks.Task<csp.systems.TicketedEventCollectionResult> GetTicketedEventsAsync(csp.common.StringArray spaceIds,int? skip,int? limit, System.Action<float>? progressCallback = null)
  {
    // Create a TaskCompletionSource to represent the async operation.
    System.Threading.Tasks.TaskCompletionSource<csp.systems.TicketedEventCollectionResult> tcs = 
        new System.Threading.Tasks.TaskCompletionSource<csp.systems.TicketedEventCollectionResult>(System.Threading.Tasks.TaskCreationOptions.RunContinuationsAsynchronously);

    /*@SWIG:/Users/runner/work/connected-spaces-platform-unity/connected-spaces-platform-unity/interface/swigutils/AsyncAdapters.i,129,MAKE_ROOTED_ASYNC_CALLBACK_BODY@*/
    ConnectedSpacesPlatformDotNet.TicketedEventCollectionResultCallback callback =
        new ConnectedSpacesPlatformDotNet.TicketedEventCollectionResultCallback();

    // Define the callback that will be called by the C++ code
    System.Action<csp.systems.TicketedEventCollectionResult>? handler = null;
    handler = new ((csp.systems.TicketedEventCollectionResult result) =>
    {
        try
        {
           /* This is a bit jank. Due to the desire to use passthrough macros between async
            * and actions, we have this result param which yes, can be
            * a comma separated list for action style callbacks, but in async (awaitable) functions,
            * it's only ever a single name.
            * It ISNT always a ResultBase type (although that would simplify things if CSP would do that...)
            * Sometime's it's just a space entity, or a bool, or something else. */

            if((object)result is csp.systems.ResultBase _result)
            {
                // It's a result base

                // Convert the failing result to a throw if we have that option enabled
                _result.ThrowOnFailure(nameof(GetTicketedEventsAsync));


                // Use _result here because we need to call ResultBase api, but we still pass the fully specified type in the TrySetResult
                // Remember that callbacks also have `init` and `inProgress` status's. We will often receive this callback more than once,
                // only finish when we get a final status.  
                if (_result.GetResultCode() == csp.systems.EResultCode.Success ||
                    _result.GetResultCode() == csp.systems.EResultCode.Failed)
                {
                    tcs.TrySetResult(result);
                    // Now that the callback has been invoked and returned success or failure, we no longer need to
                    // await, so we unsubscribe, which should empty the invocation list and unroot the reference for GC. 
                    // Instead, if the result was still pending we would have still needed to await and keep this alive.
                    callback.Invoked -= handler;
                }
                else if (_result.GetResultCode() == csp.systems.EResultCode.InProgress)
                {
                    // Trigger the injected progress callback.
                    progressCallback?.Invoke(_result.GetRequestProgress());
                }
            }
            else
            {
                // It's something else
                tcs.TrySetResult(result);
                // Now that the callback has been invoked, we unsubscribe, so that if there is no other subscriber
                // the callback gets automatically unrooted. We do this because we do not expect
                // any more callbacks to come since this is not a ResultBase with pending status. This will
                // trigger the GC of the callback safely, since we no longer await for it.
                callback.Invoked -= handler;
            }
        }
        catch (System.Exception ex)
        {
            // If any other exception occurs, we set it on the task completion source. Failsafe.
            tcs.TrySetException(ex);
        }
    });

    // Subscribe to the callback. 
    // Note that this will automatically root the callback since it has at least one subscriber.
    callback.Invoked += handler;

/*@SWIG@*/;

    // Run the method with the provided arguments and the callback
    // callback is defined in MAKE_AWAITABLE_CALLBACK_BODY
    GetTicketedEvents(spaceIds,skip,limit, callback);

    return tcs.Task;
  }


  public System.Threading.Tasks.Task<csp.systems.EventTicketResult> SubmitEventTicketAsync(string spaceId,csp.systems.EventTicketingVendor vendor,string vendorEventId,string vendorTicketId,string? onBehalfOfUserId, System.Action<float>? progressCallback = null)
  {
    // Create a TaskCompletionSource to represent the async operation.
    System.Threading.Tasks.TaskCompletionSource<csp.systems.EventTicketResult> tcs = 
        new System.Threading.Tasks.TaskCompletionSource<csp.systems.EventTicketResult>(System.Threading.Tasks.TaskCreationOptions.RunContinuationsAsynchronously);

    /*@SWIG:/Users/runner/work/connected-spaces-platform-unity/connected-spaces-platform-unity/interface/swigutils/AsyncAdapters.i,129,MAKE_ROOTED_ASYNC_CALLBACK_BODY@*/
    ConnectedSpacesPlatformDotNet.EventTicketResultCallback callback =
        new ConnectedSpacesPlatformDotNet.EventTicketResultCallback();

    // Define the callback that will be called by the C++ code
    System.Action<csp.systems.EventTicketResult>? handler = null;
    handler = new ((csp.systems.EventTicketResult result) =>
    {
        try
        {
           /* This is a bit jank. Due to the desire to use passthrough macros between async
            * and actions, we have this result param which yes, can be
            * a comma separated list for action style callbacks, but in async (awaitable) functions,
            * it's only ever a single name.
            * It ISNT always a ResultBase type (although that would simplify things if CSP would do that...)
            * Sometime's it's just a space entity, or a bool, or something else. */

            if((object)result is csp.systems.ResultBase _result)
            {
                // It's a result base

                // Convert the failing result to a throw if we have that option enabled
                _result.ThrowOnFailure(nameof(SubmitEventTicketAsync));


                // Use _result here because we need to call ResultBase api, but we still pass the fully specified type in the TrySetResult
                // Remember that callbacks also have `init` and `inProgress` status's. We will often receive this callback more than once,
                // only finish when we get a final status.  
                if (_result.GetResultCode() == csp.systems.EResultCode.Success ||
                    _result.GetResultCode() == csp.systems.EResultCode.Failed)
                {
                    tcs.TrySetResult(result);
                    // Now that the callback has been invoked and returned success or failure, we no longer need to
                    // await, so we unsubscribe, which should empty the invocation list and unroot the reference for GC. 
                    // Instead, if the result was still pending we would have still needed to await and keep this alive.
                    callback.Invoked -= handler;
                }
                else if (_result.GetResultCode() == csp.systems.EResultCode.InProgress)
                {
                    // Trigger the injected progress callback.
                    progressCallback?.Invoke(_result.GetRequestProgress());
                }
            }
            else
            {
                // It's something else
                tcs.TrySetResult(result);
                // Now that the callback has been invoked, we unsubscribe, so that if there is no other subscriber
                // the callback gets automatically unrooted. We do this because we do not expect
                // any more callbacks to come since this is not a ResultBase with pending status. This will
                // trigger the GC of the callback safely, since we no longer await for it.
                callback.Invoked -= handler;
            }
        }
        catch (System.Exception ex)
        {
            // If any other exception occurs, we set it on the task completion source. Failsafe.
            tcs.TrySetException(ex);
        }
    });

    // Subscribe to the callback. 
    // Note that this will automatically root the callback since it has at least one subscriber.
    callback.Invoked += handler;

/*@SWIG@*/;

    // Run the method with the provided arguments and the callback
    // callback is defined in MAKE_AWAITABLE_CALLBACK_BODY
    SubmitEventTicket(spaceId,vendor,vendorEventId,vendorTicketId,onBehalfOfUserId, callback);

    return tcs.Task;
  }


  public System.Threading.Tasks.Task<csp.systems.TicketedEventVendorAuthInfoResult> GetVendorAuthorizeInfoAsync(csp.systems.EventTicketingVendor vendor,string userId, System.Action<float>? progressCallback = null)
  {
    // Create a TaskCompletionSource to represent the async operation.
    System.Threading.Tasks.TaskCompletionSource<csp.systems.TicketedEventVendorAuthInfoResult> tcs = 
        new System.Threading.Tasks.TaskCompletionSource<csp.systems.TicketedEventVendorAuthInfoResult>(System.Threading.Tasks.TaskCreationOptions.RunContinuationsAsynchronously);

    /*@SWIG:/Users/runner/work/connected-spaces-platform-unity/connected-spaces-platform-unity/interface/swigutils/AsyncAdapters.i,129,MAKE_ROOTED_ASYNC_CALLBACK_BODY@*/
    ConnectedSpacesPlatformDotNet.TicketedEventVendorAuthorizeInfoCallback callback =
        new ConnectedSpacesPlatformDotNet.TicketedEventVendorAuthorizeInfoCallback();

    // Define the callback that will be called by the C++ code
    System.Action<csp.systems.TicketedEventVendorAuthInfoResult>? handler = null;
    handler = new ((csp.systems.TicketedEventVendorAuthInfoResult result) =>
    {
        try
        {
           /* This is a bit jank. Due to the desire to use passthrough macros between async
            * and actions, we have this result param which yes, can be
            * a comma separated list for action style callbacks, but in async (awaitable) functions,
            * it's only ever a single name.
            * It ISNT always a ResultBase type (although that would simplify things if CSP would do that...)
            * Sometime's it's just a space entity, or a bool, or something else. */

            if((object)result is csp.systems.ResultBase _result)
            {
                // It's a result base

                // Convert the failing result to a throw if we have that option enabled
                _result.ThrowOnFailure(nameof(GetVendorAuthorizeInfoAsync));


                // Use _result here because we need to call ResultBase api, but we still pass the fully specified type in the TrySetResult
                // Remember that callbacks also have `init` and `inProgress` status's. We will often receive this callback more than once,
                // only finish when we get a final status.  
                if (_result.GetResultCode() == csp.systems.EResultCode.Success ||
                    _result.GetResultCode() == csp.systems.EResultCode.Failed)
                {
                    tcs.TrySetResult(result);
                    // Now that the callback has been invoked and returned success or failure, we no longer need to
                    // await, so we unsubscribe, which should empty the invocation list and unroot the reference for GC. 
                    // Instead, if the result was still pending we would have still needed to await and keep this alive.
                    callback.Invoked -= handler;
                }
                else if (_result.GetResultCode() == csp.systems.EResultCode.InProgress)
                {
                    // Trigger the injected progress callback.
                    progressCallback?.Invoke(_result.GetRequestProgress());
                }
            }
            else
            {
                // It's something else
                tcs.TrySetResult(result);
                // Now that the callback has been invoked, we unsubscribe, so that if there is no other subscriber
                // the callback gets automatically unrooted. We do this because we do not expect
                // any more callbacks to come since this is not a ResultBase with pending status. This will
                // trigger the GC of the callback safely, since we no longer await for it.
                callback.Invoked -= handler;
            }
        }
        catch (System.Exception ex)
        {
            // If any other exception occurs, we set it on the task completion source. Failsafe.
            tcs.TrySetException(ex);
        }
    });

    // Subscribe to the callback. 
    // Note that this will automatically root the callback since it has at least one subscriber.
    callback.Invoked += handler;

/*@SWIG@*/;

    // Run the method with the provided arguments and the callback
    // callback is defined in MAKE_AWAITABLE_CALLBACK_BODY
    GetVendorAuthorizeInfo(vendor,userId, callback);

    return tcs.Task;
  }


  public System.Threading.Tasks.Task<csp.systems.SpaceIsTicketedResult> GetIsSpaceTicketedAsync(string spaceId, System.Action<float>? progressCallback = null)
  {
    // Create a TaskCompletionSource to represent the async operation.
    System.Threading.Tasks.TaskCompletionSource<csp.systems.SpaceIsTicketedResult> tcs = 
        new System.Threading.Tasks.TaskCompletionSource<csp.systems.SpaceIsTicketedResult>(System.Threading.Tasks.TaskCreationOptions.RunContinuationsAsynchronously);

    /*@SWIG:/Users/runner/work/connected-spaces-platform-unity/connected-spaces-platform-unity/interface/swigutils/AsyncAdapters.i,129,MAKE_ROOTED_ASYNC_CALLBACK_BODY@*/
    ConnectedSpacesPlatformDotNet.SpaceIsTicketedResultCallback callback =
        new ConnectedSpacesPlatformDotNet.SpaceIsTicketedResultCallback();

    // Define the callback that will be called by the C++ code
    System.Action<csp.systems.SpaceIsTicketedResult>? handler = null;
    handler = new ((csp.systems.SpaceIsTicketedResult result) =>
    {
        try
        {
           /* This is a bit jank. Due to the desire to use passthrough macros between async
            * and actions, we have this result param which yes, can be
            * a comma separated list for action style callbacks, but in async (awaitable) functions,
            * it's only ever a single name.
            * It ISNT always a ResultBase type (although that would simplify things if CSP would do that...)
            * Sometime's it's just a space entity, or a bool, or something else. */

            if((object)result is csp.systems.ResultBase _result)
            {
                // It's a result base

                // Convert the failing result to a throw if we have that option enabled
                _result.ThrowOnFailure(nameof(GetIsSpaceTicketedAsync));


                // Use _result here because we need to call ResultBase api, but we still pass the fully specified type in the TrySetResult
                // Remember that callbacks also have `init` and `inProgress` status's. We will often receive this callback more than once,
                // only finish when we get a final status.  
                if (_result.GetResultCode() == csp.systems.EResultCode.Success ||
                    _result.GetResultCode() == csp.systems.EResultCode.Failed)
                {
                    tcs.TrySetResult(result);
                    // Now that the callback has been invoked and returned success or failure, we no longer need to
                    // await, so we unsubscribe, which should empty the invocation list and unroot the reference for GC. 
                    // Instead, if the result was still pending we would have still needed to await and keep this alive.
                    callback.Invoked -= handler;
                }
                else if (_result.GetResultCode() == csp.systems.EResultCode.InProgress)
                {
                    // Trigger the injected progress callback.
                    progressCallback?.Invoke(_result.GetRequestProgress());
                }
            }
            else
            {
                // It's something else
                tcs.TrySetResult(result);
                // Now that the callback has been invoked, we unsubscribe, so that if there is no other subscriber
                // the callback gets automatically unrooted. We do this because we do not expect
                // any more callbacks to come since this is not a ResultBase with pending status. This will
                // trigger the GC of the callback safely, since we no longer await for it.
                callback.Invoked -= handler;
            }
        }
        catch (System.Exception ex)
        {
            // If any other exception occurs, we set it on the task completion source. Failsafe.
            tcs.TrySetException(ex);
        }
    });

    // Subscribe to the callback. 
    // Note that this will automatically root the callback since it has at least one subscriber.
    callback.Invoked += handler;

/*@SWIG@*/;

    // Run the method with the provided arguments and the callback
    // callback is defined in MAKE_AWAITABLE_CALLBACK_BODY
    GetIsSpaceTicketed(spaceId, callback);

    return tcs.Task;
  }

  // Any time this object is returned from an outer C++ object via reference, this is set
  // to prevent premature garbage collection causing premature C++ memory deallocation.
  public object OuterObjectPin { private get; set; }

}

}
