//------------------------------------------------------------------------------
// <auto-generated />
//
// This file was automatically generated by SWIG (https://www.swig.org).
// Version 4.4.0
//
// Do not make changes to this file unless you know what you are doing - modify
// the SWIG interface file instead.
//------------------------------------------------------------------------------

namespace csp.systems {

#nullable enable

public class InviteUserRoleInfoCollection : global::System.IDisposable {
  private global::System.Runtime.InteropServices.HandleRef swigCPtr;
  protected bool swigCMemOwn;

  internal InviteUserRoleInfoCollection(global::System.IntPtr cPtr, bool cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = new global::System.Runtime.InteropServices.HandleRef(this, cPtr);
  }

  internal static global::System.Runtime.InteropServices.HandleRef getCPtr(InviteUserRoleInfoCollection obj) {
    return (obj == null) ? new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero) : obj.swigCPtr;
  }

  internal static global::System.Runtime.InteropServices.HandleRef swigRelease(InviteUserRoleInfoCollection obj) {
    if (obj != null) {
      if (!obj.swigCMemOwn)
        throw new global::System.ApplicationException("Cannot release ownership as memory is not owned");
      global::System.Runtime.InteropServices.HandleRef ptr = obj.swigCPtr;
      obj.swigCMemOwn = false;
      obj.Dispose();
      return ptr;
    } else {
      return new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero);
    }
  }

  ~InviteUserRoleInfoCollection() {
    Dispose(false);
  }

  public void Dispose() {
    Dispose(true);
    global::System.GC.SuppressFinalize(this);
  }

  protected virtual void Dispose(bool disposing) {
    lock(this) {
      if (swigCPtr.Handle != global::System.IntPtr.Zero) {
        if (swigCMemOwn) {
          swigCMemOwn = false;
          ConnectedSpacesPlatformDotNetPINVOKE.delete_csp_systems_InviteUserRoleInfoCollection(swigCPtr);
        }
        swigCPtr = new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero);
      }
    }
  }

  public InviteUserRoleInfoCollection() : this(ConnectedSpacesPlatformDotNetPINVOKE.new_csp_systems_InviteUserRoleInfoCollection__SWIG_0(), true) {
    if (ConnectedSpacesPlatformDotNetPINVOKE.SWIGPendingException.Pending) throw ConnectedSpacesPlatformDotNetPINVOKE.SWIGPendingException.Retrieve();
  }

  public InviteUserRoleInfoCollection(csp.systems.InviteUserRoleInfoCollection Other) : this(ConnectedSpacesPlatformDotNetPINVOKE.new_csp_systems_InviteUserRoleInfoCollection__SWIG_1(csp.systems.InviteUserRoleInfoCollection.getCPtr(Other)), true) {
    if (ConnectedSpacesPlatformDotNetPINVOKE.SWIGPendingException.Pending) throw ConnectedSpacesPlatformDotNetPINVOKE.SWIGPendingException.Retrieve();
  }

  public string EmailLinkUrl {
    set {
      ConnectedSpacesPlatformDotNetPINVOKE.csp_systems_InviteUserRoleInfoCollection_EmailLinkUrl_set(swigCPtr, value);
      if (ConnectedSpacesPlatformDotNetPINVOKE.SWIGPendingException.Pending) throw ConnectedSpacesPlatformDotNetPINVOKE.SWIGPendingException.Retrieve();
    } 
    get {
      string ret = ConnectedSpacesPlatformDotNetPINVOKE.csp_systems_InviteUserRoleInfoCollection_EmailLinkUrl_get(swigCPtr);
      if (ConnectedSpacesPlatformDotNetPINVOKE.SWIGPendingException.Pending) throw ConnectedSpacesPlatformDotNetPINVOKE.SWIGPendingException.Retrieve();
      return ret;
    } 
  }

  public string SignupUrl {
    set {
      ConnectedSpacesPlatformDotNetPINVOKE.csp_systems_InviteUserRoleInfoCollection_SignupUrl_set(swigCPtr, value);
      if (ConnectedSpacesPlatformDotNetPINVOKE.SWIGPendingException.Pending) throw ConnectedSpacesPlatformDotNetPINVOKE.SWIGPendingException.Retrieve();
    } 
    get {
      string ret = ConnectedSpacesPlatformDotNetPINVOKE.csp_systems_InviteUserRoleInfoCollection_SignupUrl_get(swigCPtr);
      if (ConnectedSpacesPlatformDotNetPINVOKE.SWIGPendingException.Pending) throw ConnectedSpacesPlatformDotNetPINVOKE.SWIGPendingException.Retrieve();
      return ret;
    } 
  }

  public csp.common.InviteUserRoleInfoArray InviteUserRoleInfos {
    set {
      ConnectedSpacesPlatformDotNetPINVOKE.csp_systems_InviteUserRoleInfoCollection_InviteUserRoleInfos_set(swigCPtr, (value != null && csp.common.InviteUserRoleInfoArray.getCPtr(value).Handle == global::System.IntPtr.Zero) ? throw new global::System.ObjectDisposedException("value", "Passed a disposed C# SWIG wrapper (null native handle) to C++. This indicates an object lifecycle bug needing investigation. Note: This does not detect C++-side deletions.") : csp.common.InviteUserRoleInfoArray.getCPtr(value));
      if (ConnectedSpacesPlatformDotNetPINVOKE.SWIGPendingException.Pending) throw ConnectedSpacesPlatformDotNetPINVOKE.SWIGPendingException.Retrieve();
    } 
    get {
      global::System.IntPtr cPtr = ConnectedSpacesPlatformDotNetPINVOKE.csp_systems_InviteUserRoleInfoCollection_InviteUserRoleInfos_get(swigCPtr);
      if (ConnectedSpacesPlatformDotNetPINVOKE.SWIGPendingException.Pending) throw ConnectedSpacesPlatformDotNetPINVOKE.SWIGPendingException.Retrieve();
      csp.common.InviteUserRoleInfoArray ret = null;
      if (cPtr != global::System.IntPtr.Zero) {
        ret = new csp.common.InviteUserRoleInfoArray(cPtr, false);
        ret.OuterObjectPin = this;
      }
      return ret;
    }

  }

  // Any time this object is returned from an outer C++ object via reference, this is set
  // to prevent premature garbage collection causing premature C++ memory deallocation.
  public object OuterObjectPin { private get; set; }

}

}
