# ---------------- Package / Install ----------------

# In the future, this might want to produce something friendlier for CSharp,
# currently it ships the necessary .dll/.so's, as well as the .cs files that serve as includes.
# I'm not totally sure about the ecosystem. Do you ship .csproj files?
# Some variables, like _CSP_LIB_DIR and _CSP_BUILT_SHARED, may be being set
# from the branching between legacy and non legacy builds in the top-level CMakeLists.txt.
# They should be functionally identical as far as the install is concerned for both modes,
# but be aware nonetheless.

set(INSTALL_DIR "${CMAKE_SOURCE_DIR}/install" CACHE FILEPATH "Directory to install output .cs and shared libraries")

# Remove the install dir at install time so old artifacts don't hang around
install(CODE "
  file(REMOVE_RECURSE \"${INSTALL_DIR}\")
")

# Primary install of the generated wrapper binary
install(
  TARGETS ${_WRAPPER_MODULE_NAME}
  RUNTIME DESTINATION "${INSTALL_DIR}/bin" # .exe / .dll on Windows
  LIBRARY DESTINATION "${INSTALL_DIR}/lib" # .so / .dylib on Unix
  ARCHIVE DESTINATION "${INSTALL_DIR}/lib" # .lib static import libraries
)

# Install debug symbols of the wrapper binary in addition
if(MSVC)
  install(
    FILES $<TARGET_PDB_FILE:${_WRAPPER_MODULE_NAME}>
    DESTINATION "${INSTALL_DIR}/bin"
    CONFIGURATIONS Debug RelWithDebInfo #RelWithDebInfo doesn't exist, but it'll want to be here when it does.
  )
endif()

# /cs generated dir, the files you actually work with in Csharp.
install(
  DIRECTORY "${_GEN_CS_DIR}/"
  DESTINATION "${INSTALL_DIR}/include"
)

# Extra C# files to install
# These are additional helper files that aren't generated by SWIG but are part of the CSP C# bindings.
# Functions to convert coordinate systems (from CSP to Unity, etc) and other utilities should be written
# inside the extra/cs/ directory by default, so that they are automatically available to the client as desired.
cmake_path(SET CSP_EXTRA_CS_PATH
    "${CMAKE_BINARY_DIR}/../extra/cs"
    NORMALIZE
)

install(
  DIRECTORY "${CSP_EXTRA_CS_PATH}/"
  DESTINATION "${INSTALL_DIR}/include"
)

# The actual underlying CSP library, needs to sit alongside the bindings.
# Including this makes this a complete artifact.
if (CSP_BUILT_SHARED)
  install(
    FILES $<TARGET_FILE:${_CSP_TARGET_NAME}>
    DESTINATION ${INSTALL_DIR}/bin
  )
endif()

# Finally the underlying CSP's debug symbols on windows platforms (no pdb equivalent on unix).
# TARGET_PDB_FILE is not available for imported targets (why though?)
# So do it more explicitly.
if(MSVC AND CSP_BUILT_SHARED)
  # OPTIONAL: the new (non-legacy) CSP build system does not yet ship PDBs.
  # Once it does, these will start installing automatically with no code change.
  install(FILES "${_CSP_LIB_DIR}/ConnectedSpacesPlatform_D.pdb"
          DESTINATION "${INSTALL_DIR}/bin"
          CONFIGURATIONS Debug
          OPTIONAL)

  install(FILES "${_CSP_LIB_DIR}/ConnectedSpacesPlatform.pdb"
          DESTINATION "${INSTALL_DIR}/bin"
          CONFIGURATIONS RelWithDebInfo
          OPTIONAL)
elseif(APPLE AND CSP_BUILT_SHARED)
    # This is redundant I think, CSP could build DWARF with debug symbols embedded, I don't think dSYMs are the norm?
    # OPTIONAL: the new (non-legacy) CSP build system does not yet ship dSYMs.
    install(DIRECTORY "${_CSP_LIB_DIR}/libConnectedSpacesPlatform_D.dylib.dSYM"
            DESTINATION "${INSTALL_DIR}/bin"
            CONFIGURATIONS Debug
            OPTIONAL)

    install(DIRECTORY "${_CSP_LIB_DIR}/libConnectedSpacesPlatform.dylib.dSYM"
            DESTINATION "${INSTALL_DIR}/bin"
            CONFIGURATIONS RelWithDebInfo
            OPTIONAL)
endif()