# ---------------- Package / Install ----------------

# In the future, this might want to produce something friendlier for CSharp,
# currently it ships the necessary .dll/.so's, as well as the .cs files that serve as includes.
# I'm not totally sure about the ecosystem. Do you ship .csproj files?

set(INSTALL_DIR "${CMAKE_SOURCE_DIR}/install" CACHE FILEPATH "Directory to install output .cs and shared libraries")

# Remove the install dir at install time so old artifacts don't hang around
install(CODE "
  file(REMOVE_RECURSE \"${INSTALL_DIR}\")
")

# Primary install of the generated wrapper binary
install(
  TARGETS ${_WRAPPER_MODULE_NAME}
  RUNTIME DESTINATION "${INSTALL_DIR}/bin" # .exe / .dll on Windows
  LIBRARY DESTINATION "${INSTALL_DIR}/lib" # .so / .dylib on Unix
  ARCHIVE DESTINATION "${INSTALL_DIR}/lib" # .lib static import libraries
)

# Install debug symbols of the wrapper binary in addition
if(MSVC)
  install(
    FILES $<TARGET_PDB_FILE:${_WRAPPER_MODULE_NAME}>
    DESTINATION "${INSTALL_DIR}/bin"
    CONFIGURATIONS Debug
    OPTIONAL
  )
elseif(APPLE)
  install(
    DIRECTORY "$<TARGET_FILE:${_WRAPPER_MODULE_NAME}>.dSYM"
    DESTINATION "${INSTALL_DIR}/bin"
    CONFIGURATIONS Debug RelWithDebInfo #RelWithDebInfo doesn't exist, but it'll want to be here when it does.
    OPTIONAL
  )
endif()

# /cs generated dir, the files you actually work with in Csharp.
install(
  DIRECTORY "${_GEN_CS_DIR}/"
  DESTINATION "${INSTALL_DIR}/include"
)

# Extra C# files to install
# These are additional helper files that aren't generated by SWIG but are part of the CSP C# bindings.
# Functions to convert coordinate systems (from CSP to Unity, etc) and other utilities should be written
# inside the extra/cs/ directory by default, so that they are automatically available to the client as desired.
cmake_path(SET CSP_EXTRA_CS_PATH
    "${CMAKE_BINARY_DIR}/../extra/cs"
    NORMALIZE
)

install(
  DIRECTORY "${CSP_EXTRA_CS_PATH}/"
  DESTINATION "${INSTALL_DIR}/include"
)

# ---------------- CSP Runtime (only if shared) ----------------

get_target_property(_CSP_TYPE _CSP TYPE)

if(_CSP_TYPE STREQUAL "SHARED_LIBRARY")
  message(STATUS "Installing CSP as shared runtime dependency")

  install(
    TARGETS _CSP
    RUNTIME DESTINATION "${INSTALL_DIR}/bin"
    LIBRARY DESTINATION "${INSTALL_DIR}/lib"
  )

  if(MSVC)
    install(FILES "${_CSP_LIB_DIR}/ConnectedSpacesPlatform_D.pdb"
            DESTINATION "${INSTALL_DIR}/bin"
            CONFIGURATIONS Debug)

    install(FILES "${_CSP_LIB_DIR}/ConnectedSpacesPlatform.pdb"
            DESTINATION "${INSTALL_DIR}/bin"
            CONFIGURATIONS RelWithDebInfo)
  elseif(APPLE)
    # This is redundant I think, CSP could build DWARF with debug symbols embedded, I don't think dSYMs are the norm?
    install(DIRECTORY "${_CSP_LIB_DIR}/libConnectedSpacesPlatform_D.dylib.dSYM"
            DESTINATION "${INSTALL_DIR}/bin"
            CONFIGURATIONS Debug)
          
    install(DIRECTORY "${_CSP_LIB_DIR}/libConnectedSpacesPlatform.dylib.dSYM"
            DESTINATION "${INSTALL_DIR}/bin"
            CONFIGURATIONS RelWithDebInfo)
  endif()
else()
  message(STATUS "CSP is static and embedded — not installing CSP separately")
endif()