name: CMake Build Desktop

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:
    inputs:
      unity_ext_matrix:
        description: 'This parameter establishes whether SWIG should generate the additional bindings for supporting Unity applications (true) or just the code for supporting general purpose .NET C# applications (false). This is expected to be a JSON array: it is possible to produce both cases by passing [true, false].'
        required: false
        default: '[true, false]'
      csp_branch: 
        description: 'If set, will build a specific version of CSP from a CSP branch using the new cmake build system, then run with that.'
        type: string
        required: false
        default: ''
  workflow_call: # Allows other workflows to call this one and wait for its artifacts
    inputs:
      unity_ext_matrix:
        type: string
        required: false
        default: '[true, false]'
      csp_branch: # If set, will build a specific version of CSP from a CSP branch using the new cmake build system, then run with that.
        type: string
        required: false
        default: ''

env:
  BUILDING_FROM_BRANCH: ${{ inputs.csp_branch != '' }}

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        os: [windows-latest, macos-latest]
        build_type: [Debug, Release]
        # If an input is provided, parse it. Otherwise, default to building both.
        build_with_unity_extensions: ${{ fromJSON(inputs.unity_ext_matrix || '[true, false]') }}

    runs-on: ${{ matrix.os }}
    env:
      GH_TOKEN: ${{ github.token }}

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup .NET
        uses: actions/setup-dotnet@v5
        with:
          dotnet-version: '8.x'

      - name: Build CSP
        if: env.BUILDING_FROM_BRANCH == 'true' && runner.os == 'Windows'
        uses: ./.github/actions/build-csp-windows
        with:
          csp_branch: ${{inputs.csp_branch}}
          build_type: ${{ matrix.build_type }}

      - name: Install CSP Consumer Dependencies (temp) # We shouldn't need to do this forever, the new CSP build system is just under development and we haven't properly expunged public symbols yet.
        if: env.BUILDING_FROM_BRANCH == 'true' && runner.os == 'Windows'
        run: |
          pip install "conan==2.27.0"
          conan install . --output-folder=build --build=missing -s build_type=${{ matrix.build_type }};

      - name: Configure
        run: > 
          cmake -S . -B build 
          -DENABLE_UNITY_EXTENSIONS=${{ matrix.build_with_unity_extensions && 'ON' || 'OFF' }}
          ${{ env.BUILDING_FROM_BRANCH == 'true' && '-DLEGACY_BUILD_SYSTEM=Off' || '' }}
          ${{ env.BUILDING_FROM_BRANCH == 'true' && format('-DCMAKE_PREFIX_PATH={0}/CSP/install', github.workspace) || '' }}
          ${{ env.BUILDING_FROM_BRANCH == 'true' && '-DCMAKE_TOOLCHAIN_FILE="build/conan_toolchain.cmake"' || '' }}

      - name: Build
        run: cmake --build build --config ${{ matrix.build_type }} 
        env:
          CMAKE_BUILD_PARALLEL_LEVEL: ${{ runner.job_count }}

      - name: Install
        run: cmake --install build --config ${{ matrix.build_type }}

      - name: Test
        # We cannot run XUnit tests with Unity extensions enabled because Unity classes would not be found causing a build failure.
        if: ${{ matrix.build_with_unity_extensions == false }}
        env:
          RUN_LONG_RUNNING_TESTS: 1
        run: | #TODO: Upload the .dmp file when this test fails for easier debugging.
          dotnet test -c ${{ matrix.build_type }} --logger "console;verbosity=detailed" --blame-hang --blame-hang-timeout 90s
        working-directory: ./InteropTestsXUnit

      - name: Upload build artifacts
        uses: actions/upload-artifact@v4
        with:
          name: desktop-${{ matrix.os }}-${{ matrix.build_type }}${{ matrix.build_with_unity_extensions && '-Unity' || '-DotNet' }}
          path: install/**
          if-no-files-found: error
